### PR TITLE
fix(bitfinex2): fix #18169 - fix partially filled status

### LINKED ISSUE #18169: Bitfinex2 pro parseWsOrderStatusis not working
### Operating System

linux

### Programming Languages

JS

### CCXT Version

3.1.31

### Description

The parseWsOrderStatus method is not working properly, so I am getting the raw status from Bitfinex.

````
...

info: [
...
    'EXCHANGE LIMIT',
      null,
      null,
      null,
      0,
      'PARTIALLY FILLED @ 27077.0(0.001)',
      null,
      null,
      27077,
      27077,

...
],
...
   symbol: 'TESTBTC/TESTUSD',
    type: 'limit',
    side: 'buy',
    price: 27077,
    stopPrice: undefined,
    triggerPrice: undefined,
    average: 27077,
    amount: 0.002,
    remaining: 0.001,
    filled: 0.001,
    status: 'PARTIALLY',
    fee: undefined,
    cost: 27.077,
    trades: [],
    fees: [],
...
```

### Code

parseWsOrderStatus vs parseOrderStatus:

```
   parseWsOrderStatus(status) {
        const statuses = {
            'ACTIVE': 'open',
            'CANCELED': 'canceled',
            'EXECUTED': 'closed',
            'PARTIALLY FILLED': 'open',
        };
        return this.safeString(statuses, status, status);
    }

    parseWsOrder(...
...
        const rawState = this.safeString(order, 13);
        const stateParts = rawState.split(' ');
        const trimmedStatus = this.safeString(stateParts, 0);
        const status = this.parseWsOrderStatus(trimmedStatus);
....
```
```
parseOrderStatus(status) {
        if (status === undefined) {
            return status;
        }
        const parts = status.split(' ');
        const state = this.safeString(parts, 0);
        const statuses = {
            'ACTIVE': 'open',
            'PARTIALLY': 'open',
            'EXECUTED': 'closed',
            'CANCELED': 'canceled',
            'INSUFFICIENT': 'canceled',
            'POSTONLY CANCELED': 'canceled',
            'RSN_DUST': 'rejected',
            'RSN_PAUSE': 'rejected',
            'IOC CANCELED': 'canceled',
            'FILLORKILL CANCELED': 'canceled',
        };
        return this.safeString(statuses, state, status);
    }

```

### PR DESCRIPTION
**Pull request by pcriadoperez**

### CODE REVIEW

File: ts/src/pro/bitfinex2.ts [hunk 1]
```diff
@@ -993,7 +993,7 @@ export default class bitfinex2 extends bitfinex2Rest {
             'ACTIVE': 'open',
             'CANCELED': 'canceled',
             'EXECUTED': 'closed',
-            'PARTIALLY FILLED': 'open',
+            'PARTIALLY': 'open',
```
Comment (carlosmiei) [inline ts/src/pro/bitfinex2.ts:996]: @pcriadoperez This is only working because we break the original order status by space and take the first element, which is a bit hacky, but ok, we can improve it later. 
image

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]
