### PR TITLE
fix(okx): fix #22228

### LINKED ISSUE #22228: ccxtpro bug: the watched ohlcvs cache in OKX exchange not updated
### Operating System

centos8

### Programming Languages

Python

### CCXT Version

4.2.100

### Description

The cache of ohlcvs in OKX exchange are not updated after function watch_ohlcv() langched for a while(about 1 hour in my program), however the same code for Binance is well. I tried running it for several times and got the same fault in OKX and the right result in Binance.

### Code

```
   await ex.watch_ohlcv(symbol, timeframe)
   while True:
       ohlcvs = ex.ohlcvs[symbol][timeframe]  # the candles info is not updated after the program running a while
         print(ohlcvs)

```

### PR DESCRIPTION
**Pull request by pcriadoperez**
- Add missing errors
- Fix OKX throwing errors
- Throw Exchange error when error code is not found

### CODE REVIEW

File: ts/src/pro/okx.ts [hunk 1]
```diff
@@ -1557,27 +1557,20 @@ export default class okx extends okxRest {
...
                 const feedback = this.id + ' ' + this.json (message);
                 this.throwExactlyMatchedException (this.exceptions['exact'], errorCode, feedback);
                 const messageString = this.safeValue (message, 'msg');
                 if (messageString !== undefined) {
                     this.throwBroadlyMatchedException (this.exceptions['broad'], messageString, feedback);
                 }
+                throw new ExchangeError (feedback);
             }
         } catch (e) {
-            if (e instanceof AuthenticationError) {
```
Comment (pcriadoperez) [inline ts/src/pro/okx.ts:1571]: Removed this as many times authenticantion errors are thrown from other messageHashes not only 'authenticated'
