### PR TITLE
Woo exchange

### LINKED ISSUE #10536: WOO X Exchange
Hello,

Do you plan on adding support for WOO X Exchange ?
https://woo.org/

API Documentation: https://kronosresearch.github.io/wootrade-documents

That would be a lovely addition due to the low fees of this exchange.

### LINKED ISSUE #11655: woo x exchange support.
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

### PR DESCRIPTION
**Pull request by ttodua**
Woo exchange

[ fixes #10536 ; fixes #11655 ]

### CODE REVIEW

**Comment by kroitor** [comment]
@ttodua let's first make sure that is passes the build at minimum. Then we will add more methods to it, if necessary.

File: js/woo.js [hunk 1]
```diff
@@ -0,0 +1,984 @@
...
+        }
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const request = {
+            'symbol': market['id'],
+        };
+        if (limit !== undefined) {
+            request['limit'] = limit;
+        }
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('fetchTrades', market, params);
```
Comment (kroitor) [inline js/woo.js:298]: Do they have any other type of markets, other than `spot` ? If not, and it's always a `spot` market, then we should remove handleMarketTypeAndParams from here.

File: js/woo.js [hunk 2]
```diff
@@ -0,0 +1,984 @@
...
+                'margin': false,
+                'swap': false,
+                'future': false,
+                'option': false,
+                'active': undefined,
+                'contract': false,
+                'linear': undefined,
+                'inverse': undefined,
+                // Fee is in %, so divide by 100
+                'taker': undefined,
```
Comment (kroitor) [inline js/woo.js:250]: Let's remove `taker` and `maker` from markets if they're not defined in this endpoint, they will be filled in later in the base code here:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L724

Comment (kroitor) [reply js/woo.js:250]: This is an exceptional case, cause otherwise the undefined values will overwrite the fees inherited from the exchange-wide .fees property.

File: js/woo.js (hunk 1 above)
Comment (ttodua) [reply js/woo.js:289]: They actually seem to have specific definitions for it. i.e. if you look their fetchMarkets response (their definition of symbols/pairs) they are even prefixed with `SPOT_BTC_USDT` and alike (They also have margin-related api responses). I think they are going to add other types too. for example, a while ago, binance also invested in them (and their marketing themselves as having 'deep pool'). So, I thought it would have been good in this case to keep them structured this way. But let me know

File: js/woo.js [hunk 3]
```diff
@@ -0,0 +1,1469 @@
...
+    async fetchOrderBook (symbol, limit = undefined, params = {}) {
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const request = {
+            'symbol': market['id'],
+        };
+        if (limit !== undefined) {
+            if (limit > 1000) {
+                throw new BadRequest (this.id + ' fetchOHLCV() limit argument cannot exceed 1000');
+            }
```
Comment (kroitor) [inline js/woo.js:833]: Let's change lines 830-833 like this:

```JavaScript
if (limit !== undefined) {
    limit = Math.min (limit, 1000);
```

File: js/woo.js [hunk 4]
```diff
@@ -0,0 +1,1469 @@
...
+    }
+
+    async fetchMarkets (params = {}) {
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('fetchMarkets', undefined, params);
+        const method = this.getSupportedMapping (marketType, {
+            'spot': 'v1PublicGetInfo',
+        });
+        let data = undefined;
+        if (marketType === 'spot') {
+            const response = await this[method] (query);
```
Comment (kroitor) [inline js/woo.js:199]: If this exchange does not have any other markets except `spot`, we should probably simplify lines 193-222:

```JavaScript
    async fetchMarkets (params = {}) {
        const response = await this.v1PublicGetInfo (params);
        //
        // ... response sample ... 
        //
        const data = this.safeValue (response, 'rows', []);
```

File: js/woo.js [hunk 5]
```diff
@@ -0,0 +1,1469 @@
...
+            data = this.safeValue (response, 'rows', []);
+        }
+        const result = [];
+        for (let i = 0; i < data.length; i++) {
+            const market = data[i];
+            const marketId = this.safeString (market, 'symbol');
+            const parts = marketId.split ('_');
+            const baseId = parts[1];
+            const quoteId = parts[2];
+            const marketTypeVal = parts[0].toLowerCase ();
```
Comment (kroitor) [inline js/woo.js:230]: Let's use safeString on all keys and indices as much as possible, except in for-loops:

```JavaScript
const marketType = this.safeStringLower (parts, 0);
```

File: js/woo.js (hunk 4 above)
Comment (kroitor) [reply js/woo.js:199]: Although, on a second thought, I will need a bit of time to confirm it.

File: js/woo.js (hunk 3 above)
Comment (ttodua) [reply js/woo.js:833]: it that change the unified approach, to silently fix (trim down or whatever) user inputed parameter? because I remind other exchagnes, where you have to input explicitly i.e. `20,50` or whatever number, and if user doesn't enter those numbers, it throws exception. (so, maybe in those cases too, CCXT should trim down to nearest number? i.e. if user inputs 39, then it should rounddown to 20, if user inputs 83, then rounddown to 50... so, no exceptions should be thrown?)

File: js/woo.js [hunk 6]
```diff
@@ -0,0 +1,1465 @@
...
+            const currencyNetworks = derivedNetworksData[code];
+            const currencyMerged = this.deepExtend (currencyInfo, currencyNetworks);
+            // if response1 each item contains only one child, then they are the same network . Quite bad behavior of their API for this matter, but as-is: the only solution is this as I think at this moment.
+            const name = this.safeString (currencyMerged, 'fullname');
+            const isActive = this.hasChildWithKeyValue (currencyNetworks, 'allow_deposit', 1) && this.hasChildWithKeyValue (currencyNetworks, 'allow_withdraw', 1);
+            result[code] = {
+                'id': code,
+                'name': name,
+                'code': code,
+                'precision': undefined, // TODO: different networks have different precision
```
Comment (kroitor) [inline js/woo.js:548]: See how that is done here:

- https://github.com/ccxt/ccxt/blob/master/js/okex.js#L940
- https://github.com/ccxt/ccxt/blob/master/js/huobi.js#L2237

File: js/woo.js [hunk 7]
```diff
@@ -0,0 +1,1465 @@
...
+    async createOrder (symbol, type, side, amount, price = undefined, params = {}) {
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const request = {
+            'symbol': market['id'],
+            'order_type': type.toUpperCase (),
+            'side': side.toUpperCase (),
+        };
+        if (price !== undefined) {
+            request['order_price'] = price; // TODO:   this.priceToPrecision (symbol, price);  --> rounds-dow 1.01 to 1.0 , for WOO_USDT
```
Comment (kroitor) [inline js/woo.js:577]: We have to use priceToPrecision with a proper precision value set on the WOO market.

File: js/woo.js [hunk 8]
```diff
@@ -0,0 +1,1465 @@
...
+        const addressTo = this.safeString (transaction, 'target_address');
+        const addressFrom = this.safeString (transaction, 'source_address');
+        const timestamp = this.safeTimestamp (transaction, 'created_time');
+        return {
+            'id': this.safeString (transaction, 'id'),
+            'txid': this.safeString (transaction, 'tx_id'),
+            'timestamp': timestamp,
+            'datetime': this.iso8601 (timestamp),
+            'address': movementDirection === 'deposit' ? addressTo : addressFrom, // TODO - should become deprecated property
+            'address_from': addressTo, // TODO - make unified property
```
Comment (kroitor) [inline js/woo.js:1186]: It is a unified property, see parseTransaction is all other exchanges.

Comment (kroitor) [reply js/woo.js:1186]: We must rename this to camelCase notation, `address_from` > `addressFrom`.

File: js/woo.js [hunk 9]
```diff
@@ -0,0 +1,1465 @@
...
+    parseTransfer (transfer, currency = undefined) {
+        // example is "fetchTransactions"
+        let movementDirection = this.safeStringLower (transfer, 'token_side');
+        if (movementDirection === 'withdraw') {
+            movementDirection = 'withdrawal';
+        }
+        let fromAccount = undefined;
+        let toAccount = undefined;
+        if (movementDirection === 'withdraw') {
+            fromAccount = 'derivative';
```
Comment (kroitor) [inline js/woo.js:1241]: We should not set it to the word `derivative`, since it's nowhere to find in any other places through this exchange and it's not unified.

File: js/woo.js [hunk 10]
```diff
@@ -0,0 +1,1465 @@
...
+                    if (networkItem['chained_currency_code'] === chainedCode) {
+                        return currencyItem;
+                    }
+                }
+            }
+        }
+        return undefined;
+    }
+
+    objectMemberAt (objOrArray, position) { // TODO: can be in base
```
Comment (kroitor) [inline js/woo.js:1420]: We don't need this in most cases.

File: js/woo.js [hunk 11]
```diff
@@ -0,0 +1,1465 @@
...
+        return objOrArray[Object.keys (objOrArray)[position]];
```
Comment (kroitor) [inline js/woo.js:1421]: Let's split all lines like this into multiple expressions, one expression per line. 

```JavaScript
const keys = Object.keys (objectOrArray);
const keyAtPosition = this.safeValue (keys, position);
return this.safeValue (objectOrArray, keyAtPosition);
```

In general, we can avoid this method entirely with the already existing basecode.

File: js/woo.js [hunk 12]
```diff
@@ -0,0 +1,1465 @@
...
+        chainsSlugs['ERC20'] = [ 'erc', 'erc20', 'erc-20', 'eth', 'eth20', 'eth-20', 'ethereum', 'ethereum-network', 'ethereum-chain' ];
+        chainsSlugs['HRC20'] = [ 'heco', 'hrc', 'hrc20', 'hrc-20', 'huobi', 'huobi-network', 'huobi-chain', 'huobi-eco-chain', 'eco-network', 'eco-chain' ];
+        chainsSlugs['TRC20'] = [ 'trc', 'trc20', 'trc-20', 'trx', 'trx20', 'trx-20', 'tron', 'tron-network', 'tron-chain', 'trx-chain', 'trx-network' ];
+        chainsSlugs['SOL'] = [ 'sol', 'solana', 'solana-network', 'solana-chain', 'sol-network', 'sol-chain' ];
+        chainsSlugs['MATIC'] = [ 'matic', 'matic-network', 'matic-chain', 'polygon', 'polygon-network', 'polygon-chain' ];
+        const keys = Object.keys (chainsSlugs);
+        for (let i = 0; i < keys.length; i++) {
+            const key = keys[i];
+            const chainList = chainsSlugs[key];
+            if (chainList.includes (type_S)) {
```
Comment (kroitor) [inline js/woo.js:1459]: We don't transpile `includes`, cause a linear search in the array is always slower than a key-lookup in a dictionary, which is why we never use loops and arrays for such things, instead we use dictionaries with safe-methods.

File: js/woo.js [hunk 13]
```diff
@@ -0,0 +1,1465 @@
...
+        str = str.replace (' ', '-');
+        str = str.replace ('.', '-');
+        str = str.replace ('_', '-');
+        return str.toLowerCase ();
+    }
+
+    detectChainSlug (type) { // TODO: this method can be moved into base
+        const type_S = this.sanitizestr (type);
+        const chainsSlugs = {};
+        chainsSlugs['BTC'] = [ 'btc', 'btc-chain', 'btc-network', 'bitcoin', 'bitcoin-chain', 'bitcoin-network' ];
```
Comment (kroitor) [inline js/woo.js:1447]: Where do all these slugs come from? If they're mentioned in the API docs (exchange-specific) – we can keep them, otherwise we have to remove them, cause they're not unified and not used by this exchange.

File: js/woo.js [hunk 14]
```diff
@@ -0,0 +1,1465 @@
...
+        // at first, try to find if user or exchange has defined default networks for the specific currency
+        const userChosenNetork = this.safeStringUpper (params, 'network');
+        params = this.omit (params, 'network');
+        const defaultNetworks = this.safeValue (this.options, 'defaultNetworks');
+        if (defaultNetworks !== undefined) {
+            const defaultNetworkCode = this.safeStringUpper (defaultNetworks, code);
+            if (defaultNetworkCode !== undefined) {
+                const networks = this.safeValue (this.options, 'networks');
+                if (networks !== undefined) {
+                    const unifiedNetworkCode = userChosenNetork !== undefined ? this.detectChainSlug (userChosenNetork) : defaultNetworkCode;
```
Comment (kroitor) [inline js/woo.js:1332]: This line is a violation of the following rule: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#using-ternary-conditionals

File: js/woo.js [hunk 15]
```diff
@@ -0,0 +1,1465 @@
...
+
+    async fetchTransfers (code = undefined, since = undefined, limit = undefined, params = {}) {
+        let currency = undefined;
+        if (code !== undefined) {
+            currency = this.currency (code);
+        }
+        const request = {
+            'type': 'COLLATERAL',
+        };
+        params = this.omit (params, 'type'); // conflict! we need to change 'type' param for spot/futures into 'exchangeType'
```
Comment (kroitor) [inline js/woo.js:1222]: There is no conflict here, cause fetchTransfers does not operate with markets, it operates with currencies which are usually working exchange-wide. Let's cut out lines 1222-1226.

File: js/woo.js [hunk 16]
```diff
@@ -0,0 +1,1465 @@
...
+        return this.parseTransactions (transactions, currency, since, limit);
+    }
+
+    parseTransaction (transaction, currency = undefined) {
+        // example in fetchTransactions
+        const networkizedCode = this.safeString (transaction, 'token');
+        if (currency === undefined) {
+            currency = this.getCurrencyByNetworkizedCode (networkizedCode);
+        }
+        const code = currency['code'];
```
Comment (kroitor) [inline js/woo.js:1168]: From the above lines 1162-1167 it follows that `currency` can be undefined here.
Let's use this syntax:

```JavaScript
const token = this.safeString (transaction, 'token');
//  split it here
const currencyId = ...
const code = this.safeCurrencyCode (currencyId);
```

File: js/woo.js [hunk 17]
```diff
@@ -0,0 +1,1465 @@
...
+        let movementDirection = this.safeStringLower (transaction, 'token_side');
+        if (movementDirection === 'withdraw') {
+            movementDirection = 'withdrawal';
+        }
+        let fee_token = this.safeString (transaction, 'fee_token', '');
```
Comment (kroitor) [inline js/woo.js:1173]: We never pass the exchange specific currency ids (`fee_token` in this case) to the user "as is". We always convert them from exchange-specific currency ids, to CCXT unified currency codes. That is done with the following methods:

```JavaScript
const feeCurrencyId = this.safeString (transaction, 'fee_token');
const feeCurrencyCode = this.safeCurrencyCode (feeCurrencyId);
```

See how that is done across the other exchanges.

File: js/woo.js [hunk 18]
```diff
@@ -0,0 +1,1465 @@
...
+            request['start_t'] = since;
+        }
+        if (limit !== undefined) {
+            request['pageSize'] = limit;
+        }
+        const transactionType = this.safeString (params, 'transaction_type');
+        if (transactionType !== undefined) {
+            request['type'] = transactionType;
+        }
+        params = this.omit (params, 'type'); // conflict! we need to change 'type' param for spot/futures into 'exchangeType'
```
Comment (kroitor) [inline js/woo.js:1118]: No conflict here, as with `fetchTansfers` – `fetchTransactions` does not deal with markets, let's cut out these lines.

File: js/woo.js [hunk 19]
```diff
@@ -0,0 +1,1465 @@
...
+                '1h': '1h',
+                '4h': '4h',
+                '12h': '12h',
+                '1d': '1d',
+                '1w': '1w',
+                '1M': '1mon',
+                '1y': '1y',
+            },
+            'urls': {
+                'logo': '  <<<TODO>>>    ',
```
Comment (kroitor) [inline js/woo.js:75]: Let's leave these strings empty, i'll add all that upon merging.

File: js/woo.js [hunk 20]
```diff
@@ -0,0 +1,1465 @@
...
+                'api': {
+                    'public': 'https://api.woo.org',
+                    'private': 'https://api.woo.org',
+                    // TODO: official api doesnt mention, but there seems to be :  API_TESTNET_URL = "http://api.staging.woo.network" as said https://github.com/wanth1997/python-wootrade/blob/main/wootrade/client.py
```
Comment (kroitor) [inline js/woo.js:79]: Let's add that under `test` – see how that is done with the other exchanges. Upon adding a testnet, let's make sure that it works – test the testnet.

File: js/woo.js [hunk 21]
```diff
@@ -0,0 +1,1465 @@
...
+        const method = this.getSupportedMapping (marketType, {
+            'spot': 'v1PrivateDeleteOrders',
+        });
+        const response = await this[method] (this.extend (request, query));
+        return response;
+    }
+
+    async fetchOrder (id, symbol = undefined, params = {}) {
+        await this.loadMarkets ();
+        const market = (symbol !== undefined) ? this.market (symbol) : undefined;
```
Comment (kroitor) [inline js/woo.js:682]: Does this endpoint require a `symbol` ?

Comment (kroitor) [reply js/woo.js:682]: Nevermind, i've misread it at first.

File: js/woo.js [hunk 22]
```diff
@@ -0,0 +1,1466 @@
...
+                    },
+                    'private': {
+                        'get': {
+                            'client/token': 1, // implicit
+                            'order/{oid}': 1, // shared with "GET: client/order/:client_order_id"
+                            'client/order/{client_order_id}': 1, // shared with "GET: order/:oid"
+                            'orders': 1,
+                            'orderbook/{symbol}': 1,
+                            'kline': 1,
+                            'client/trade/:tid': 1, // implicit
```
Comment (kroitor) [inline js/woo.js:109]: I think `:tid` here is meant to be `{tid}`.

File: js/woo.js [hunk 23]
```diff
@@ -0,0 +1,1466 @@
...
+                            'order/{oid}/trades': 1,
+                            'client/trades': 1,
+                            'client/info': 60,
+                            'asset/deposit': 120,
+                            'asset/history': 60,
+                            'token_interest': 60, // implicit
+                            'token_interest/:token': 60, // implicit
```
Comment (kroitor) [inline js/woo.js:116]: `:token` here must be `{token}`.

File: js/woo.js (hunk 8 above)
Comment (ttodua) [reply js/woo.js:1185]: Strange, the class from where I copied didn't implement those props. my mistake.
question though - what's about 'address' property - will it become deprecated?

File: js/woo.js (hunk 9 above)
Comment (ttodua) [reply js/woo.js:1240]: Should I set it to 'derivatives' (as in bitfinex) or 'futures' ?  because Woo api docs talks about collaterals and they are probably going to open the futures/derivs . however, what I should do in this case so?

Comment (kroitor) [reply js/woo.js:1240]: We are in the process of unifying it in the following way: https://github.com/ccxt/ccxt/pulls?q=fetchmarkets+unified+is%3Apr

- to `exchange.has` we add boolean flags: `spot`, `swap`, `future`, `option`
- to the market structure we add boolean flags: `spot`, `swap`, `future`, `option` and we also add `type` string (equal to either of `'spot'`, `'swap'`, `'future'`, `'option'`) and a `contract` boolean flag that is set to `swap || future || option`.

File: js/woo.js (hunk 13 above)
Comment (ttodua) [reply js/woo.js:1446]: Actually, that is a part of 'in-house' unified base method which I've mentioned. the specific exchange (lets say Woo in this case) have only one or two matching title from that list of slug, however, these slugs were picked and joined from different exchanges, and that's why I've marked it with "..maybe move this method in base..", where we can have a better method body, like:
```
detectChainSlug (slug) {
 chainsSlugs['BTC'] = [
    'btc', // binance, gateio, bitfinex
    'btc-chain', // kraken, xyz
    'bitcoin-chain', //phemex, 
 ....
```
etc, and so, in implementations of exchange classes, we can have just `this.detectChainSlug()` applied to any network related slug and it will be automatically covnerted into unified network-slug (i.e. BTC, ERC20 or whatever will be chosen by CCXT unified networkid for specific chain).

The second way is that we created individual parsing functions inside derived exchange classes, but it will be far from unified convenience i think.

Comment (kroitor) [reply js/woo.js:1446]: First, I totally agree about unification.

However, before unifying chain slugs, we need to define exactly what a chain slug is and why we need it. The users are supposed to supply unified networks to methods like fetchDepositAddress, withdraw, etc. We should also return unified networks in the related structures. How is chain slug applied to that? I think we should take the info from the preloaded currencies into the account.

Before we can actually unify it – we need to spend more time on the design of this unification. And since it involves a lot of exchanges – we should probably do that in a standalone PR. This exchange integration, however, should not depend on that, we can't really freeze it for a few weeks till we get to unifying networks everywhere. We have to make this code clean and mergeable without external dependencies first.

**Comment by ttodua** [comment]
@kroitor I've addressed all notes, reworked some functions/network things. The only thing remains in this PR is Testnet addition.

File: js/woo.js (hunk 13 above)
Comment (ttodua) [reply js/woo.js]: I understand, you're right. I've tried now to make this individual exchange to be a self-isolated. About the slugs, let's talk about it in discord thread.

**Comment by ttodua** [comment]
@kroitor lmk notes.

File: js/woo.js [hunk 24]
```diff
@@ -0,0 +1,1532 @@
...
+                'precision': {
+                    'amount': quantityScale,
+                    'price': priceScale,
+                },
+                'limits': {
+                    'leverage': {
+                        'min': undefined,
+                        'max': undefined,
+                    },
+                    // I am dubious that something is not correct in my below prop-value assignments
```
Comment (kroitor) [inline js/woo.js:289]: I think it's ok, we can clean out this comment.

File: js/woo.js (hunk 20 above)
Comment (kroitor) [reply js/woo.js:79]: Let's add these test urls, or lmk if I am missing something.

File: js/woo.js [hunk 25]
```diff
@@ -0,0 +1,1532 @@
...
+        //     is_maker: '1'
+        // }
+        //
+        const isFromFetchOrder = ('id' in trade);
+        const timestamp = this.safeTimestamp (trade, 'executed_timestamp');
+        const marketId = this.safeString (trade, 'symbol');
+        if (market === undefined) {
+            market = this.safeMarket (marketId, market, '_');
+        }
+        const symbol = market['symbol'];
```
Comment (kroitor) [inline js/woo.js:392]: Let's replace the above three lines 389-391 with a one-liner:
```JavaScript
        if (market === undefined) {
            market = this.safeMarket (marketId, market, '_');
        }
```
↓
```JavaScript
        market = this.safeMarket (marketId, market, '_');
```

Comment (kroitor) [reply js/woo.js:392]: Also, a delimiter will not take the effect here, cause it will only be recognized for 2-word symbols with one delimiter in them. In this case it's 3 words with 2 delimiters.

File: js/woo.js [hunk 26]
```diff
@@ -0,0 +1,1532 @@
...
+            const code = this.safeCurrencyCode (tokenCode);
+            if (!(code in derivedCurrenciesData)) {
+                derivedCurrenciesData[code] = {
+                    'fullname': this.safeString (item, 'fullname'),
+                    'networks': {},
+                };
+            }
+            const chainedTokenCode = this.safeString (item, 'token');
+            const parts = chainedTokenCode.split ('_');
+            const networkId = parts.length === 2 ? this.safeString (parts, 0) : chainedTokenCode;
```
Comment (kroitor) [inline js/woo.js:489]: This is a violation of two CONTRIBUTING guidelines:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#working-with-array-lengths
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#using-ternary-conditionals

File: js/woo.js [hunk 27]
```diff
@@ -0,0 +1,1532 @@
...
+            }
+            const protocol = this.safeString (item, 'protocol', '');
+            const networkUnifiedSlug = this.safeString (this.options['network-aliases'], protocol, protocol);
+            derivedNetworksData[code]['networks'][networkUnifiedSlug] = {
+                'network_title': this.safeString (item, 'name'),
+                'allow_deposit': this.safeString (item, 'allow_deposit'),
+                'allow_withdraw': this.safeString (item, 'allow_withdraw'),
+                'withdrawal_fee': this.safeString (item, 'withdrawal_fee'),
+                'minimum_withdrawal': this.safeString (item, 'minimum_withdrawal'),
+                'info': { 'networkInfo': item },
```
Comment (kroitor) [inline js/woo.js:547]: I think this code is somewhat an overkill for the purpose. We can do this in an algorithmically-cleaner way.
My logic goes like this:

```JavaScript
        const tokenResponse = await this.v1PublicGetToken (query);
        //  
        //     {
        //         rows: [
        //             {
        //                 token: "ETH_USDT",
        //                 fullname: "Tether",
        //                 decimals: 6,
        //                 balance_token: "USDT",
        //                 created_time: "0",
        //                 updated_time: "0"
        //             },
        //         ],
        //         success: true
        //     }
        //            
        const tokenNetworkResponse = await this.v1PublicGetTokenNetwork (query);
        //
        //     {
        //         rows: [
        //             {
        //                 protocol: "ERC20",
        //                 token: "USDT",
        //                 name: "Ethereum",
        //                 minimum_withdrawal: 30,
        //                 withdrawal_fee: 25,
        //                 allow_deposit: 1,
        //                 allow_withdraw: 1
        //             },
        //             {
        //                 protocol: "TRC20",
        //                 token: "USDT",
        //                 name: "Tron",
        //                 minimum_withdrawal: 30,
        //                 withdrawal_fee: 1,
        //                 allow_deposit: 1,
        //                 allow_withdraw: 1
        //             },
        //             ...
        //         ],
        //         success: true
        //     }
        //
        const result = {};
        const tokenRows = this.safeValue (tokenResponse, 'rows', []);
        const tokenNetworkRows = this.safeValue (tokenNetworkResponse, 'rows', []);
        const networksByCurrencyId = this.groupBy (tokenNetworkRows, 'token');
        for (let i = 0; i < tokenRows.length; i++) {
            //
            //     ** please copy this code from huobi.js as much as possible **
            //     ** i'm not including all the details in this example for simplicity **
            //
            const currency = tokenRows[i];
            const id = this.safeString (currency, 'balance_token');
            const code = this.safeCurrencyCode (id);
            const networks = this.safeValue (networksByCurrencyId, id, []);
            const resultingNetworks = {};
            for (let j = 0; j < networks.length; j++) {
                const networkEntry = networks[i];
                const networkId = this.safeString (networkEntry, 'protocol');
                const network = this.safeNetwork (networkId);
                resultingNetworks[network] = {
                    'info': chain,
                    'id': networkId,
                    'network': network,
                    'limits': {
                        'withdraw': {
                            'min': minWithdraw,
                            'max': maxWithdraw,
                        },
                    },
                    'active': active,
                    'deposit': depositEnabled,
                    'withdraw': withdrawEnabled,
                    'fee': fee,
                    'precision': precision,
                };
            }
            result[code] = {
                // currency structure
                // ...
                'networks': resultingNetworks,
                // ...
            };
        }
```

File: js/woo.js (hunk 3 above)
Comment (kroitor) [reply js/woo.js]: > maybe in those cases too, CCXT should trim down to nearest number?

I would not truncate the limit in those cases at this point, we can add that later if necessary.

File: js/woo.js [hunk 28]
```diff
@@ -0,0 +1,1586 @@
...
+        const price = this.safeString (trade, 'executed_price');
+        const amount = this.safeString (trade, 'executed_quantity');
+        const order_id = this.safeString (trade, 'order_id');
+        const feeValue = this.safeString (trade, 'fee');
+        const feeAsset = this.safeString (trade, 'fee_asset');
+        const cost = Precise.stringMul (price, amount);
+        let side = this.safeString (trade, 'side');
+        if (side !== undefined) {
+            side = side.toLowerCase ();
+        }
```
Comment (kroitor) [inline js/woo.js:406]: We can replace the above 3 lines with a one-liner `const side = this.safeStringLower (trade, 'side');`

File: js/woo.js [hunk 29]
```diff
@@ -0,0 +1,1586 @@
...
+            const code = this.safeCurrencyCode (tokenCode);
+            if (!(code in derivedCurrenciesData)) {
+                derivedCurrenciesData[code] = {
+                    'fullname': this.safeString (item, 'fullname'),
+                    'networks': {},
+                };
+            }
+            const chainedTokenCode = this.safeString (item, 'token');
+            const parts = chainedTokenCode.split ('_');
+            const networkId = (parts.length === 2) ? this.safeString (parts, 0) : chainedTokenCode;
```
Comment (kroitor) [inline js/woo.js:493]: We can't do parts.length, it won't work with arrays, just strings, so we have to do this to hint the transpiler:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#working-with-array-lengths

File: js/woo.js [hunk 30]
```diff
@@ -0,0 +1,1586 @@
...
+        // {
+        //     success: true,
+        //     address: '3Jmtjx5544T4smrit9Eroe4PCrRkpDeKjP',
+        //     extra: ''
+        // }
+        let tag = this.safeValue (response, 'extra');
+        if (tag === '') {
+            tag = undefined;
+        }
+        const address = this.safeValue (response, 'address');
```
Comment (kroitor) [inline js/woo.js:1170]: Let's use safeString here.

File: js/woo.js [hunk 31]
```diff
@@ -0,0 +1,1586 @@
...
+        const method = this.getSupportedMapping (marketType, {
+            'spot': 'v1PrivateGetAssetDeposit',
+        });
+        const response = await this[method] (this.extend (request, query));
+        // {
+        //     success: true,
+        //     address: '3Jmtjx5544T4smrit9Eroe4PCrRkpDeKjP',
+        //     extra: ''
+        // }
+        let tag = this.safeValue (response, 'extra');
```
Comment (kroitor) [inline js/woo.js:1166]: Let's use safeString here.

File: js/woo.js [hunk 32]
```diff
@@ -0,0 +1,1586 @@
...
+            'info': response,
+        };
+        const balances = this.safeValue (response, 'holding', []);
+        for (let i = 0; i < balances.length; i++) {
+            const balance = balances[i];
+            const code = this.safeCurrencyCode (this.safeString (balance, 'token'));
+            const account = this.account ();
+            account['total'] = this.safeString (balance, 'holding');
+            account['used'] = this.safeString (balance, 'outstanding_holding');
+            account['free'] = Precise.stringAdd (account['total'], account['used']);
```
Comment (kroitor) [inline js/woo.js:1141]: This line is not necessary – done in safeBalance.

File: js/woo.js [hunk 33]
```diff
@@ -0,0 +1,1586 @@
...
+        const orderId = this.safeInteger (order, 'order_id');
+        const clientOrderId = this.safeTimestamp (order, 'client_order_id'); // Somehow, this always returns 0 for limit order
+        if (market === undefined) {
+            const marketId = this.safeString (order, 'symbol');
+            market = this.safeMarket (marketId, market);
+        }
+        const symbol = market['symbol'];
+        const price = this.safeString2 (order, 'order_price', 'price');
+        const quantity = this.safeString2 (order, 'order_quantity', 'quantity'); // This is base amount
+        const amount = this.safeString2 (order, 'order_amount', 'amount'); // This is quote amount
```
Comment (kroitor) [inline js/woo.js:872]: Let's call this variable `cost` for less confusion.

File: js/woo.js [hunk 34]
```diff
@@ -0,0 +1,1586 @@
...
+        const timestamp = this.safeTimestamp2 (order, 'timestamp', 'created_time');
+        const orderId = this.safeInteger (order, 'order_id');
+        const clientOrderId = this.safeTimestamp (order, 'client_order_id'); // Somehow, this always returns 0 for limit order
+        if (market === undefined) {
+            const marketId = this.safeString (order, 'symbol');
+            market = this.safeMarket (marketId, market);
+        }
+        const symbol = market['symbol'];
+        const price = this.safeString2 (order, 'order_price', 'price');
+        const quantity = this.safeString2 (order, 'order_quantity', 'quantity'); // This is base amount
```
Comment (kroitor) [inline js/woo.js:871]: Let's call this variable `amount` for less confusion.

File: js/woo.js [hunk 35]
```diff
@@ -0,0 +1,1586 @@
...
+        // * fetchOrder
+        // * fetchOrders
+        // const isFromFetchOrder = ('order_tag' in order); TO_DO
+        const timestamp = this.safeTimestamp2 (order, 'timestamp', 'created_time');
+        const orderId = this.safeInteger (order, 'order_id');
+        const clientOrderId = this.safeTimestamp (order, 'client_order_id'); // Somehow, this always returns 0 for limit order
+        if (market === undefined) {
+            const marketId = this.safeString (order, 'symbol');
+            market = this.safeMarket (marketId, market);
+        }
```
Comment (kroitor) [inline js/woo.js:868]: The `if (market === undefined)` conditional is not necessary here – it is done in safeMarket. Let's replace the four lines 865-868 with just these two lines:

```JavaScript
            const marketId = this.safeString (order, 'symbol');
            market = this.safeMarket (marketId, market);
```

File: js/woo.js [hunk 36]
```diff
@@ -0,0 +1,1654 @@
...
+        if (currency === undefined) {
+            currency = this.getCurrencyByNetworkizedCode (networkizedCode);
+        }
+        let code = undefined;
+        if (currency !== undefined) {
+            code = currency['code'];
+        } else {
+            const parts = networkizedCode.split ('_');
+            let currencyId = undefined;
+            if (parts.length > 1) {
```
Comment (kroitor) [inline js/woo.js:1335]: We still can't use `parts.length` here cause `.length` is for strings-only. We have to hint the transpiler as documented here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#working-with-array-lengths

```JavaScipt
const parts = networkizedCode.split ('_');
let currencyId = undefined;
const partsLength = parts.length;
if (partsLength > 1) {
    currencyId = parts[1];
} else {
    currencyId = parts[0];
}
```
↓
```JavaScipt
const parts = networkizedCode.split ('_');
const partsLength = parts.length;
const currencyId = (partsLength > 1) ? parts[1] : parts[0];
```
↓
```JavaScript
const parts = networkizedCode.split ('_');
const firstPart = this.safeString (parts, 0);
const currencyId = this.safeString (parts, 1, firstPart);
```

Comment (ttodua) [reply js/woo.js:1253]: I've not thought about that approach, thanks !

can we add that to linter, so `.length` keywords not ending with `;` showed problem. I think it's not uncommon issue, and moreover forced you to include it in docs.  (possible variation could have been to create an unified function named 'this.arrayLength` and `this.stringLength` , and enforced instead of using `.length` params.  so, less documentation will be needed and less errors. not?

File: js/woo.js (hunk 34 above)
Comment (ttodua) [reply js/woo.js:852]: on the next line was the 'amount' variable, this one was specifically quantity (as they call it).

**Comment by ttodua** [comment]
@kroitor I think I've done all. Had spent most of the time for recoding the currencies (as it affected other unified methods in class, and eventually I think I've reached a well-structured methods which can be implemented in base too). lmk

File: js/woo.js (hunk 36 above)
Comment (kroitor) [reply js/woo.js]: @ttodua I will look into the linter rules for `.length`.

File: js/woo.js [hunk 37]
```diff
@@ -0,0 +1,1453 @@
...
+        const result = {
+            'info': response,
+        };
+        const balances = this.safeValue (response, 'holding', []);
+        for (let i = 0; i < balances.length; i++) {
+            const balance = balances[i];
+            const code = this.safeCurrencyCode (this.safeString (balance, 'token'));
+            const account = this.account ();
+            account['total'] = this.safeString (balance, 'holding');
+            account['used'] = this.safeString (balance, 'outstanding_holding');
```
Comment (kroitor) [inline js/woo.js:1084]: I think `used` should be a `this.sum` in this case:

```JavaSciprt
const outstandingHolding = this.safeString (balance, 'outstanding_holding');
const frozen = this.safeString (balance, 'frozen');
const used = Precise.stringAdd (frozen, Precise.stringNeg (outstandingHolding));
```

In general, `total = used + free` should hold – let's ensure that.

Comment (ttodua) [reply js/woo.js:1087]: yes, that's done

File: js/woo.js [hunk 38]
```diff
@@ -0,0 +1,1456 @@
...
+            params = this.omit (params, 'network');
+        }
+        await this.loadMarkets ();
+        const currency = this.currency (code);
+        const currencyId = currency['id'];
+        const request = {
+            'amount': amount,
+        };
+        const method = 'v1PrivatePostAssetWithdraw';
+        request['token'] = this.currencyCodeWithNetwork (currencyId, networkCode);
```
Comment (kroitor) [inline js/woo.js:1335]: There's no `this.currencyCodeWithNetwork` anymore.

**Comment by ttodua** [comment]
@kroitor any idea why travis fails?

**Comment by ttodua** [comment]
damn, incorrect commit.  will revert shortly.

**Comment by ttodua** [comment]
@kroitor now seems ready, lmk.
