### PR TITLE
base - undefined string in findBroadlyMatchedKey exception

### LINKED ISSUE #12698: ccxt/base/exchange.py find_broadly_matched_key not catching some exceptions, fix in body
You should add "string = str(string)" to the top of find_broadly_matched_key(self, string, key) in the title file, otherwise an unknown exchange error throwing an exception will crash with "NoneType has no attribute 'find' ". Code is on another computer, sorry for the lack of replicability.

### PR DESCRIPTION
**Pull request by ttodua**
fix #12698
this PR depends on another PR: https://github.com/ccxt/ccxt/pull/14808

### CODE REVIEW

File: js/base/Exchange.js [hunk 1]
```diff
@@ -2087,8 +2087,10 @@ module.exports = class Exchange {
         const keys = Object.keys (broad);
         for (let i = 0; i < keys.length; i++) {
             const key = keys[i];
-            if (string.indexOf (key) >= 0) {
-                return key;
+            if (string !== undefined && string !== null) { // #issues/12698
```
Comment (frosty00) [inline js/base/Exchange.js:2090]: !== null is not transpilable

Comment (ttodua) [reply js/base/Exchange.js]: fixed it

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]
