### PR TITLE
fix(binance) - editOrder for spot

### LINKED ISSUE #18667: [binance] editOrder recieved error "Mandatory parameter 'type' was not sent"
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.0.38

### Description

when call editOrder with params (id, symbol, type, side, amount, price), I got the response error blow this.

```
BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'type' was not sent, was empty/null, or malformed."}
```

the verbose detail:

```
 {"symbol":"USDCUSDT","origClientOrderId":"xxx","orderId":xxx,"orderListId":-1,"clientOrderId":"xxx","transactTime":1690380923704,"price":"1.00010000","origQty":"499.00000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"CANCELED","timeInForce":"GTC","type":"LIMIT","side":"BUY","selfTradePreventionMode":"NONE"}
```

### PR DESCRIPTION
**Pull request by ttodua**
currently this does not work:
```
const o1 = await e.createOrder('ADA/USDT', 'limit', 'buy', 50, 0.2);
const o2 = await e.editOrder(o1.id, 'ADA/USDT', 'limit', 'buy', 50, 0.21);
```
PR seems to fix it, but @pcriadoperez I see that you were working on WS orders & related things in last month, so you could know this better - can you confirm whether this PR would fix it correctly?

(fixes #18667)

### CODE REVIEW

File: ts/src/binance.ts [hunk 1]
```diff
@@ -3677,15 +3677,16 @@ export default class binance extends Exchange {
...
-            'side': side.toUpperCase (),
-        };
         const clientOrderId = this.safeStringN (params, [ 'newClientOrderId', 'clientOrderId', 'origClientOrderId' ]);
         let response = undefined;
         if (market['spot']) {
-            response = await this.privatePostOrderCancelReplace (this.extend (request, params));
+            const payload = this.editSpotOrderRequest (id, symbol, type, side, amount, price, params);
+            response = await this.privatePostOrderCancelReplace (payload);
         } else {
+            const request = {
```
Comment (carlosmiei) [inline ts/src/binance.ts:3686]: @ttodua something is wrong here, we're inside `editSpotOrder` but we have an else branch that handles swap orders?

Comment (ttodua) [reply ts/src/binance.ts]: yeah, i haven't looked around, i was looking just spot order request corrections... something was off yeh. 
also, maybe we neither need `if (!market['spot'])` check inside `editSpotOrder`.

Comment (carlosmiei) [reply ts/src/binance.ts]: @ttodua yeah I removed all of that

Comment (ttodua) [reply ts/src/binance.ts]: it might need later to be checked inside `editSwapOrder` or alike, i've not looked in other areas yet.

**Comment by carlosmiei** [comment]
DEMO

```
p binance createOrder "BTC/USDT" limit buy 0.001 20000 --sandbox
Python v3.10.9
CCXT v4.0.37
binance.createOrder(BTC/USDT,limit,buy,0.001,20000)
{'amount': 0.001,
 'average': None,
 'clientOrderId': 'x-R4BD3S82cdedc7f8966c7dc0f41cdc',
 'cost': 0.0,
 'datetime': '2023-07-27T10:46:27.481Z',
 'fee': {'cost': None, 'currency': None, 'rate': None},
 'fees': [{'cost': None, 'currency': None, 'rate': None}],
 'filled': 0.0,
 'id': '10010788',
 'info': {'clientOrderId': 'x-R4BD3S82cdedc7f8966c7dc0f41cdc',
          'cummulativeQuoteQty': '0.00000000',
          'executedQty': '0.00000000',
          'fills': [],
          'orderId': '10010788',
          'orderListId': '-1',
          'origQty': '0.00100000',
          'price': '20000.00000000',
          'selfTradePreventionMode': 'NONE',
          'side': 'BUY',
          'status': 'NEW',
          'symbol': 'BTCUSDT',
          'timeInForce': 'GTC',
          'transactTime': '1690454787481',
          'type': 'LIMIT',
          'workingTime': '1690454787481'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': 1690454787481,
 'postOnly': False,
 'price': 20000.0,
 'reduceOnly': None,
 'remaining': 0.001,
 'side': 'buy',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'BTC/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': 1690454787481,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
```
```
p binance editOrder "10010788" "BTC/USDT" limit buy 0.002 25000 --sandbox
Python v3.10.9
CCXT v4.0.37
binance.editOrder(10010788,BTC/USDT,limit,buy,0.002,25000)
{'amount': 0.002,
 'average': None,
 'clientOrderId': 'x-R4BD3S82d59a66489401748191cf4c',
 'cost': 0.0,
 'datetime': '2023-07-27T10:47:12.481Z',
 'fee': {'cost': None, 'currency': None, 'rate': None},
 'fees': [{'cost': None, 'currency': None, 'rate': None}],
 'filled': 0.0,
 'id': '10011014',
 'info': {'clientOrderId': 'x-R4BD3S82d59a66489401748191cf4c',
          'cummulativeQuoteQty': '0.00000000',
          'executedQty': '0.00000000',
          'fills': [],
          'orderId': '10011014',
          'orderListId': '-1',
          'origQty': '0.00200000',
          'price': '25000.00000000',
          'selfTradePreventionMode': 'NONE',
          'side': 'BUY',
          'status': 'NEW',
          'symbol': 'BTCUSDT',
          'timeInForce': 'GTC',
          'transactTime': '1690454832481',
          'type': 'LIMIT',
          'workingTime': '1690454832481'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': 1690454832481,
 'postOnly': False,
 'price': 25000.0,
 'reduceOnly': None,
 'remaining': 0.002,
 'side': 'buy',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'BTC/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': 1690454832481,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
```

**Review by carlosmiei — APPROVED** [review]
