### PR TITLE
yobit - fetchtickers

### LINKED ISSUE #17661: fetch_tickers() yobit error
### Operating System

WIndows

### Programming Languages

_No response_

### CCXT Version

3.0.74

### Description

Hi.
I can't get the full list of currencies with prices that the function "fetch_tickers()" returns.
Each exchange gives out different results, for example:

```
$data=mysqli_source($con,"select * from `stocks` where `name`='{$stock}'");
$exchange = '\\ccxt\\'.$stock;

if ($data['apikey']='') $exchange = new $exchange (); 
else $exchange = new $exchange (array('apiKey' => $data['apikey'],'secret' => $data['secret'],));

echo 'load_markets: '.count($exchange->load_markets()).'<br>';
echo 'fetch_tickers: '.count($exchange->fetch_tickers()).'<br>';
echo 'fetch_tickers*: '.count($exchange->fetch_tickers(array_keys($exchange->load_markets()))).'<br>';
```

**Bybit** 
load_markets: 620
fetch_tickers: 217
fetch_tickers*: 250

**Binance**
load_markets: 2471
fetch_tickers: 2190
fetch_tickers*: 2185

**Gateio**
load_markets: 3775
fetch_tickers: 3049
fetch_tickers*: 3049

**Huobi**
load_markets: 1641
fetch_tickers: 802
fetch_tickers*: 785

**Yobit**
load_markets: 8950

**Fatal error**: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in X:\domains\ccxt0\php\yobit.php:546 Stack trace: #0 X:\domains\ccxt0\php\yobit.php(546): implode() #1 X:\domains\ccxt\index.php(443): ccxt\yobit->fetch_tickers() #2 {main} thrown in X:\domains\ccxt0\php\yobit.php on line 546

fetch_tickers*: 0

As you can see on the "Yobit" exchange, an error occurs on the fetch_tickers() function.
Tell me how to correctly check prices in all currencies, and what to do with error on the stock Yobit.

thank you for your help

### Code

```
  

```

### PR DESCRIPTION
**Pull request by ttodua**
fix #17661

### CODE REVIEW

File: ts/src/yobit.ts [hunk 1]
```diff
@@ -558,19 +557,21 @@ export default class yobit extends Exchange {
...
-            const maxLength = this.safeInteger (this.options, 'fetchTickersMaxLength', 2048);
-            // max URL length is 2048 symbols, including http schema, hostname, tld, etc...
-            if (ids.length > this.options['fetchTickersMaxLength']) {
-                throw new ArgumentsRequired (this.id + ' fetchTickers() has ' + numIds.toString () + ' markets exceeding max URL length for this endpoint (' + maxLength.toString () + ' characters), please, specify a list of symbols of interest in the first argument to fetchTickers');
-            }
+            ids = this.ids;
         } else {
-            const newIds = this.marketIds (symbols);
-            ids = newIds.join ('-');
+            ids = this.marketIds (symbols);
```
Comment (carlosmiei) [inline ts/src/yobit.ts:562]: @ttodua we have an issue here
image

Comment (ttodua) [reply ts/src/yobit.ts:562]: yes, I was in the thoughts what would be the fix for it.
Initially I thought that we could make 2-3 parallel request with promise.all, but it turns out that yobit would need 20 requests to cover all tickers. so, we shouldnt do that much in promise.all.
then, the only thing we can make it now, is to skip it in tests (or just set limited symbols amount)

Comment (ttodua) [reply ts/src/yobit.ts:562]: ah wait, for 7 markets it shouldn't fail. let me check php specifically, maybe transpiling issue.

File: ts/src/yobit.ts [hunk 2]
```diff
@@ -562,12 +561,14 @@ export default class yobit extends Exchange {
...
         const idsString = ids.join ('-');
-        const maxLength = this.safeInteger (this.options, 'fetchTickersMaxLength', 2048);
+        const maxLength = this.safeInteger (this.options, 'maxUrlLength', 2048);
         // max URL length is 2048 symbols, including http schema, hostname, tld, etc...
         const lenghtOfBaseUrl = 30; // the url including api-base and endpoint dir is 30 chars
-        if (idsString.length + lenghtOfBaseUrl > maxLength) {
-            throw new ArgumentsRequired (this.id + ' fetchTickers() is being requested for ' + (idsString.length).toString () + ' markets, but it exceedes max URL length (' + maxLength.toString () + ' characters), please pass limisted symbols array to fetchTickers to fit in one request');
+        const actualLength = idsString.length + lenghtOfBaseUrl;
+        if (actualLength > maxLength) {
+            throw new ArgumentsRequired (this.id + ' fetchTickers() is being requested for ' + idsLength + ' markets (which has an URL length of ' + actualLength.toString () + ' characters), but it exceedes max URL length (' + maxLength.toString () + '), please pass limisted symbols array to fetchTickers to fit in one request');
```
Comment (carlosmiei) [inline ts/src/yobit.ts:571]: @ttodua First I think fetchTickers should work by default (even if we have to limit the number if markets sent) second, I don't believe this is a reasonable error message because it is excessively long and hard to read
image

image

Comment (ttodua) [reply ts/src/yobit.ts:571]: in second I agree, in first I might not :) because it would be direct misbehavior and issue of our code to randomly choose which symbols to fetch, as it will mislead/misguide users. not?

Comment (carlosmiei) [reply ts/src/yobit.ts:571]: @ttodua in that case, we can just make symbols mandatory to avoid this issue

Comment (ttodua) [reply ts/src/yobit.ts:571]: we just throw exception and letting users know to select their preferred symbols, so everyone will be on clear side. why should we arise extra confusions? let's user decide. 

but as you'll say.

Comment (carlosmiei) [reply ts/src/yobit.ts:571]: @ttodua in my opinion just does not make sense to have a method that does not work by default if in the end they have to select a number of symbols let be explicit about it then

Comment (ttodua) [reply ts/src/yobit.ts:571]: yeah, making symbols as mandatory sounds better

Comment (ttodua) [reply ts/src/yobit.ts:574]: pushed a commit, does that seem ok?

Comment (ttodua) [reply ts/src/yobit.ts:574]: ahh, I realized what you wrote now, in exception I accidentally included the full url. pushed an edit. now everything should be as you said.

**Comment by carlosmiei** [comment]
LGTM  ✅ 

```
n yobit fetchTickers '["BTC/USDT"]'
Debugger attached.
2023-05-27T13:13:43.776Z
Node.js: v18.14.0
CCXT v3.1.9
yobit.fetchTickers (BTC/USDT)
2023-05-27T13:13:46.362Z iteration 0 passed in 2066 ms

{
  'BTC/USDT': {
    symbol: 'BTC/USDT',
    timestamp: 1685192984000,
    datetime: '2023-05-27T13:09:44.000Z',
    high: 26773.23118369,
    low: 26250,
    bid: 26408.40266944,
    bidVolume: undefined,
    ask: 26650,
    askVolume: undefined,
    vwap: 26261.171085928294,
    open: undefined,
    close: 26408.40266944,
    last: 26408.40266944,
    previousClose: undefined,
    change: undefined,
    percentage: undefined,
    average: 26511.61559184,
    baseVolume: 0.39976286,
    quoteVolume: 10498.24086026,
    info: {
      high: '26773.23118369',
      low: '26250',
      avg: '26511.61559184',
      vol: '10498.24086026',
      vol_cur: '0.39976286',
      last: '26408.40266944',
      buy: '26408.40266944',
      sell: '26650.00000000',
      updated: '1685192984'
    }
  }
}
2023-05-27T13:13:46.362Z iteration 1 passed in 2066 ms

Waiting for the debugger to disconnect...
```

**Review by carlosmiei — APPROVED** [review]
