### PR TITLE
client & protect sendAsync

### LINKED ISSUE #21920: Error during starting WatchOrderBook c#
### Operating System

Windows 10

### Programming Languages

_No response_

### CCXT Version

4.2.80

### Description

Error while starting WatchOrderBook for a list of symbols.
Happens more often while library is used in .net framework4.8 environment compared to .net6.

### Code

```
using ccxt;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace DemoLib
{
    public class DemoNew3
    {
        private ccxt.pro.binance _exchange;
        private CancellationTokenSource _cts;
        private ConcurrentDictionary<string, Task> _tasks;

        public DemoNew3()
        {
            _tasks = new ConcurrentDictionary<string, Task>();
        }

        public void Run()
        {
            Task.Run(async () =>
            {
                while (true)
                {
                    Start();

                    await Task.Delay(10000);

                    Stop();

                    await Task.Delay(1000);
                }
            });
        }

        private void Start()
        {
            Console.WriteLine("Starting");

            _exchange = new ccxt.pro.binance();
            _cts = new CancellationTokenSource();
            _tasks.Clear();

            Console.WriteLine("LoadMarkets");

            Task.Run(async () => await _exchange.LoadMarkets()).Wait();

            Console.WriteLine($"Loaded {_exchange.symbols.Count} symbols");

            List<string> symbols = new List<string>();
            int countLimit = 10;

            // select futures/swap
            if (_exchange.markets is Dictionary<string, object> markets)
                foreach (var kvp in markets)
                {
                    if (symbols.Count == countLimit)
                        continue;

                    var props = (Dictionary<string, object>)kvp.Value;

                    if (props.TryGetValue("type", out var type) && type is string _type)
                        if (_type == "swap" || _type == "future")
                            symbols.Add(kvp.Key);
                }

            Console.WriteLine($"Selected {symbols.Count} symbols");

            int batchSize = 100;
            int counter = 0;
            foreach (var symbol in symbols)
            {
                SubscribeOrderBook(symbol);

                if (++counter % batchSize == 0)
                    Thread.Sleep(1);
            }

            Console.WriteLine("Started");
        }

        private void Stop()
        {
            Console.WriteLine("Stopping");

            _cts.Cancel();
            
            //Task.WaitAll(_tasks.Values.ToArray());

            Console.WriteLine("Stopped");
        }

        private void SubscribeOrderBook(string symbol)
        {
            Console.WriteLine($"SubscribeOrderBook for {symbol}");

            var task = Task.Run(async () =>
            {
                while (!_cts.Token.IsCancellationRequested)
                {
                    try
                    {
                        var response = await _exchange.WatchOrderBook(symbol, limit2: 5);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        break;
                    }
                }

                _tasks.TryRemove(symbol, out _);

                Console.WriteLine($"SubscribeOrderBook cancelled for {symbol}, remain tasks: {_tasks.Count}");
            });

            _tasks.TryAdd(symbol, task);
        }
    }
}


```

log for .net6 environment:
```
waiting
Starting
LoadMarkets
Loaded 2900 symbols
Selected 10 symbols
SubscribeOrderBook for BTC/USDT:USDT
SubscribeOrderBook for ETH/USDT:USDT
SubscribeOrderBook for BCH/USDT:USDT
SubscribeOrderBook for XRP/USDT:USDT
SubscribeOrderBook for EOS/USDT:USDT
SubscribeOrderBook for LTC/USDT:USDT
SubscribeOrderBook for TRX/USDT:USDT
SubscribeOrderBook for ETC/USDT:USDT
SubscribeOrderBook for LINK/USDT:USDT
SubscribeOrderBook for XLM/USDT:USDT
Started
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
System.InvalidOperationException: The WebSocket has already been started.
   at System.Net.WebSockets.ClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at ccxt.Exchange.WebSocketClient.<>c__DisplayClass31_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.Exchange.watchMultiple(Object url2, Object messageHashes2, Object message, Object subscribeHashes2, Object subscription)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBookForSymbols(Object symbols, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.watchOrderBook(Object symbol, Object limit, Object parameters)
   at ccxt.pro.binance.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters)
   at DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() in D:\Dev\Z\CCXT\Demo\DemoLib\DemoNew3.cs:line 106
SubscribeOrderBook cancelled for XLM/USDT:USDT, remain tasks: 9
SubscribeOrderBook cancelled for TRX/USDT:USDT, remain tasks: 8
SubscribeOrderBook cancelled for BTC/USDT:USDT, remain tasks: 7
SubscribeOrderBook cancelled for XRP/USDT:USDT, remain tasks: 6
SubscribeOrderBook cancelled for ETH/USDT:USDT, remain tasks: 5
SubscribeOrderBook cancelled for LTC/USDT:USDT, remain tasks: 4
SubscribeOrderBook cancelled for EOS/USDT:USDT, remain tasks: 3
SubscribeOrderBook cancelled for LINK/USDT:USDT, remain tasks: 2
SubscribeOrderBook cancelled for BCH/USDT:USDT, remain tasks: 1
Stopping
Stopped
SubscribeOrderBook cancelled for ETC/USDT:USDT, remain tasks: 0
Starting
LoadMarkets

```

log for .netframework4.8 environment (from attached solution):
```
waiting
Starting
LoadMarkets
Loaded 2900 symbols
Selected 100 symbols
SubscribeOrderBook for BTC/USDT:USDT
SubscribeOrderBook for ETH/USDT:USDT
SubscribeOrderBook for BCH/USDT:USDT
SubscribeOrderBook for XRP/USDT:USDT
SubscribeOrderBook for EOS/USDT:USDT
SubscribeOrderBook for LTC/USDT:USDT
SubscribeOrderBook for TRX/USDT:USDT
SubscribeOrderBook for ETC/USDT:USDT
SubscribeOrderBook for LINK/USDT:USDT
SubscribeOrderBook for XLM/USDT:USDT
SubscribeOrderBook for ADA/USDT:USDT
SubscribeOrderBook for XMR/USDT:USDT
SubscribeOrderBook for DASH/USDT:USDT
SubscribeOrderBook for ZEC/USDT:USDT
SubscribeOrderBook for XTZ/USDT:USDT
SubscribeOrderBook for BNB/USDT:USDT
SubscribeOrderBook for ATOM/USDT:USDT
SubscribeOrderBook for ONT/USDT:USDT
SubscribeOrderBook for IOTA/USDT:USDT
SubscribeOrderBook for BAT/USDT:USDT
SubscribeOrderBook for VET/USDT:USDT
SubscribeOrderBook for NEO/USDT:USDT
SubscribeOrderBook for QTUM/USDT:USDT
SubscribeOrderBook for IOST/USDT:USDT
SubscribeOrderBook for THETA/USDT:USDT
SubscribeOrderBook for ALGO/USDT:USDT
SubscribeOrderBook for ZIL/USDT:USDT
SubscribeOrderBook for KNC/USDT:USDT
SubscribeOrderBook for ZRX/USDT:USDT
SubscribeOrderBook for COMP/USDT:USDT
SubscribeOrderBook for OMG/USDT:USDT
SubscribeOrderBook for DOGE/USDT:USDT
SubscribeOrderBook for SXP/USDT:USDT
SubscribeOrderBook for KAVA/USDT:USDT
SubscribeOrderBook for BAND/USDT:USDT
SubscribeOrderBook for RLC/USDT:USDT
SubscribeOrderBook for WAVES/USDT:USDT
SubscribeOrderBook for MKR/USDT:USDT
SubscribeOrderBook for SNX/USDT:USDT
SubscribeOrderBook for DOT/USDT:USDT
SubscribeOrderBook for DEFI/USDT:USDT
SubscribeOrderBook for YFI/USDT:USDT
SubscribeOrderBook for BAL/USDT:USDT
SubscribeOrderBook for CRV/USDT:USDT
SubscribeOrderBook for TRB/USDT:USDT
SubscribeOrderBook for RUNE/USDT:USDT
SubscribeOrderBook for SUSHI/USDT:USDT
SubscribeOrderBook for SRM/USDT:USDT
SubscribeOrderBook for EGLD/USDT:USDT
SubscribeOrderBook for SOL/USDT:USDT
SubscribeOrderBook for ICX/USDT:USDT
SubscribeOrderBook for STORJ/USDT:USDT
SubscribeOrderBook for BLZ/USDT:USDT
SubscribeOrderBook for UNI/USDT:USDT
SubscribeOrderBook for AVAX/USDT:USDT
SubscribeOrderBook for FTM/USDT:USDT
SubscribeOrderBook for HNT/USDT:USDT
SubscribeOrderBook for ENJ/USDT:USDT
SubscribeOrderBook for FLM/USDT:USDT
SubscribeOrderBook for TOMO/USDT:USDT
SubscribeOrderBook for REN/USDT:USDT
SubscribeOrderBook for KSM/USDT:USDT
SubscribeOrderBook for NEAR/USDT:USDT
SubscribeOrderBook for AAVE/USDT:USDT
SubscribeOrderBook for FIL/USDT:USDT
SubscribeOrderBook for RSR/USDT:USDT
SubscribeOrderBook for LRC/USDT:USDT
SubscribeOrderBook for MATIC/USDT:USDT
SubscribeOrderBook for OCEAN/USDT:USDT
SubscribeOrderBook for CVC/USDT:USDT
SubscribeOrderBook for BEL/USDT:USDT
SubscribeOrderBook for CTK/USDT:USDT
SubscribeOrderBook for AXS/USDT:USDT
SubscribeOrderBook for ALPHA/USDT:USDT
SubscribeOrderBook for ZEN/USDT:USDT
SubscribeOrderBook for SKL/USDT:USDT
SubscribeOrderBook for GRT/USDT:USDT
SubscribeOrderBook for 1INCH/USDT:USDT
SubscribeOrderBook for CHZ/USDT:USDT
SubscribeOrderBook for SAND/USDT:USDT
SubscribeOrderBook for ANKR/USDT:USDT
SubscribeOrderBook for BTS/USDT:USDT
SubscribeOrderBook for LIT/USDT:USDT
SubscribeOrderBook for UNFI/USDT:USDT
SubscribeOrderBook for REEF/USDT:USDT
SubscribeOrderBook for RVN/USDT:USDT
SubscribeOrderBook for SFP/USDT:USDT
SubscribeOrderBook for XEM/USDT:USDT
SubscribeOrderBook for BTCST/USDT:USDT
SubscribeOrderBook for COTI/USDT:USDT
SubscribeOrderBook for CHR/USDT:USDT
SubscribeOrderBook for MANA/USDT:USDT
SubscribeOrderBook for ALICE/USDT:USDT
SubscribeOrderBook for HBAR/USDT:USDT
SubscribeOrderBook for ONE/USDT:USDT
SubscribeOrderBook for LINA/USDT:USDT
SubscribeOrderBook for STMX/USDT:USDT
SubscribeOrderBook for DENT/USDT:USDT
SubscribeOrderBook for CELR/USDT:USDT
SubscribeOrderBook for HOT/USDT:USDT
Started
System.Exception: System.Net.WebSockets.WebSocketException (0x80004005): Экземпляр "System.Net.WebSockets.InternalClientWebSocket" нельзя использовать для взаимодействия, поскольку он перешел в состояние "Aborted". ---> System.OperationCanceledException: Операция была отменена.
   в System.Threading.CancellationToken.ThrowOperationCanceledException()
   в System.Net.WebSockets.WebSocketConnectionStream.<WriteAsync>d__22.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__48.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
   в System.Net.WebSockets.WebSocketBase.ThrowIfAborted(Boolean aborted, Exception innerException)
   в System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   в System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.WebSocketClient.<send>d__32.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.<watchMultiple>d__1165.MoveNext()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.<watchMultiple>d__1165.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в ccxt.pro.binance.<watchOrderBookForSymbols>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.binance.<watchOrderBook>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.binance.<WatchOrderBook>d__64.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() в D:\Dev\Z\CCXT\Demo2\DemoLib\DemoNew3.cs:строка 106
System.Exception: System.InvalidOperationException: Для данного экземпляра WebSocket уже имеется один незавершенный вызов "SendAsync". Методы ReceiveAsync и SendAsync можно вызывать одновременно, однако в каждый момент времени разрешена только одна незавершенная операция для каждого из них.
   в System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.WebSocketClient.<send>d__32.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.<watchMultiple>d__1165.MoveNext()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.<watchMultiple>d__1165.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в ccxt.pro.binance.<watchOrderBookForSymbols>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.binance.<watchOrderBook>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.binance.<WatchOrderBook>d__64.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в DemoLib.DemoNew3.<>c__DisplayClass7_0.<<SubscribeOrderBook>b__0>d.MoveNext() в D:\Dev\Z\CCXT\Demo2\DemoLib\DemoNew3.cs:строка 106
SubscribeOrderBook cancelled for ATOM/USDT:USDT, remain tasks: 98
```

Solution is attached
[Demo2.zip](https://github.com/ccxt/ccxt/files/14747489/Demo2.zip)

### PR DESCRIPTION
**Pull request by ttodua**
_(fix #21920)_

for me, this fixed the issue of sendAsync. as I read, websocket cant have two simultaneous sendAsync operations, so one needs to be finished before another starts.

However, the second issue of websocket state still remains, will push the update for it too.

### CODE REVIEW

**Comment by ttodua** [comment]
@carlosmiei the second issue is also gone now. you can review this PR, ready.

File: cs/ccxt/ws/Client.cs [hunk 1]
```diff
@@ -240,13 +244,30 @@ public void Connect()
                 }
                 catch (Exception ex)
                 {
+                    _connectSemaphore.Release();
```
Comment (carlosmiei) [inline cs/ccxt/ws/Client.cs:247]: should we only release on a crash? what if we succeed?

Comment (ttodua) [reply cs/ccxt/ws/Client.cs:247]: ouch,  where did I put that, what a stupid mistake

**Comment by ttodua** [comment]
now, in both netfr 4.8 and net 6.0 I successfully run those demo snippets without any exceptions
