### PR TITLE
gemini - fix transaction parsing

### LINKED ISSUE #12895: Gemini: Parsing withdrawal as transaction results in error
Summary: CCXT 1.79.40 tries to parse withdrawals as transactions. However, withdrawals lack the `status` key, resulting in an error.

Withdrawing funds from gemini results with `self.privatePostV1WithdrawCurrency(self.extend(request, params))` 
results in a response as detailed in the comment: https://github.com/ccxt/ccxt/blame/master/python/ccxt/gemini.py#L882

```
        #     {
        #         "address":"mi98Z9brJ3TgaKsmvXatuRahbFRUFKRUdR",
        #         "amount":"1",
        #         "withdrawalId":"02176a83-a6b1-4202-9b85-1c1c92dd25c4",
        #         "message":"You have requested a transfer of 1 BTC to mi98Z9brJ3TgaKsmvXatuRahbFRUFKRUdR. This withdrawal will be sent to the blockchain within the next 60 seconds."
        #     }
```

Version 1.79.40 added lines to parse the transaction: https://github.com/ccxt/ccxt/blame/master/python/ccxt/gemini.py#L903-L906
```
        result = self.safe_string(response, 'result')
        if result == 'error':
            raise ExchangeError(self.id + ' withdraw() failed: ' + self.json(response))
        return self.parse_transaction(response, currency)
```

However, `parse_transaction` fails if the transaction does not have a `status` key, which the withdrawal response does not: https://github.com/ccxt/ccxt/blame/master/python/ccxt/gemini.py#L947
```
        if transaction['status']:
            status = 'ok'
```

### PR DESCRIPTION
**Pull request by ttodua**
I can't test gemini, but this should fix.

[fixes #12895]

### CODE REVIEW

File: js/gemini.js [hunk 1]
```diff
@@ -976,11 +976,8 @@ module.exports = class gemini extends Exchange {
         const code = this.safeCurrencyCode (currencyId, currency);
         const address = this.safeString (transaction, 'destination');
         const type = this.safeStringLower (transaction, 'type');
-        let status = 'pending';
-        // When deposits show as Advanced or Complete they are available for trading.
-        if (transaction['status']) {
-            status = 'ok';
-        }
+        // if status field is available, then it's complete
+        const statusRaw = this.safeString (transaction, 'status');
```
Comment (kroitor) [inline js/gemini.js:980]: We should not lose the `pending` status if a deposit or a withdrawal is not advanced and not complete. Which other statuses are possible?

Comment (ttodua) [reply js/gemini.js:980]: the reason I've removed `pending` is that [withdraw method (`/withdraw` endpoint)](https://docs.gemini.com/rest-api/#withdraw-crypto-funds) doesn't have 'status' endpoint at all,  `parseTransaction` (before we routed `withdrawal` response through it) only served in gemini for [fetchTransactions (`/transfers` endpoint)](https://docs.gemini.com/rest-api/#transfers), which have 'status' only with two possible values: `Advanced` or `Complete`. So, as there was no sign of other, I am not sure we should have `pending`. maybe it could be `cancelled, rejected` or etc. so, why we might say 'pending' in that case?
