### PR TITLE
ftx - unrealizedPnl fix

### LINKED ISSUE #14235: Bugs on FTX wrapper
when `unrealized pnl` is 0.0(from `info`, we can find the original unrealizedPnl), the ccxt ftx will transfer 0 to None.
截图 2022-07-06 02-51-13

### PR DESCRIPTION
**Pull request by ttodua**
recentPln smells to be quite something different value (not documented enough), but it's obviously not an unrealized-profit.

fixes #14235

### CODE REVIEW

File: js/ftx.js [hunk 1]
```diff
@@ -2409,7 +2409,7 @@ module.exports = class ftx extends Exchange {
         const initialMargin = Precise.stringMul (notionalString, initialMarginPercentage);
         const maintenanceMarginPercentageString = this.safeString (position, 'maintenanceMarginRequirement');
         const maintenanceMarginString = Precise.stringMul (notionalString, maintenanceMarginPercentageString);
-        const unrealizedPnlString = this.safeString (position, 'recentPnl');
+        const unrealizedPnlString = this.safeString (position, 'unrealizedPnl');
```
Comment (kroitor) [inline js/ftx.js:2412]:
```suggestion
        const unrealizedPnlString = this.safeString2 (position, 'unrealizedPnl', 'recentPnl');
```

Comment (kroitor) [reply js/ftx.js]: @ttodua it has to be tested:

Screenshot 2022-07-07 at 23 35 24

Comment (ttodua) [reply js/ftx.js]: I've seen that field in api docs, but i meant, there is no explanation of that field. when I've tested that today earlier, it returned null for my position/s. i'll dig into it further and let you know
