### PR TITLE
Bybit :: Set price undefined on market orders

### LINKED ISSUE #11839: Enhancement - bybit fetch_order()
- OS: win7
- Programming Language version: Python 3.7.1
- CCXT version: 1.72.15

Issue:
I recently found that fetch_order() return had a key called 'price' that gave a applicable but wrong value. But that is because of the bybit. So, i had a small chat with the bybit support. 

Chat with bybit support:
________________________________________
me:
'btc/usdt' - testnet 
1. by web-UI:  
    current price = 37552.50 
2. market buy placed for qty = 0.01 
3. by /private/linear/order/search:  
    'last_exec_price': '37511.5' (ok) 
    'price': : '39387' (what !??) 
'price' value is 4.89% higher that current price 
what is 'price'? the documentation says,  
price = 'Order price'  
but then shouldn't it be near to the current price? 
but it is a whopping 4.89% higher than current 
price (for a 'buy' order). what's going on? 
ref: https://bybit-exchange.github.io/docs/linear/#t-queryactive

bybit:
Has the order been executed? What entry price do you see on testnet.bybit.com?

me:
Order is executed. entry price on testnet.bybit.com is '37511.5'

bybit:
A traditional market price order which will be filled at the best available price. "price" is not required for this type of order. (It is for limit orders). So the price that was executed is last_exec_price.

me:
so, as i understand, 'price' value can (or rather should) be ignored for market order. is it?

bybit:
Yes

me:
tnx
________________________________________

So, basically, if the 'price' can have a None or just a blank field in case of market orders, that would be convenient and less confusing.
Of course its not a very big issue for me, but just in case you want to take interest in.
And true, its bybit that needs to correct that but it would not be a bad thing to do it in ccxt too. 
You decide to do it or not, in either case, tnx buddy.

### PR DESCRIPTION
**Pull request by carlosmiei**
fixes #11839

### CODE REVIEW

File: js/bybit.js [hunk 1]
```diff
@@ -1653,7 +1653,10 @@ module.exports = class bybit extends Exchange {
         const timestamp = this.parse8601 (this.safeString (order, 'created_at'));
         const id = this.safeString2 (order, 'order_id', 'stop_order_id');
         const type = this.safeStringLower (order, 'order_type');
-        const price = this.safeString (order, 'price');
+        let price = undefined;
```
Comment (carlosmiei) [inline js/bybit.js:1656]: @kroitor Although we're setting it as undefined, the price will have a value because it's calculated inside safeorder using the amount and cost
