### PR TITLE
bybit: integrate derivatives v3

### LINKED ISSUE #15648: bybit can't use fetchOrder by id after created
I tried to search a lot on issues tab but no one report about this, I also tried to look at fetchOpenOrders and fetchClosedOrders and other endpoints tried using a custom id did not work too, closed:True. Everything I could find I tried

- OS: Mac OS 12.6
- Programming Language version: Python 3.9.10
- CCXT version: 2.1.67

```
import ccxt
clientData = {
    'apiKey': 'xxx',
    'secret': 'xxx',
    'options': {
        'defaultType': 'future'
    }
}
client = ccxt.bybit(clientData)
data = client.createOrder(
    'XRPUSDT',
    'MARKET',
    'sell',
    1
)
print(data)
print(client.fetchOrder(data.get('id'), 'XRPUSDT'))
```

```
Traceback (most recent call last):
  File "/Users/ulisses/Desktop/bybit.py", line 17, in <module>
    print(client.fetchOrder(data.get('id'), 'XRPUSDT'))
  File "/Users/ulisses/Projects/env/btc24h/lib/python3.9/site-packages/ccxt/bybit.py", line 2966, in fetch_order
    raise OrderNotFound(self.id + ' fetchOrder() order ' + id + ' not found')
ccxt.base.errors.OrderNotFound: bybit fetchOrder() order xx-xx-xx-xx-xxxx not found
```

### PR DESCRIPTION
**Pull request by sc0Vu**
Bybit have released derivatives v3 recently, and separate two parts (unified margin and contract v3). In this PR, I'll integrate derivatives v3 for bybit.

##### For unified margin

- [x] fetchOrderBook
- [x] fetchOHLCV
- [x] fetchMarketLeverageTiers
- [x] fetchOpenInterestHistory
- [x] fetchTrades
- [x] fetchFundingRateHistory
- [x] fetchTickers
- [x] add v3 public time
- [x] update fetchBalance
- [x] update setLeverage
- [x] update createOrder
- [x] update cancelOrder
- [x] update fetchOpenOrders
- [x] update fetchOrders
- [x] update fetchClosedOrders
- [x] update cancelAllOrders
- [x] add fetchPosition
- [x] update fetchPositions

TODO for refactor:
- [x] fetchOHLCV
- [x] cancelOrder
- [x] cancelAllOrders
- [x] fetchOrders
- [x] fetchClosedOrders
- [x] fetchOpenOrders
- [x] fetchPositions
- [x] setLeverage
- [x] fetchOpenInterestHistory
- [x] fetchMarketLeverageTiers

##### For contract v3

- [x] update fetchBalance
- [x] update setLeverage
- [x] update setPositionMode
- [x] update createOrder
- [x] update cancelOrder
- [x] update fetchOpenOrders
- [x] update fetchOrders
- [x] update fetchClosedOrders
- [x] update cancelAllOrders
- [x] update fetchPosition
- [x] update fetchPositions
- [x] update fetchMyTrades

( fixes #15648 )

### CODE REVIEW

File: js/bybit.js [hunk 1]
```diff
@@ -1617,8 +1674,30 @@ module.exports = class bybit extends Exchange {
         let intervalKey = 'interval';
         let sinceKey = 'from';
         const isUsdcSettled = market['settle'] === 'USDC';
+        const enableUnifiedMargin = this.safeValue (this.options, 'enableUnifiedMargin');
```
Comment (carlosmiei) [inline js/bybit.js:1677]: with this unified margin integration, we have huge methods with a lot of endpoints logic, request params, etc, making them very hard to maintain (we never know if we might break something accidentally), and even more important to remove the v2 logic after bybit deprecates it. 

With that in mind, I would like to suggest this approach, for every unified method we would split the v2 and v3 logic into different methods, something like this:

```Javascript
    async fetchOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
        // common logic (parse timeframe, load market, etc)
        if (spot) {
            response = this.fetchSpotOHLCV (symbol, timeframe, since, limit, params);
        }
        if (unifiedMargin) {
            response = this.fetchUnifiedMargintOHLCV (symbol, timeframe, since, limit, params);
        } else {
            response = this.fetchDerivativesOHLCV (symbol, timeframe, since, limit, params);
        }
    }
```

In the future, to deprecate v2 we just need to comment out one line and remove the method with the isolated v2 logic, which is much easier than dissecting the current logic months after implementing it.

what do you think? @sc0Vu @kroitor

Comment (sc0Vu) [reply js/bybit.js:1677]: @carlosmiei they did change requests payload and response, for now I can only test manually.

For the future upgrading, I agree with you, it's might be easier if we separate. But if we do that, isn't it over-engineering? (There will be some duplicate code blocks.)

Comment (carlosmiei) [reply js/bybit.js:1677]: @sc0Vu I know that we would get some duplication the thing is I suspect that v3 and v2 logic are getting too tied and will be hard to safely split in the future or even make to apply some fix if needed, @kroitor what do you think?

Comment (kroitor) [reply js/bybit.js:1677]: I would totally agree with the approach proposed by @carlosmiei ! I think in general we should refrain from mixing up the logic, ideally just split them into exchange-specific methods and call those methods under an if-else conditional, as shown above.

**Sidenote**: I'm not sure how margin OHLCV are different from regular spot OHLCV with bybit v2 vs v3, they're usually the same thing with the rest of the exchanges – margin trading is done with the same set of pairs as regular spot trading, the only difference is the underlying settlement logic within the exchange engine. Or, put simply, spot trading is the same as margin trading with leverage 1 without borrowing. Let me know if I'm missing something here.

**Comment by carlosmiei** [comment]
@sc0Vu can you check what is going on with the build?

File: js/bybit.js [hunk 2]
```diff
@@ -1627,74 +1804,147 @@ module.exports = class bybit extends Exchange {
...
+        //         ],
+        //         "ext_code": null,
+        //         "ext_info": null
+        //     }
+        //
+        const ohlcvs = this.safeValue (response, 'result');
+        return this.parseOHLCVs (ohlcvs, market, timeframe, since, limit);
+    }
+
+    async fetchUnifiedMarginOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
```
Comment (carlosmiei) [inline js/bybit.js:1837]: @sc0Vu we don't need UnifiedMargin methods for public data they're the same

File: js/bybit.js [hunk 3]
```diff
@@ -1648,47 +1833,16 @@ module.exports = class bybit extends Exchange {
                 isUsdcSettled = defaultSettle === 'USDC';
             }
         }
-        let method = undefined;
+        const enableUnifiedMargin = this.safeValue (this.options, 'enableUnifiedMargin');
```
Comment (carlosmiei) [inline js/bybit.js:1836]: @sc0Vu we should be checking `params` too (for every method). 

Check `handleOptionAndParams` we might use if we override it here and change it slightly.  The stock implementation checks for `default+optionName` which does not really apply here I think

Comment (sc0Vu) [reply js/bybit.js:1836]: @carlosmiei like this?:

```JS
let enableUnifiedMargin = this.safeValue (this.options, 'defaultEnableUnifiedMargin', false);
enableUnifiedMargin = this.safeValue2 (params, 'enableUnifiedMargin', 'defaultEnableUnifiedMargin', enableUnifiedMargin);
params = this.omit (params, [ 'enableUnifiedMargin', 'defaultEnableUnifiedMargin' ]);
```

BTW, should we also change this:
```JS
if (type !== 'spot') {
                let defaultSettle = this.safeString (this.options, 'defaultSettle', 'USDT'); // this line seems not work
                defaultSettle = this.safeString2 (params, 'settle', 'defaultSettle', isUsdcSettled); // change to this.safeString2 (params, 'settle', 'defaultSettle', defaultSettle);
                params = this.omit (params, [ 'settle', 'defaultSettle' ]);
                isUsdcSettled = defaultSettle === 'USDC';
            }
```

Comment (carlosmiei) [reply js/bybit.js:1836]: @sc0Vu 

> let enableUnifiedMargin = this.safeValue (this.options, 'defaultEnableUnifiedMargin', false);
> enableUnifiedMargin = this.safeValue2 (params, 'enableUnifiedMargin', 'defaultEnableUnifiedMargin', enableUnifiedMargin);
> params = this.omit (params, [ 'enableUnifiedMargin', 'defaultEnableUnifiedMargin' ]);

⬆️  this is what `handleOptionAndParams` does, but for the `enableUnifiedMargin` option I'm not sure that the `defaultEnableUnifiedMargin` makes sense tbh, that's why I was suggesting overriding handleOptionAndParams here to remove the "default" part, wdyt?

> if (type !== 'spot') {
>     let defaultSettle = this.safeString (this.options, 'defaultSettle', 'USDT'); // this line seems not work
>     defaultSettle = this.safeString2 (params, 'settle', 'defaultSettle', isUsdcSettled); // change to this.safeString2 (params, 'settle', 'defaultSettle', defaultSettle);
>     params = this.omit (params, [ 'settle', 'defaultSettle' ]);
>     isUsdcSettled = defaultSettle === 'USDC';
> }
> 

⬆️  here I think we can use `handleOptionAndParams` directly no? like: `handleOptionAndParams(params, 'method name', 'settle', 'USDT')`

Comment (sc0Vu) [reply js/bybit.js:1836]: @carlosmiei that make sense, I'll update.

File: js/bybit.js [hunk 4]
```diff
@@ -63,6 +63,7 @@ module.exports = class bybit extends Exchange {
                 'fetchOrderBook': true,
                 'fetchOrders': true,
                 'fetchOrderTrades': true,
+                'fetchPosition': true,
                 'fetchPositions': true,
                 'fetchPremiumIndexOHLCV': true,
                 'fetchTicker': true,
```
Comment (carlosmiei) [inline js/bybit.js:69]: @sc0Vu aren't we missing `fetchTicker`upgrade? 
I'm not seeing this endpoint being used here: https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_tickerhead
image

File: js/bybit.js [hunk 5]
```diff
@@ -48,7 +48,7 @@ module.exports = class bybit extends Exchange {
                 'fetchDepositAddressesByNetwork': true,
```
Comment (carlosmiei) [inline js/bybit.js:48]: @sc0Vu 
Can't we also update fetchMarkets with this method? https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_instrhead

⬆️  just bear in mind that I don't think that v3 and unified margin are not necessarily the same thing, meaning that I think we can use v3 to do non-unified-margin things (the opposite is not true), like for instance create a swap order using the normal margin mode

So I think we should probably check one more option, `version`, and apply the following logic:
- if version === v3 or unifiedMargin 
  - use v3 endpoint to load markets, trades, tickers, etc 
  -  if unifiedMargin -> use v3 unified margin endpoints to order related methods
  - if not unified margin -> use v3 "regular" endpoints to order related methods

File: js/bybit.js [hunk 6]
```diff
@@ -2337,29 +2791,63 @@ module.exports = class bybit extends Exchange {
...
+         */
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        let enableUnifiedMargin = undefined;
+        [ enableUnifiedMargin, params ] = this.handleOptionAndParamsValue (params, 'fetchTrades', 'enableUnifiedMargin', false);
+        const isUsdcSettled = market['settle'] === 'USDC';
+        if (market['type'] === 'spot') {
+            return await this.fetchSpotTrades (symbol, since, limit, params);
+        } else if (!isUsdcSettled) {
+            if (enableUnifiedMargin) {
```
Comment (carlosmiei) [inline js/bybit.js:2818]: We should not check `enableUnifiedMargin` option here, as I said before unified is an orthogonal concept to trades, tickers, markets, etc (only applies to order/account-related methods)

So in this case, I think the logic should be:
-  if v3 version 
   - use v3 endpoint to fetchTrades (I think the same endpoint fetches options and usdc settled as well but pls double check it)
   - otherwise
      - use the current logic

File: js/bybit.js [hunk 7]
```diff
@@ -1640,55 +1848,22 @@ module.exports = class bybit extends Exchange {
...
-                let defaultSettle = this.safeString (this.options, 'defaultSettle', 'USDT');
-                defaultSettle = this.safeString2 (params, 'settle', 'defaultSettle', isUsdcSettled);
-                params = this.omit (params, [ 'settle', 'defaultSettle' ]);
-                isUsdcSettled = defaultSettle === 'USDC';
-            }
+            [ defaultSettle, params ] = this.handleOptionAndParams (params, 'fetchTickers', 'settle', 'USDT');
+            isUsdcSettled = defaultSettle === 'USDC';
         }
-        let method = undefined;
+        let enableUnifiedMargin = undefined;
```
Comment (carlosmiei) [inline js/bybit.js:1856]: Please check `fetchTrades` comment

File: js/bybit.js (hunk 6 above)
Comment (sc0Vu) [reply js/bybit.js:2818]: @carlosmiei because these endpoints are public, do you suggest we replace v2 calls with v3 derivatives method? For example:

```JS
if (type === 'spot') {
    return await this.fetchSpotTickers (symbols, params);
}
return await this.fetchDerivativesTickers (symbols, params);
```

In this case, I think we can remove `fetchV2DerivativesTickers`.

File: js/bybit.js (hunk 5 above)
Comment (sc0Vu) [reply js/bybit.js:48]: I'm not sure whether the trades/tickers are the same between v3 and v2 endpoints. Probably bybit will upgrade the v2 apis to v3 (eg, v2 linear to v3 linear)? If the price is different, would that break `createOrder` functionality?

If they are the same, we can also check the version. BTW, should we compare v3 in other public methods?

Comment (sc0Vu) [reply js/bybit.js:48]: After check https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_instrhead, it seems we can only fetch one category market at the time. It might need 3 requests to fetch linear/inverse/options markets.

File: js/bybit.js (hunk 6 above)
Comment (sc0Vu) [reply js/bybit.js]: How do you think we only check the version in public methods?

Comment (carlosmiei) [reply js/bybit.js]: @sc0Vu yeah that sounds good

File: js/bybit.js (hunk 5 above)
Comment (carlosmiei) [reply js/bybit.js:48]: > I'm not sure whether the trades/tickers are the same between v3 and v2 endpoints. Probably bybit will upgrade the v2 apis to v3 (eg, v2 linear to v3 linear)? If the price is different, would that break `createOrder` functionality?
> 
> If they are the same, we can also check the version. BTW, should we compare v3 in other public methods?

If they are not the same we have to update them accordingly. Basically, if the user selects v3 version we have to use everything from v3 (tickers, precisions, etc, etc)

File: js/bybit.js [hunk 8]
```diff
@@ -1610,16 +1672,213 @@ module.exports = class bybit extends Exchange {
...
+        //         "retExtInfo": null,
+        //         "time": 1663670053454
+        //
         const result = this.safeValue (response, 'result', []);
         let rawTicker = undefined;
         if (Array.isArray (result)) {
             rawTicker = this.safeValue (result, 0);
         } else {
-            rawTicker = result;
+            if (isV3) {
```
Comment (carlosmiei) [inline js/bybit.js:1716]: @sc0Vu spot v3 does not have `list` so this is breaking rn 
image

File: js/bybit.js [hunk 9]
```diff
@@ -2337,29 +2840,58 @@ module.exports = class bybit extends Exchange {
...
+         * @param {int|undefined} limit the maximum amount of trades to fetch
+         * @param {object} params extra parameters specific to the bybit api endpoint
+         * @returns {[object]} a list of [trade structures]{@link https://docs.ccxt.com/en/latest/manual.html?#public-trades}
+         */
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const isV3 = this.version === 'v3';
+        const isUsdcSettled = market['settle'] === 'USDC';
+        if (market['type'] === 'spot') {
+            return await this.fetchSpotTrades (symbol, since, limit, params);
```
Comment (carlosmiei) [inline js/bybit.js:2864]: also, something broke fetchTrades for spot markets: 
image

File: js/bybit.js [hunk 10]
```diff
@@ -2337,29 +2840,58 @@ module.exports = class bybit extends Exchange {
...
+        } else if (isV3) {
+            return await this.fetchDerivativesTrades (symbol, since, limit, params);
```
Comment (carlosmiei) [inline js/bybit.js:2866]: @sc0Vu you need to re-visit the parsers, for instance for v3 linear swap trade `amount` is `size`  and we're not parsing it 
image

File: js/bybit.js [hunk 11]
```diff
@@ -1823,74 +2047,149 @@ module.exports = class bybit extends Exchange {
...
+        //                 "44213.97591627",
+        //                 24,
+        //                 "0",
+        //                 "0"
+        //             ]
+        //         ],
+        //         "ext_code": null,
+        //         "ext_info": null
+        //     }
+        //
```
Comment (carlosmiei) [inline js/bybit.js:2075]: Not working, spot ohlcv has `list` not  `result` 
image

File: js/bybit.js [hunk 12]
```diff
@@ -2538,16 +3151,56 @@ module.exports = class bybit extends Exchange {
...
+        const balances = this.safeValue2 (data, 'balances', 'coin');
         if (Array.isArray (balances)) {
             // spot balances
             for (let i = 0; i < balances.length; i++) {
                 const balance = balances[i];
-                const currencyId = this.safeString (balance, 'coin');
+                const currencyId = this.safeString2 (balance, 'coin', 'currencyCoin');
                 const code = this.safeCurrencyCode (currencyId);
                 const account = this.account ();
                 account['free'] = this.safeString (balance, 'availableBalance');
```
Comment (carlosmiei) [inline js/bybit.js:3206]: question, can't we use these fields to calculate the `used` amount? 
image

File: js/bybit.js [hunk 13]
```diff
@@ -872,7 +898,17 @@ module.exports = class bybit extends Exchange {
...
+        let promises = [];
+        if (isV3) {
+            promises = [
+                this.fetchDerivativesMarkets ({ 'category': 'linear' }),
+                this.fetchDerivativesMarkets ({ 'category': 'inverse' }),
+                this.fetchDerivativesMarkets ({ 'category': 'option' }),
+            ];
+        } else {
+            promises = [ this.fetchSwapAndFutureMarkets (params), this.fetchUSDCMarkets (params) ];
+        }
```
Comment (carlosmiei) [inline js/bybit.js:911]: @sc0Vu, this is not right for v3, we're not unpacking all the 3 promises here

File: js/bybit.js [hunk 14]
```diff
@@ -3678,65 +4688,323 @@ module.exports = class bybit extends Exchange {
...
+        if (symbol === undefined) {
+            throw new ArgumentsRequired (this.id + ' cancelOrder() requires a symbol argument');
+        }
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const isUsdcSettled = market['settle'] === 'USDC';
+        let enableUnifiedMargin = undefined;
+        [ enableUnifiedMargin, params ] = this.handleOptionAndParamsValue (params, 'cancelOrder', 'enableUnifiedMargin', false);
+        if (market['spot']) {
+            return this.cancelSpotOrder (id, symbol, params);
```
Comment (carlosmiei) [inline js/bybit.js:4857]: @sc0Vu we're missing waiting for the promise here

File: js/bybit.js [hunk 15]
```diff
@@ -3678,65 +4688,323 @@ module.exports = class bybit extends Exchange {
...
+        } else if (enableUnifiedMargin) {
+            return this.cancelUnifiedMarginOrder (id, symbol, params);
```
Comment (carlosmiei) [inline js/bybit.js:4859]: here

File: js/bybit.js [hunk 16]
```diff
@@ -3678,65 +4688,323 @@ module.exports = class bybit extends Exchange {
...
+        } else if (isUsdcSettled) {
+            return this.cancelUSDCOrder (id, symbol, params);
```
Comment (carlosmiei) [inline js/bybit.js:4861]: here

File: js/bybit.js [hunk 17]
```diff
@@ -3678,65 +4688,323 @@ module.exports = class bybit extends Exchange {
...
+        }
+        return this.cancelDerivativesOrder (id, symbol, params);
```
Comment (carlosmiei) [inline js/bybit.js:4863]: and here

File: js/bybit.js [hunk 18]
```diff
@@ -665,6 +668,29 @@ module.exports = class bybit extends Exchange {
         return this.milliseconds () - this.options['timeDifference'];
     }
 
+    handleOptionAndParamsValue (params, methodName, optionName, defaultValue = undefined) {
+        // This method can be used to obtain method specific properties, i.e: this.handleOptionAndParams (params, 'fetchPosition', 'marginMode', 'isolated')
+        const defaultOptionName = 'default' + this.capitalize (optionName); // we also need to check the 'defaultXyzWhatever'
```
Comment (carlosmiei) [inline js/bybit.js:673]: isn't the entire goal of overriding this here to remove this `default` thing? so users would have `enableUnifiedMargin` in options instead of `defaultUnifiedMargin` ?

File: js/bybit.js [hunk 19]
```diff
@@ -3203,6 +4184,101 @@ module.exports = class bybit extends Exchange {
         return this.parseOrder (order);
     }
 
+    async createUnifiedMarginOrder (symbol, type, side, amount, price = undefined, params = {}) {
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        if (!market['linear'] && !market['option']) {
+            throw new NotSupported (this.id + ' createOrder does not allow inverse market orders for ' + symbol + ' markets');
```
Comment (carlosmiei) [inline js/bybit.js:4191]: first isn't easier to check `if market['inverse']` ? 🙂 
Second, I think this message is a bit confusing, if you are in the unifiedMargin mode you still can place orders for inverse markets the only difference is that will use the normal "margin", so should we call the normal "create order" method if the user chooses an inverse market?

File: js/bybit.js [hunk 20]
```diff
@@ -3114,8 +4091,12 @@ module.exports = class bybit extends Exchange {
         const market = this.market (symbol);
         symbol = market['symbol'];
         const isUsdcSettled = (market['settle'] === 'USDC');
+        let enableUnifiedMargin = undefined;
+        [ enableUnifiedMargin, params ] = this.handleOptionAndParamsValue (params, 'createOrder', 'enableUnifiedMargin', false);
```
Comment (carlosmiei) [inline js/bybit.js:4095]: @sc0Vu aren't we missing the v3 upgrade here? https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_placeorder

Comment (sc0Vu) [reply js/bybit.js:4095]: There is a `createUnifiedMarginOrder` to submit v3 order. Is anything wrong in that function?

Comment (sc0Vu) [reply js/bybit.js:4095]: @carlosmiei it seems we miss some contract v3 endpoint, I'll add.

File: js/bybit.js (hunk 19 above)
Comment (carlosmiei) [reply js/bybit.js:4191]: @sc0Vu yeah it can be a bit confusing, but if we want to throw here i think we should improve the error message guiding the user to the right path

**Comment by philipperemy** [comment]
Good luck guys! I guess many people are waiting for this pull request to be merged.

File: js/bybit.js [hunk 21]
```diff
@@ -3114,13 +4148,19 @@ module.exports = class bybit extends Exchange {
...
+        const isV3 = (this.version === 'v3');
         if (market['spot']) {
             return await this.createSpotOrder (symbol, type, side, amount, price, params);
+        } else if (enableUnifiedMargin) {
+            return await this.createUnifiedMarginOrder (symbol, type, side, amount, price, params);
         } else if (isUsdcSettled) {
             return await this.createUsdcOrder (symbol, type, side, amount, price, params);
-        } else {
-            return await this.createContractOrder (symbol, type, side, amount, price, params);
+        } else if (isV3) {
```
Comment (carlosmiei) [inline js/bybit.js:4160]: @sc0Vu shouldn't we check `if v3` before `is USDC` ? afaik in v3 USDC orders go to the same endpoint as the other derivatives

File: js/bybit.js [hunk 22]
```diff
@@ -3277,126 +4321,307 @@ module.exports = class bybit extends Exchange {
...
+            const takeProfitPrice = this.safeValue (params, 'takeProfitPrice');
+            const isTakeProfitOrder = takeProfitPrice !== undefined;
+            const isStopOrder = isStopLossOrder || isTakeProfitOrder;
+            if (isStopOrder) {
+                request['triggerBy'] = 'LastPrice';
+                const stopPx = isStopLossOrder ? stopLossPrice : takeProfitPrice;
+                const preciseStopPrice = this.priceToPrecision (symbol, stopPx);
+                request['triggerPrice'] = preciseStopPrice;
+                const delta = this.numberToString (market['precision']['price']);
+                request['basePrice'] = isStopLossOrder ? Precise.stringSub (preciseStopPrice, delta) : Precise.stringAdd (preciseStopPrice, delta);
```
Comment (carlosmiei) [inline js/bybit.js:4403]: Hum I think `basePrice` does not exist anymore, now they have `triggerDirection` 
https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_placeorder

File: js/bybit.js [hunk 23]
```diff
@@ -3277,126 +4321,307 @@ module.exports = class bybit extends Exchange {
...
-        const takeProfitPrice = this.safeValue (params, 'takeProfitPrice');
-        const isTakeProfitOrder = takeProfitPrice !== undefined;
-        if (isTriggerOrder) {
-            request['trigger_by'] = 'LastPrice';
-            const preciseStopPrice = this.priceToPrecision (symbol, triggerPrice);
-            request['stop_px'] = parseFloat (preciseStopPrice);
-            const basePrice = this.safeValue2 (params, 'base_price', 'basePrice');
-            if (basePrice === undefined) {
-                throw new ArgumentsRequired (this.id + ' createOrder() requires a base_price parameter for trigger orders, your triggerPrice > max(market price, base_price) or triggerPrice < min(market price, base_price)');
+        if (market['swap']) {
```
Comment (carlosmiei) [inline js/bybit.js:4390]: Why aren't we applying the stopPrice/tk/sl logic to futures and options?

File: js/bybit.js [hunk 24]
```diff
@@ -3572,88 +4822,21 @@ module.exports = class bybit extends Exchange {
             throw new NotSupported (this.id + ' editOrder() does not support spot markets');
         } else if (isUsdcSettled) {
             return await this.editUsdcOrder (id, symbol, type, side, amount, price, params);
-        } else {
-            return await this.editContractOrder (id, symbol, type, side, amount, price, params);
         }
+        return await this.editContractOrder (id, symbol, type, side, amount, price, params);
```
Comment (carlosmiei) [inline js/bybit.js:4826]: Do we need to update `editOrder` to add the unifiedMargin part? 
https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#t-dv_replaceorder

File: js/bybit.js (hunk 21 above)
Comment (sc0Vu) [reply js/bybit.js:4160]: As I saw in testnet contract account, I think contract v3 is for usdt contract.

File: js/bybit.js (hunk 22 above)
Comment (sc0Vu) [reply js/bybit.js:4403]: I think it's gonna be:

```JS
request['triggerDirection'] = isStopLossOrder ? 2 : 1; // 1: rise; 2: fall
```

**Comment by cowboyee** [comment]
thanks guy!  many people are waiting for this merge i believe!

File: js/bybit.js [hunk 25]
```diff
@@ -495,7 +514,9 @@ module.exports = class bybit extends Exchange {
                     '10018': RateLimitExceeded, // exceed ip rate limit
                     '10020': PermissionDenied, // {"retCode":10020,"retMsg":"your account is not a unified margin account, please update your account","result":null,"retExtInfo":null,"time":1664783731123}
                     '12201': BadRequest, // {"retCode":12201,"retMsg":"Invalid orderCategory parameter.","result":{},"retExtInfo":null,"time":1666699391220}
+                    '110007': InsufficientFunds, // {"retCode":110007,"retMsg":"ab not enough for new order","result":{},"retExtInfo":{},"time":1668838414793}
```
Comment (philipperemy) [inline js/bybit.js:517]: You forgot some errors: https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#t-errors

File: js/bybit.js [hunk 26]
```diff
@@ -3203,6 +4244,186 @@ module.exports = class bybit extends Exchange {
...
+        };
+        if (market['future']) {
+            const positionIdx = this.safeInteger (params, 'position_idx', 0); // 0 One-Way Mode, 1 Buy-side, 2 Sell-side
+            request['position_idx'] = positionIdx;
+            params = this.omit (params, 'position_idx');
+        }
+        const isMarket = lowerCaseType === 'market';
+        const isLimit = lowerCaseType === 'limit';
+        if (isLimit) {
+            request['price'] = this.priceToPrecision (symbol, price);
```
Comment (carlosmiei) [inline js/bybit.js:4375]: if limit and price==undefined we should throw a meaningful error here

File: js/bybit.js [hunk 27]
```diff
@@ -3203,6 +4244,186 @@ module.exports = class bybit extends Exchange {
...
+        } else if (timeInForce === 'ioc') {
+            request['timeInForce'] = 'ImmediateOrCancel';
+        }
+        const triggerPrice = this.safeValue2 (params, 'stopPrice', 'triggerPrice');
+        const stopLossPrice = this.safeValue (params, 'stopLossPrice', triggerPrice);
+        const isStopLossOrder = stopLossPrice !== undefined;
+        const takeProfitPrice = this.safeValue (params, 'takeProfitPrice');
+        const isTakeProfitOrder = takeProfitPrice !== undefined;
+        const isStopOrder = isStopLossOrder || isTakeProfitOrder;
+        if (isStopOrder) {
```
Comment (carlosmiei) [inline js/bybit.js:4395]: @sc0Vu this logic isn't right, stopOrder/tp/sl are not mutually exclusive it can be all of them simultaneously 

image

File: js/bybit.js [hunk 28]
```diff
@@ -3114,13 +4149,19 @@ module.exports = class bybit extends Exchange {
...
+        } else if (enableUnifiedMargin) {
+            return await this.createUnifiedMarginOrder (symbol, type, side, amount, price, params);
         } else if (isUsdcSettled) {
             return await this.createUsdcOrder (symbol, type, side, amount, price, params);
-        } else {
-            return await this.createContractOrder (symbol, type, side, amount, price, params);
+        } else if (isV3) {
+            return await this.createContractV3Order (symbol, type, side, amount, price, params);
         }
+        return await this.createContractOrder (symbol, type, side, amount, price, params);
```
Comment (carlosmiei) [inline js/bybit.js:4164]: I think we also need to send futures to the old "endpoint" for now

**Comment by frosty00** [comment]
i'm deleting all the v2 endpoints, the v3 endpoints have support for all the markets you just need to parse it properly

File: js/bybit.js [hunk 29]
```diff
@@ -4,7 +4,7 @@
 
 const Exchange = require ('./base/Exchange');
 const { TICK_SIZE } = require ('./base/functions/number');
-const { AuthenticationError, ExchangeError, ArgumentsRequired, PermissionDenied, InvalidOrder, OrderNotFound, InsufficientFunds, BadRequest, RateLimitExceeded, InvalidNonce, NotSupported } = require ('./base/errors');
+const { AuthenticationError, ExchangeError, ArgumentsRequired, PermissionDenied, InvalidOrder, OrderNotFound, InsufficientFunds, BadRequest, RateLimitExceeded, InvalidNonce, NotSupported, BadReqeust } = require ('./base/errors');
```
Comment (carlosmiei) [inline js/bybit.js:7]: typo: BadReqeust

File: js/bybit.js [hunk 30]
```diff
@@ -48,7 +48,7 @@ module.exports = class bybit extends Exchange {
                 'fetchDepositAddressesByNetwork': true,
                 'fetchDeposits': true,
                 'fetchFundingRate': true,
-                'fetchFundingRateHistory': false,
+                'fetchFundingRateHistory': true,
                 'fetchIndexOHLCV': true,
                 'fetchLedger': true,
```
Comment (carlosmiei) [inline js/bybit.js:53]: @sc0Vu I think we're missing this ugprade: https://bybit-exchange.github.io/docs/account_asset/v3/#t-withdrawrecordquery

File: js/bybit.js [hunk 31]
```diff
@@ -665,6 +825,24 @@ module.exports = class bybit extends Exchange {
         return this.milliseconds () - this.options['timeDifference'];
     }
 
+    async isUnifiedMarginEnabled (params = {}) {
+        const enableUnifiedMargin = this.safeValue (this.options, 'enableUnifiedMargin');
+        if (enableUnifiedMargin === undefined) {
+            const response = await this.privateGetUserV3PrivateQueryApi (params);
```
Comment (carlosmiei) [inline js/bybit.js:831]: @sc0Vu I'm not sure this is working correctly my account is unified but this returns `false` because I receive this response:

```
result:
{id: '364993', note: 'ccxt', apiKey: 'pi0XyfFkvXN1nYCryc', readOnly: '0', secret: '', …}
retCode:
'0'
retExtInfo:
null
retMsg:
'OK'
time:
'1669716906592'
```

File: js/bybit.js [hunk 32]
```diff
@@ -665,6 +825,24 @@ module.exports = class bybit extends Exchange {
...
+            this.options['enableUnifiedMargin'] = this.safeInteger (permissions, 'unified') === 0;
+        }
+        return this.options['enableUnifiedMargin'];
+    }
+
+    async upgradeUnifiedAccount (params = {}) {
+        // warning this method can only be called once
+        // it is not reverseable and you will be stuck with a unified margin account
+        // you also need at least 5000 USDT in your bybit account to do this
+        return await this.privatePostUnifiedV3PrivateAccountUpgradeUnifiedAccount (params);
```
Comment (carlosmiei) [inline js/bybit.js:843]: @sc0Vu  user won't see this warning by default, so I'd suggest doing something similar to `createMarketBuyRequiresPric` here, i.e, throw an exception by default warning the user and that exception can be disabled in the options

File: js/bybit.js [hunk 33]
```diff
@@ -4265,93 +4890,224 @@ module.exports = class bybit extends Exchange {
         //         "time": "1666768215157"
         //     }
         //
+        const result = this.safeValue (response, 'result', {});
+        const trades = this.safeValue (result, 'list', []);
+        return this.parseTrades (trades, market, since, limit);
+    }
+
+    async fetchMyDerivativesTrades (symbol = undefined, since = undefined, limit = undefined, params = {}) {
```
Comment (carlosmiei) [inline js/bybit.js:4898]: this name seems ambiguous, can we change it to something like `fetchMyUnifiedTrades` or `fetchMyUnifiedDerivativeTrades` ?

File: js/bybit.js [hunk 34]
```diff
@@ -4265,93 +4890,224 @@ module.exports = class bybit extends Exchange {
...
+            // 'category': ''
+            // 'limit' 20, // max 50
+        };
+        if (since !== undefined) {
+            request['startTime'] = since;
+        }
+        if (limit !== undefined) {
+            request['limit'] = limit; // default 20, max 50
+        }
+        const response = await this.privateGetUnifiedV3PrivateExecutionList (this.extend (request, params));
```
Comment (carlosmiei) [inline js/bybit.js:4918]: Hum this is not working:
image

I think we're missing the `category` 
image

File: js/bybit.js [hunk 35]
```diff
@@ -3166,6 +3480,189 @@ module.exports = class bybit extends Exchange {
...
+        } else if (timeInForce === 'ioc') {
+            request['timeInForce'] = 'ImmediateOrCancel';
+        }
+        const triggerPrice = this.safeValue2 (params, 'stopPrice', 'triggerPrice');
+        const stopLossPrice = this.safeValue (params, 'stopLossPrice', triggerPrice);
+        const isStopLossOrder = stopLossPrice !== undefined;
+        const takeProfitPrice = this.safeValue (params, 'takeProfitPrice');
+        const isTakeProfitOrder = takeProfitPrice !== undefined;
+        const isStopOrder = isStopLossOrder || isTakeProfitOrder;
+        if (isStopOrder) {
```
Comment (carlosmiei) [inline js/bybit.js:3543]: @sc0Vu same comment here, these are not mutex, we can have sl+tp+sp simultaneously

File: js/bybit.js [hunk 36]
```diff
@@ -2987,9 +3316,6 @@ module.exports = class bybit extends Exchange {
         }
         let type = undefined;
         [ type, params ] = this.handleMarketTypeAndParams ('fetchOrder', market, params);
```
Comment (carlosmiei) [inline js/bybit.js:3318]: @sc0Vu aren't we missing the `unifiedMargin`check inside `fetchOrder` ?

File: js/bybit.js [hunk 37]
```diff
@@ -3825,170 +4385,115 @@ module.exports = class bybit extends Exchange {
...
+         * @name bybit#fetchOrders
+         * @description fetches information on multiple orders made by the user
+         * @param {string} symbol unified market symbol of the market orders were made in
          * @param {int|undefined} since the earliest time in ms to fetch orders for
          * @param {int|undefined} limit the maximum number of  orde structures to retrieve
          * @param {object} params extra parameters specific to the bybit api endpoint
          * @returns {[object]} a list of [order structures]{@link https://docs.ccxt.com/en/latest/manual.html#order-structure}
          */
         await this.loadMarkets ();
         let market = undefined;
```
Comment (carlosmiei) [inline js/bybit.js:4460]: `fetchClosedOrders`consistently returns `System Error` so I think it might be related to our code

```
Node.js: v17.9.0
CCXT v2.2.35
bybit.fetchClosedOrders (BTC/USDT:USDT, , 1)
ExchangeError bybit {"retCode":10016,"retMsg":"System error. Please try again later.","result":{},"retExtInfo":{},"time":1669718855914}
---------------------------------------------------
[ExchangeError] bybit {"retCode":10016,"retMsg":"System error. Please try again later.","result":{},"retExtInfo":{},"time":1669718855914}

    at throwExactlyMatchedException  js/base/Exchange.js:2257              throw new exact[string] (message);                                              
    at handleErrors                  js/bybit.js:7140                      this.throwExactlyMatchedException (this.exceptions['exact'], errorCode, feedbac…
    at                               js/base/Exchange.js:598               const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
    at processTicksAndRejections     node:internal/process/task_queues:96                                                                                  
    at async timeout                 js/base/functions/time.js:181         return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
    at fetch2                        js/base/Exchange.js:1901              return await this.fetch (request['url'], request['method'], request['headers'],…
    at request                       js/base/Exchange.js:1905              return await this.fetch2 (path, api, method, params, headers, body, config, con…
    at fetchUnifiedMarginOrders      js/bybit.js:4321                      const response = await this.privateGetUnifiedV3PrivateOrderList (this.extend (r…
    at fetchOrders                   js/bybit.js:4473                      return await this.fetchUnifiedMarginOrders (symbol, since, limit, params);      
    at fetchClosedOrders             js/bybit.js:4559                      return await this.fetchOrders (symbol, since, limit, this.extend (request, para…

bybit {"retCode":10016,"retMsg":"System error. Please try again later.","result":{},"retExtInfo":{},"time":1669718855914}
```

File: js/bybit.js [hunk 38]
```diff
@@ -6143,4 +7315,112 @@ module.exports = class bybit extends Exchange {
...
+        let fees = this.safeValue (response, 'result', {});
+        fees = this.safeValue (fees, 'list', []);
+        const result = {};
+        for (let i = 0; i < fees.length; i++) {
+            const fee = this.parseTradingFee (fees[i]);
+            const symbol = fee['symbol'];
+            result[symbol] = fee;
+        }
+        return result;
+    }
```
Comment (carlosmiei) [inline js/bybit.js:7425]: @sc0Vu currently inside `sign`, we set ` headers['Referer'] = brokerId;` in multiple places, which is messy, can we dry it and centralize its manipulation? 
Like at the beginning or the end:

```Javascript
if (POST) {
                    const brokerId = this.safeString (this.options, 'brokerId');
                    if (brokerId !== undefined) {
                        headers['Referer'] = brokerId;
                    }
}

File: js/bybit.js (hunk 30 above)
Comment (sc0Vu) [reply js/bybit.js:53]: Do you mean this one: https://github.com/ccxt/ccxt/blob/bd63662db44909783b7e5ee0fc9e73e3ecdbc706/js/bybit.js#L5330 ?

File: js/bybit.js (hunk 32 above)
Comment (sc0Vu) [reply js/bybit.js:843]: @carlosmiei do you want to check account balance of user?

Comment (carlosmiei) [reply js/bybit.js:843]: @sc0Vu nop, just a simple warning stating this action is irreversible (you can add the 5k info too) so that users won't enable it accidentally

File: js/bybit.js (hunk 33 above)
Comment (sc0Vu) [reply js/bybit.js:4898]: How about we use `fetchMyUnifiedMarginTrades`? Maybe we can also change `fetchMyContractTrades` to `fetchMyDerivativesTrades`.

Comment (carlosmiei) [reply js/bybit.js:4898]: @sc0Vu sounds good to me

File: js/bybit.js (hunk 36 above)
Comment (sc0Vu) [reply js/bybit.js:3318]: How do you think call `fetchOrders` directly?

File: js/bybit.js (hunk 37 above)
Comment (sc0Vu) [reply js/bybit.js:4460]: They only accept single status, shall we add another status in params?

File: js/bybit.js (hunk 38 above)
Comment (sc0Vu) [reply js/bybit.js:7425]: Looks like we only add this when trade in derivatives market. Do we want to send this in other market?

Comment (carlosmiei) [reply js/bybit.js:7472]: @sc0Vu Yeah I think it does not hurt send it in every POST

File: js/bybit.js (hunk 37 above)
Comment (sc0Vu) [reply js/bybit.js:4496]: @carlosmiei closed orders mean the status is either filled or cancelled. I only use cancelled in unified margin, just wondering we can add status in params ('{"status":"Filled"}')

Comment (carlosmiei) [reply js/bybit.js:4498]: @sc0Vu obviously, we have to return both (closed and filled) otherwise it's an incomplete `fetchClosedOrders` implementation, but will adding the other status in params work? I'm not sure I understood tbh

File: js/bybit.js (hunk 36 above)
Comment (carlosmiei) [reply js/bybit.js:3351]: @sc0Vu Yeah I think we can do that by providing the `orderId`

File: js/bybit.js [hunk 39]
```diff
@@ -2198,8 +2533,8 @@ module.exports = class bybit extends Exchange {
             'timestamp': timestamp,
             'datetime': this.iso8601 (timestamp),
             'symbol': symbol,
-            'order': this.safeString2 (trade, 'order_id', 'orderId'),
-            'type': this.safeStringLower (trade, 'order_type'),
+            'order': this.safeString (trade, 'orderId'),
+            'type': this.safeStringLower (trade, 'orderType'),
```
Comment (carlosmiei) [inline js/bybit.js:2537]: @sc0Vu bybit returns `unknown` for the order type, I think we should set it undefined in these cases: 
image

File: js/bybit.js (hunk 30 above)
Comment (carlosmiei) [reply js/bybit.js:53]: @sc0Vu sorry I pasted the wrong link, I meant this one: https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_walletrecords

File: js/bybit.js [hunk 40]
```diff
@@ -665,6 +826,56 @@ module.exports = class bybit extends Exchange {
...
+            //
+            const result = this.safeValue (response, 'result', {});
+            this.options['enableUnifiedMargin'] = this.safeInteger (result, 'unified') === 1;
+        }
+        return this.options['enableUnifiedMargin'];
+    }
+
+    async upgradeUnifiedAccount (params = {}) {
+        const createUnifiedMarginAccount = this.safeValue (this.options, 'createUnifiedMarginAccount');
+        if (!createUnifiedMarginAccount) {
```
Comment (carlosmiei) [inline js/bybit.js:873]: @sc0Vu we have to add here "If you want to disable this warning set `exchange.options["createUnifiedMarginAccount"]=true;`
