### PR TITLE
fixes #17508

### LINKED ISSUE #17508: okx withdraw is broken
### Operating System

macOS

### Programming Languages

JS

### CCXT Version

3.0.56

### Description

Calling withdraw for USDT over MATIC throws error:
okx {"code":"51000","data":[],"msg":"Parameter chainName  error"}

### Code

```
  

```

### PR DESCRIPTION
**Pull request by dmatora**

### CODE REVIEW

File: dist/cjs/src/okx.js [hunk 1]
```diff
@@ -3863,7 +3863,7 @@ class okx extends okx$1 {
             'amt': this.numberToString(amount),
         };
         const networks = this.safeValue(this.options, 'networks', {});
-        let network = this.safeStringUpper(params, 'network'); // this line allows the user to specify either ERC20 or ETH
+        let network = this.safeString(params, 'network'); // this line allows the user to specify either ERC20 or ETH
```
Comment (carlosmiei) [inline dist/cjs/src/okx.js:3866]: @dmatora You don't need to commit this file, but don't worry I will revert it this time

Comment (dmatora) [reply dist/cjs/src/okx.js:3866]: @carlosmiei thanks

File: js/src/okx.js [hunk 2]
```diff
@@ -3866,7 +3866,7 @@ export default class okx extends Exchange {
             'amt': this.numberToString(amount),
         };
         const networks = this.safeValue(this.options, 'networks', {});
-        let network = this.safeStringUpper(params, 'network'); // this line allows the user to specify either ERC20 or ETH
+        let network = this.safeString(params, 'network'); // this line allows the user to specify either ERC20 or ETH
```
Comment (carlosmiei) [inline js/src/okx.js:3869]: @dmatora also, we should apply the fixes on the TS version now

**Review by carlosmiei — APPROVED** [review]
