### PR TITLE
bybit - v1 update to v3

### LINKED ISSUE #15345: exchange.transfer is not working with on bybit exchange
Transfering funds from "spot" to "funding" accounts works fine on binance exchange, but not with bybit.
Maybe I'm missing some arguments in my request ?

- OS: Win 10 x64
- Programming Language version: Node.js 18
- CCXT version: 2.0.25

```
// Transfering 2 USDT from spot to funding
exchange.transfer('USDT', 2, 'spot', 'funding')
```

```
BadRequest: bybit {"ret_code":10001,"ret_msg":"invalid parameter","ext_code":"","result":null,"ext_info":null,"time_now":1666163282207}
    at bybit.throwExactlyMatchedException (/home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:2142:19)
    at bybit.handleErrors (/home/user/www/nodeccxt/node_modules/ccxt/js/bybit.js:5420:18)
    at /home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/home/user/www/nodeccxt/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bybit.fetch2 (/home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:1803:16)
    at async bybit.request (/home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:1807:16)
    at async bybit.transfer (/home/user/www/nodeccxt/node_modules/ccxt/js/bybit.js:5064:26)
    at async withdrawToWallet (/home/user/www/nodeccxt/src/testing.js:32:3)
    at async start (/home/user/www/nodeccxt/src/testing.js:21:3) {
  constructor: [class BadRequest extends ExchangeError]
}
```

### PR DESCRIPTION
**Pull request by ttodua**
updated  spot [v1](https://bybit-exchange.github.io/docs/spot/v1/#t-balance) endpoints to [v3](https://bybit-exchange.github.io/docs/spot/v3/#t-balance)

(edit: unfortunately, even though I've updated api version to v3 endpoints, 'trigger' orders are still unavailable through API as [their support says](https://t.me/BybitAPI/129755))

_[fix #15345]_

### CODE REVIEW

File: js/bybit.js [hunk 1]
```diff
@@ -1493,22 +1540,53 @@ module.exports = class bybit extends Exchange {
...
+        if (this.isArray (result)) {
+            const tickers = {};
+            for (let i = 0; i < result.length; i++) {
+                const ticker = this.parseTicker (result[i]);
+                const symbol = ticker['symbol'];
+                tickers[symbol] = ticker;
+            }
+            return this.filterByArray (tickers, 'symbol', symbols);
+        } else {
+            const list = this.safeValue (result, 'list', []);
```
Comment (carlosmiei) [inline js/bybit.js:1587]: you can't use `list` as an identifier name because it confuses our transpiler that's why the build is broken

Comment (ttodua) [reply js/bybit.js]: yeah, I've not yet looked at builds, because PR was not ready till now (my bad, i havent marked it draft when opened the PR).
Now, the PR is complete.

**Comment by ttodua** [comment]
Note, private tests will fail for php, as this PR is still unmerged: https://github.com/ccxt/ccxt/pull/14268

**Comment by frosty00** [comment]
how does this relate to #15210

**Comment by ttodua** [comment]
> how does this relate to #15210

where is it mentioned that it's directly related to #15210?  my PR doesn't touch unified account updates, this only touches spot v1 to v3, nothing else much

File: js/bybit.js [hunk 2]
```diff
@@ -4000,36 +4314,69 @@ module.exports = class bybit extends Exchange {
...
+            const network = this.safeString (networks, rawNetwork, rawNetwork);
+            params = this.omit (params, 'network');
+            const response = await this.fetchDepositAddressesByNetwork (code, query);
+            let result = undefined;
+            if (network === undefined) {
+                result = this.safeValue (response, code);
                 if (result === undefined) {
-                    const defaultNetwork = this.safeString (this.options, 'defaultNetwork', 'ERC20');
-                    result = this.safeValue (response, defaultNetwork);
+                    const alias = this.safeString (networks, code, code);
```
Comment (carlosmiei) [inline js/bybit.js:4358]: 4 nested ifs it's just bad practice and makes the code hard to read, are you sure we can't replace this with a loop or something?

File: js/bybit.js [hunk 3]
```diff
@@ -2420,7 +2573,38 @@ module.exports = class bybit extends Exchange {
 
     parseOrder (order, market = undefined) {
```
Comment (carlosmiei) [inline js/bybit.js:2574]: @ttodua changes inside shared parsers (parseOrder, parseTrade, etc) will definitely clash with @sc0Vu PR. Since you're upgrading spot only, can you please create a dedicated parser for it? in the end spot and derivative structures are different, so in short, would be something like this:

```Javascript
// current implementation stays as is because will be modified in a different PR
parseOrder(order,market) {
}

// new parser that will handle v3 spot upgrade
parseSpotOrder() {

}
```

what do you think?

File: js/bybit.js (hunk 2 above)
Comment (ttodua) [reply js/bybit.js:4358]: Well, if you look at that method, I've not added those nested if/else in this PR, and I've just added only 1 `if` in the top. so, if possible to ignore this fact atm, because of the complexity of the merge of this PR, let's put that if/else nesting problem aside, and after my & peter's PRs are merged, I'll then make reorganize of this part. Does that sound ok?

File: js/bybit.js (hunk 3 above)
Comment (ttodua) [reply js/bybit.js:2574]: done.

File: js/bybit.js [hunk 4]
```diff
@@ -2676,6 +2812,90 @@ module.exports = class bybit extends Exchange {
         }, market);
     }
 
+    parseSpotOrder (order, market = undefined) {
```
Comment (carlosmiei) [inline js/bybit.js:2815]: @ttodua I noticed this is the only parser you split, so is it safe to assume that the conflicts in the other ones are going to be minimal?

File: js/bybit.js [hunk 5]
```diff
@@ -2623,7 +2761,7 @@ module.exports = class bybit extends Exchange {
         } else if (lastTradeTimestamp === undefined) {
             lastTradeTimestamp = this.parse8601 (this.safeStringN (order, [ 'updated_time', 'updated_at', 'update_time' ]));
             if (lastTradeTimestamp === undefined) {
-                lastTradeTimestamp = this.safeNumber (order, 'updateTime');
+                lastTradeTimestamp = this.safeNumber (order, 'updateTime'); // todo: trade udpate time is different than update order time
```
Comment (carlosmiei) [inline js/bybit.js:2764]: in that case should we remove it?

File: js/bybit.js [hunk 6]
```diff
@@ -3215,7 +3473,7 @@ module.exports = class bybit extends Exchange {
          * @returns {object} An [order structure]{@link https://docs.ccxt.com/en/latest/manual.html#order-structure}
          */
         if (symbol === undefined) {
-            throw new ArgumentsRequired (this.id + ' cancelOrder() requires a symbol argument');
+            throw new ArgumentsRequired (this.id + ' cancelOrder() requires a symbol argument'); // todo: spot doesnt need symbol
```
Comment (carlosmiei) [inline js/bybit.js:3476]: missing yet?

File: js/bybit.js [hunk 7]
```diff
@@ -5133,38 +5525,48 @@ module.exports = class bybit extends Exchange {
...
-        const request = {
-            'transfer_id': transferId,
-            'from_account_type': fromId,
-            'to_account_type': toId,
-            'coin': currency['id'],
-            'amount': amountToPrecision,
-        };
-        const response = await this.privatePostAssetV1PrivateTransfer (this.extend (request, params));
+        let method = undefined;
+        [ method, params ] = this.handleOptionAndParams (params, 'transfer', 'method', 'privatePostAssetV1PrivateTransfer'); // v1 preferred atm, because it supports funding
```
Comment (carlosmiei) [inline js/bybit.js:5529]: ok in this case we should require `method` inside params, and also allow setting it inside options 

```Javascript
options: {
     transfer: {
               method: 
      }
}

File: js/bybit.js [hunk 8]
```diff
@@ -2782,20 +3033,20 @@ module.exports = class bybit extends Exchange {
...
-            'qty': this.amountToPrecision (symbol, amount),
+            'orderQty': this.amountToPrecision (symbol, amount),
             // 'orderLinkId': 'string', // unique client order id, max 36 characters
         };
         if ((upperCaseType === 'LIMIT') || (upperCaseType === 'LIMIT_MAKER')) {
             if (price === undefined) {
                 throw new InvalidOrder (this.id + ' createOrder requires a price argument for a ' + type + ' order');
             }
-            request['price'] = parseFloat (this.priceToPrecision (symbol, price));
+            request['orderPrice'] = parseFloat (this.priceToPrecision (symbol, price));
```
Comment (carlosmiei) [inline js/bybit.js:3045]: image
does it work with strings as documented?

File: js/bybit.js (hunk 4 above)
Comment (ttodua) [reply js/bybit.js:2877]: you are right, I incorrectly misunderstood you older comment and had just done parseOrder dissection. Now I am doing all other parsers too.

File: js/bybit.js (hunk 8 above)
Comment (ttodua) [reply js/bybit.js:3142]: As I remember, I have tested all those methods before pushing, but anyway, I've amended that to string now and re-tested and works with strings as API doc says.

File: js/bybit.js (hunk 5 above)
Comment (ttodua) [reply js/bybit.js:2867]: I wouldnt touch that in this current PR, as it's a different aspect, whether exchange's API engine emits 'updateTime' changes whenever there is trade too, so it might be right in some cases but might be wrong in some cases. however, I'll not touch it in this PR. just made a note for future edits.

File: js/bybit.js [hunk 9]
```diff
@@ -2892,10 +3150,10 @@ module.exports = class bybit extends Exchange {
                 request['orderFilter'] = 'StopOrder';
                 request['trigger_by'] = 'LastPrice';
                 const stopPx = isStopLossOrder ? stopLossPrice : takeProfitPrice;
-                const preciseStopPrice = this.priceToPrecision (symbol, stopPx);
-                request['triggerPrice'] = preciseStopPrice;
+                const preciseTriggerPrice = this.priceToPrecision (symbol, stopPx);
```
[the remark this answers is not in the document]
Comment (ttodua) [reply js/bybit.js:3250]: Yes, you're right!

File: js/bybit.js (hunk 4 above)
Comment (carlosmiei) [reply js/bybit.js:2918]: @ttodua only the ones you feel necessary pls

File: js/bybit.js (hunk 7 above)
Comment (ttodua) [reply js/bybit.js:5626]: may I ask for more clarification? `handleOptionAndParams` does what you say in the backgrounds. Do I miss smth?

Comment (carlosmiei) [reply js/bybit.js:5617]: @ttodua yeah sorry I misread it 😅 , did not notice you were using handleOptionAndparams already

**Comment by ttodua** [comment]
I've updated `fetchDepositAddress` , so it works with any combination as expected:

```
    let a1 = await e.fetchDepositAddress('SHIB', {network: 'ETH'});
    let a2 = await e.fetchDepositAddress('SHIB', {network: 'ERC20'});
    let a3 = await e.fetchDepositAddress('SHIB', {network: 'ZZZZ'}); // throws exception
    let a4 = await e.fetchDepositAddress('SHIB');
    let a6 = await e.fetchDepositAddress('USDT', {network: 'ETH'});
    let a7 = await e.fetchDepositAddress('USDT', {network: 'ERC20'});
    let a8 = await e.fetchDepositAddress('USDT', {network: 'TRC20'});
    let a9 = await e.fetchDepositAddress('USDT');
```

File: js/bybit.js [hunk 10]
```diff
@@ -600,6 +629,17 @@ module.exports = class bybit extends Exchange {
                     'OMNI': 'OMNI',
                     'SPL': 'SOL',
                 },
+                'networksById': {
```
Comment (carlosmiei) [inline js/bybit.js:632]: @ttodua isn't this usually called `reverseNetworks` ?

File: js/bybit.js [hunk 11]
```diff
@@ -3215,7 +3579,11 @@ module.exports = class bybit extends Exchange {
...
         if (symbol === undefined) {
-            throw new ArgumentsRequired (this.id + ' cancelOrder() requires a symbol argument');
+            let type = undefined;
+            [ type, params ] = this.handleMarketTypeAndParams ('cancelOrder', undefined, params);
+            if (type !== 'spot') {
+                throw new ArgumentsRequired (this.id + ' cancelOrder() requires a symbol argument');
+            }
         }
         await this.loadMarkets ();
         const market = this.market (symbol);
```
Comment (carlosmiei) [inline js/bybit.js:3589]: @ttodua this logic isn't right, if you don't provide any symbol in the spot mode, will crash here

If symbol is not required for spot orders, so we can only `this.market (symbol);` if the users provide a symbol

File: js/bybit.js [hunk 12]
```diff
@@ -1853,15 +2049,87 @@ module.exports = class bybit extends Exchange {
...
+            takerOrMaker = isMaker === 1 ? 'maker' : 'taker';
+            side = isBuyer === 1 ? 'buy' : 'sell';
+        }
+        const marketId = this.safeString (trade, 'symbol');
+        market = this.safeMarket (marketId, market);
+        let fee = {};
+        const feeToken = this.safeString (trade, 'feeTokenId');
+        if (feeToken !== undefined) {
+            const feeCurrency = this.safeCurrencyCode (feeToken);
+            const feeCost = this.safeNumber (trade, 'execFee');
```
Comment (carlosmiei) [inline js/bybit.js:2109]: this is crashing as well, I think we must parse it as a string here
image

File: js/bybit.js [hunk 13]
```diff
@@ -466,6 +492,8 @@ module.exports = class bybit extends Exchange {
                     '10017': BadRequest, // request path not found or request method is invalid
                     '10018': RateLimitExceeded, // exceed ip rate limit
                     '10020': PermissionDenied, // {"retCode":10020,"retMsg":"your account is not a unified margin account, please update your account","result":null,"retExtInfo":null,"time":1664783731123}
+                    '12201': BadRequest, // {"retCode":12201,"retMsg":"Invalid orderCategory parameter.","result":{},"retExtInfo":null,"time":1666699391220}
```
Comment (carlosmiei) [inline js/bybit.js:495]: can we add this exception as well?

`ccxt.base.errors.ExchangeError: bybit {"retCode":5004,"retMsg":"Server Timeout","result":null,"retExtInfo":{},"time":1667577060106}`

File: js/bybit.js (hunk 4 above)
Comment (ttodua) [reply js/bybit.js:2928]: > @ttodua only the ones you feel necessary pls

yes, actually I think with multi-market exchanges, the separation of parsers is very efficient - in terms of readability and possible theoretical performance (avoiding tons of extra `this.safe...` checks).

File: js/bybit.js (hunk 10 above)
Comment (ttodua) [reply js/bybit.js:632]: > `reverseNetworks`

No, `reverseNetworks` is not same, moreover it's almost nowhere used - only in binance & tokocrypto (which is based on  purely binance-class almost) and they contain different data. (additionally, mistakenly someone applied 'reverseNetworks' also in wavesexchange).  

in all other exchanges, if you search for word `networksById` you will find out that is exactly what I refer too, the difference is that in all other exchanges `networksById` variable is hardcoded, while I mentioned on discord that 'hardcoded' approach is not ideal and we should move them in `networksById` field under options, the next sibling where to `networks` key. 

additional note, `networksById` is not just reversed key-values of `networks` object, because `networks` values have many-to-one relation, for example it might be such (let's say 'Ethereum' and 'TronNetwork' are exchange-specific slugs for chains used in withdrawal/deposit network actions):
```
'networks': {
    'ERC20': 'Ethereum',
    'ETH': 'Ethereum',
    'TRX': 'TronNetwork',
    'TRON': 'TronNetwork',
    'TRC20': 'TronNetwork',
    ...
}
```

however, `networksById` variable (as you see across exchange implementations) is reversed, but with one-to-one relation. (and I see that CCXT has one chosen name for each popular network, for example, `TRC20` seems the chosen core networkCode for tron, `ERC20` for ethereum...)

File: js/bybit.js (hunk 11 above)
Comment (ttodua) [reply js/bybit.js]: Ah, good catch. the logic needed deeper edits. I've updated, and take a look, if it seems 'sketchy' let me know. (however I dont see other way, if we want to maintain that flexibility so user was able to skip the symbol )

File: js/bybit.js [hunk 14]
```diff
@@ -3685,22 +4094,52 @@ module.exports = class bybit extends Exchange {
                 method = isConditional ? 'privateGetV2PrivateStopOrder' : 'privateGetV2PrivateOrder';
             }
         } else if (type === 'spot') {
-            method = 'privateGetSpotV1OpenOrders';
+            request['symbol'] = market['id'];
```
[the remark this answers is not in the document]
Comment (ttodua) [reply js/bybit.js]: fixed! 👍

File: js/bybit.js (hunk 12 above)
Comment (ttodua) [reply js/bybit.js]: uh oh. when i ran private tests, this was not caught. fixed !

File: js/bybit.js [hunk 15]
```diff
@@ -5133,38 +5630,47 @@ module.exports = class bybit extends Exchange {
...
         const amountToPrecision = this.currencyToPrecision (code, amount);
-        const request = {
-            'transfer_id': transferId,
-            'from_account_type': fromId,
-            'to_account_type': toId,
-            'coin': currency['id'],
-            'amount': amountToPrecision,
-        };
-        const response = await this.privatePostAssetV1PrivateTransfer (this.extend (request, params));
+        let method = undefined;
```
Comment (carlosmiei) [inline js/bybit.js:5633]: @ttodua We're missing a couple of things here (correct link, camelCase params instead of snake_case), can you please check @Dan-krm's PR and apply the same changes here? https://github.com/ccxt/ccxt/pull/15579/files#diff-cb8b530c783df8bccc6e0df910e7433b34c9c9c3cea8904fcf2c59f1e60aeebe

File: js/bybit.js [hunk 16]
```diff
@@ -3214,13 +3582,15 @@ module.exports = class bybit extends Exchange {
          * @param {object} params extra parameters specific to the bybit api endpoint
          * @returns {object} An [order structure]{@link https://docs.ccxt.com/en/latest/manual.html#order-structure}
          */
+        let marketType = undefined;
+        [ marketType, params ] = this.handleMarketTypeAndParams ('cancelOrder', undefined, params);
```
[the remark this answers is not in the document]
Comment (ttodua) [reply js/bybit.js]: done

File: js/bybit.js (hunk 15 above)
Comment (ttodua) [reply js/bybit.js:5635]: I've accommodated all changes from @Dan's PR and corrected/updated those methods too.
I think after merge, i'll just edit some peripherical thins (i.e. links etc...), however, because of the priority, I don't want to hold this PR for some minor things.

File: js/bybit.js [hunk 17]
```diff
@@ -5117,54 +5616,65 @@ module.exports = class bybit extends Exchange {
...
+            request = {
+                'transferId': transferId,
+                'fromAccountType': fromId,
+                'toAccountType': toId,
+                'coin': currency['id'],
+                'amount': amountToPrecision,
+            };
+        } else {
+            request = {
+                'transferId': transferId,
```
Comment (carlosmiei) [inline js/bybit.js:5648]: it should be `transfer_id` here right?

File: js/bybit.js [hunk 18]
```diff
@@ -5117,54 +5616,65 @@ module.exports = class bybit extends Exchange {
          * @method
          * @name bybit#transfer
          * @description transfer currency internally between wallets on the same account
-         * @see https://bybit-exchange.github.io/docs/account_asset/#t-createinternaltransfer
+         * @see https://bybit-exchange.github.io/docs/account_asset/v3/#t-createinternaltransfer
```
Comment (carlosmiei) [inline js/bybit.js:5619]: since we're using both methods here (v1, v3) I think we should keep both links

Comment (ttodua) [reply js/bybit.js:5619]: ok

File: js/bybit.js (hunk 17 above)
Comment (ttodua) [reply js/bybit.js]: good catch, copy-pasted codes several times, and that become broken accidentaly. fixed.

**Comment by carlosmiei** [comment]
LGTM ✅ 
[bybitv3SpotTests.txt](https://github.com/ccxt/ccxt/files/9970227/bybitv3SpotTests.txt)

**Review by carlosmiei — APPROVED** [review]
