### PR TITLE
fix(okx): fetchohlcv

### LINKED ISSUE #25679: okx| binance | bitget fetchOHLCV returns incorrect data
### Operating System

_No response_

### Programming Languages

JavaScript

### CCXT Version

4.4.73

### Description

When I requested OKX and Binance data, the first data returned when I set limt=1000 was not the start time I set, but the first data returned when I set limt=100 was correct.
The test was normal when requesting bybit

Image

Image

### Code

```
 
import { HttpsProxyAgent } from "https-proxy-agent";
import ccxt from "ccxt";

const exchange = new ccxt.okx({
  agent: new HttpsProxyAgent("http://127.0.0.1:1087") 
})

const startTime = 1737244800000
console.log(startTime)
exchange.fetchOHLCV("BTC/USDT", "1h", startTime, 1000).then((data) => {
  console.log(data[0][0])
}) 

```

### PR DESCRIPTION
**Pull request by ttodua**
fix #25679

now it correctly returns:
```
const startTime = 1737244800000
e.fetchOHLCV("BTC/USDT", "1h", startTime, 1000).then((data) => {
    console.log(`${e.id} first bar with 1000 limit: ` + data[0][0])
})
```
>
`okx first bar with 1000 limit: 1737244800000`

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua can you check the static tests?

**Comment by ttodua** [comment]
@carlosmiei passes now

File: ts/src/okx.ts [hunk 1]
```diff
@@ -2417,6 +2418,8 @@ export default class okx extends Exchange {
         const timezone = this.safeString (options, 'timezone', 'UTC');
         if (limit === undefined) {
             limit = 100; // default 100, max 100
+        } else {
+            limit = Math.min (limit, 300); // max 100
```
Comment (sc0Vu) [inline ts/src/okx.ts:2422]: Just to clarify, is the maximum limit 100 or 300?

Comment (carlosmiei) [reply ts/src/okx.ts:2422]: image
for the regular endpoint 300, the historical 100
image
