### PR TITLE
fix(bitmex): fix #17313

### LINKED ISSUE #17313: watchOrderbook() bug on Bitmex
### Operating System

Debian

### Programming Languages

JS

### CCXT Version

3.0.29

### Description

The watchOrderbook() function is not working correctly on Bitmex, but it works fine on Binance USDM and Bybit. The issue seems to be that the orderbook cache doesn't remove a record when it gets filled or cancelled.

Here's an example of the behavior of the best ask/bid:
[ 27433, 5300, '8797256700' ] [ 27429.5, 6000, '8797257050' ]
[ 27428, 3600, '8797257200' ] [ 27429.5, 6000, '8797257050' ]
[ 27427, 3600, '8797257300' ] [ 27429.5, 6000, '8797257050' ]
[ 27423, 7000, '8797257700' ] [ 27429.5, 6000, '8797257050' ]

As you can see, the "best ask" is decreasing as the new lower price is received, while the "best bid" stays the same since the received price is higher than the one already saved in memory. If the price were rising, it would be the opposite.

I only observed this issue recently on Bitmex.

### Code

```
const ccxt=require('ccxt').pro

const api=new ccxt.bitmex()
run()

async function run() {
    while (true) {
        try {
            const orderbook = await api.watchOrderBook('BTC/USD:BTC')
            console.log(orderbook['asks'][0], orderbook['bids'][0])
        } catch (e) {
            console.log(e)
        }
    }
}

```

### PR DESCRIPTION
**Pull request by pcriadoperez**
Bitmex did an update where a new message with the action delete was added. This PR does the change to take it into account.
- Fix #17313 
- Add missing timestamp and symbol field

### CODE REVIEW

**Comment by pcriadoperez** [comment]
```python
2023-03-26T23:46:27.961Z message {"table":"orderBookL2","action":"delete","data":[{"symbol":"ETH_USDT","id":85499965976,"side":"Buy","size":42000000,"price":1701.2,"timestamp":"2023-03-26T23:46:27.829Z"}]}
{'asks': [[1782.45, 398000000.0, '85499964351'], [1782.5, 42000000.0, '85499964350'], [1888.0, 202000000.0, '85499962240'], [1901.95, 31122000000.0, '85499961961'], [1902.0, 36000000.0, '85499961960'], [1985.6, 300000000.0, '85499960288'], [1987.0, 9567000000.0, '85499960260'], [1990.0, 12000000.0, '85499960200'], [2000.0, 200000000.0, '85499960000'], [2100.0, 324000000.0, '85499958000'], [2150.0, 47000000.0, '85499957000'], [2200.0, 68000000.0, '85499956000'], [2250.0, 89000000.0, '85499955000'], [2280.0, 300000000.0, '85499954400'], [2300.0, 733000000.0, '85499954000'], [2350.0, 149000000.0, '85499953000'], [2400.0, 1667000000.0, '85499952000'], [2450.0, 184000000.0, '85499951000'], [2500.0, 200000000.0, '85499950000'], [8000.0, 500000000.0, '85499840000'], [8888.0, 164000000.0, '85499822240'], [88888.0, 167000000.0, '85498222240']],
 'bids': [[1701.3, 42000000.0, '85499965974'], [1701.25, 852000000.0, '85499965975'], [1700.0, 100000000.0, '85499966000'], [1606.65, 154000000.0, '85499967867'], [1600.0, 10000000.0, '85499968000'], [1550.0, 20000000.0, '85499969000'], [1518.0, 50000000.0, '85499969640'], [1510.0, 1000000.0, '85499969800'], [1500.0, 30000000.0, '85499970000'], [1470.0, 1000000.0, '85499970600'], [1450.0, 40000000.0, '85499971000'], [1400.0, 50000000.0, '85499972000'], [1350.0, 100000000.0, '85499973000'], [1300.0, 151000000.0, '85499974000'], [1250.0, 175000000.0, '85499975000'], [1200.0, 201000000.0, '85499976000'], [1100.0, 1000000.0, '85499978000'], [1000.0, 1000000.0, '85499980000'], [999.9, 100000000.0, '85499980002'], [999.8, 100000000.0, '85499980004'], [999.7, 100000000.0, '85499980006'], [999.6, 100000000.0, '85499980008'], [999.5, 100000000.0, '85499980010'], [999.4, 100000000.0, '85499980012'], [999.3, 100000000.0, '85499980014'], [999.2, 100000000.0, '85499980016'], [999.1, 100000000.0, '85499980018'], [999.0, 100000000.0, '85499980020'], [940.0, 45000000.0, '85499981200'], [920.0, 326000000.0, '85499981600'], [900.0, 56000000.0, '85499982000'], [867.0, 23000000.0, '85499982660'], [815.0, 1000000000.0, '85499983700'], [801.0, 1000000000.0, '85499983980'], [800.0, 1000000.0, '85499984000'], [751.0, 100000000.0, '85499984980'], [747.0, 30000000.0, '85499985060'], [726.0, 1000000000.0, '85499985480'], [701.0, 1000000000.0, '85499985980'], [700.0, 1000000.0, '85499986000'], [680.0, 102000000.0, '85499986400'], [600.0, 1001000000.0, '85499988000'], [589.0, 1000000000.0, '85499988220'], [500.0, 21000000.0, '85499990000'], [480.0, 20000000.0, '85499990400'], [470.0, 2000000.0, '85499990600'], [420.0, 763000000.0, '85499991600'], [400.0, 1000000.0, '85499992000'], [379.0, 17000000.0, '85499992420'], [356.0, 8000000000.0, '85499992880'], [350.0, 46070000000.0, '85499993000'], [300.0, 1000000.0, '85499994000'], [280.0, 63000000.0, '85499994400'], [200.0, 1000000.0, '85499996000'], [189.0, 28000000.0, '85499996220'], [175.0, 160000000.0, '85499996500'], [156.0, 3000000000.0, '85499996880'], [150.0, 333000000.0, '85499997000'], [135.0, 15000000000.0, '85499997300'], [122.0, 10000000000.0, '85499997560'], [100.0, 10000000.0, '85499998000'], [26.0, 25000000000.0, '85499999480'], [15.0, 4000000000.0, '85499999700'], [10.0, 2198000000.0, '85499999800'], [8.0, 1125000000.0, '85499999840'], [6.0, 833000000.0, '85499999880'], [5.05, 100000000000.0, '85499999899'], [5.0, 1071800000000.0, '85499999900'], [3.0, 4513000000.0, '85499999940'], [2.0, 717003000000.0, '85499999960'], [1.7, 4647000000.0, '85499999966'], [1.0, 1000000000.0, '85499999980'], [0.35, 10000000000.0, '85499999993'], [0.15, 6067000000.0, '85499999997'], [0.05, 40000000000.0, '85499999999']],
 'datetime': '2023-03-26T23:46:27.829Z',
 'nonce': None,
 'symbol': 'ETH_USDT',
 'timestamp': 1679874387829}
 ```

File: ts/src/pro/bitmex.ts [hunk 1]
```diff
@@ -1172,6 +1183,7 @@ export default class bitmex extends bitmexRest {
                 this.orderbooks[symbol] = this.indexedOrderBook ({}, 10);
             }
             const orderbook = this.orderbooks[symbol];
```
Comment (carlosmiei) [inline ts/src/pro/bitmex.ts:1185]: humm 
```
tmex watchOrderBook "BTC/USDT"                    
Python v3.10.9
CCXT v3.0.36
Traceback (most recent call last):
  File "/Users/cjg/Git/ccxt10/ccxt/examples/py/cli.py", line 232, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/cjg/Git/ccxt10/ccxt/examples/py/cli.py", line 197, in main
    await exchange.load_markets()
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/base/exchange.py", line 215, in load_markets
    raise e
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/base/exchange.py", line 211, in load_markets
    result = await self.markets_loading
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/base/exchange.py", line 201, in load_markets_helper
    markets = await self.fetch_markets(params)
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/bitmex.py", line 279, in fetch_markets
    response = await self.publicGetInstrumentActiveAndIndices(params)
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/base/exchange.py", line 1601, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/base/exchange.py", line 1597, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/bitmex.py", line 2642, in sign
    auth += expires
TypeError: can only concatenate str (not "int") to str
```

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p bitmex watchOrderBook "XBT_USDT"          
Python v3.10.9
CCXT v3.0.36
bitmex.watchOrderBook(XBT_USDT)
{'asks': [[27801.5, 53620000.0, '85399944397'], [27824.5, 790000.0, '85399944351'], [27825.0, 122170000.0, '85399944350'], [27826.5, 96090000.0, '85399944347'], [27835.0, 40670000.0, '85399944330'], [27837.5, 121380000.0, '85399944325'], [27923.5, 650580000.0, '85399944153'], [27970.5, 408830000.0, '85399944059'], [28082.0, 209470000.0, '85399943836'], [28132.0, 60000.0, '85399943736'], [28220.5, 10000.0, '85399943559'], [28221.0, 52080000.0, '85399943558'], [28222.0, 10000.0, '85399943556'], [28249.0, 100000.0, '85399943502'], [28336.5, 100000.0, '85399943327'], [28426.0, 120000.0, '85399943148'], [28500.0, 6580000.0, '85399943000'], [28700.0, 580000.0, '85399942600'], [28800.0, 25000000.0, '85399942400'], [28900.0, 29340000.0, '85399942200'], [29000.0, 25000000.0, '85399942000'], [29100.0, 25000000.0, '85399941800'], [29200.0, 50000000.0, '85399941600'], [29300.0, 26760000.0, '85399941400'], [29500.0, 9130000.0, '85399941000'], [29558.0, 2420000.0, '85399940884'], [29600.0, 6900000.0, '85399940800'], [29667.5, 50000000.0, '85399940665'], [29800.0, 25000000.0, '85399940400'], [30000.0, 18900000.0, '85399940000'], [30010.0, 820000.0, '85399939980'], [30012.0, 20000.0, '85399939976'], [30500.0, 3490000.0, '85399939000'], [30547.5, 50000000.0, '85399938905'], [30900.0, 16230000.0, '85399938200'], [31200.0, 50020000.0, '85399937600'], [31500.0, 630000.0, '85399937000'], [31600.0, 25000000.0, '85399936800'], [31700.0, 500000000.0, '85399936600'], [31800.0, 50000000.0, '85399936400'], [32000.0, 3350000.0, '85399936000'], [32254.5, 30000000.0, '85399935491'], [32400.0, 50000000.0, '85399935200'], [32499.0, 150000.0, '85399935002'], [32500.0, 770000.0, '85399935000'], [32600.0, 400000000.0, '85399934800'], [32800.0, 376800000.0, '85399934400'], [33000.0, 930000.0, '85399934000'], [33600.0, 280000.0, '85399932800'], [33800.0, 50000000.0, '85399932400'], [34000.0, 20000.0, '85399932000'], [36000.0, 20000.0, '85399928000'], [38000.0, 40000.0, '85399924000'], [40000.0, 20000.0, '85399920000'], [41111.0, 10000000.0, '85399917778'], [42000.0, 20000.0, '85399916000'], [42111.0, 2210000.0, '85399915778'], [46665.0, 4880000.0, '85399906670'], [47000.0, 310000.0, '85399906000'], [52000.0, 10000.0, '85399896000'], [55000.0, 20000.0, '85399890000'], [88888.0, 5590000.0, '85399822224'], [100000.0, 30000.0, '85399800000'], [150000.0, 30000.0, '85399700000'], [222222.0, 9790000.0, '85399555556'], [410000.0, 2260000.0, '85399180000'], [888888.0, 2640000.0, '85398222224']],
 'bids': [[27759.5, 790000.0, '85399944481'], [27759.0, 66620000.0, '85399944482'], [27746.0, 19610000.0, '85399944508'], [27745.5, 96950000.0, '85399944509'], [27744.5, 122170000.0, '85399944511'], [27722.5, 121380000.0, '85399944555'], [27651.0, 645130000.0, '85399944698'], [27638.5, 70000.0, '85399944723'], [27589.5, 409820000.0, '85399944821'], [27520.5, 10000.0, '85399944959'], [27423.0, 246100000.0, '85399945154'], [27407.5, 10000.0, '85399945185'], [27360.0, 157610000.0, '85399945280'], [27324.5, 20000.0, '85399945351'], [27217.5, 20000.0, '85399945565'], [27197.0, 50000.0, '85399945606'], [27127.5, 79500000.0, '85399945745'], [27000.0, 520000.0, '85399946000'], [26888.0, 30000.0, '85399946224'], [26837.0, 60000.0, '85399946326'], [26800.0, 300000.0, '85399946400'], [26781.0, 10000.0, '85399946438'], [26768.0, 970000.0, '85399946464'], [26726.0, 19200000.0, '85399946548'], [26710.5, 39770000.0, '85399946579'], [26700.0, 2000000.0, '85399946600'], [26666.0, 50000.0, '85399946668'], [26632.5, 10000.0, '85399946735'], [26600.0, 7520000.0, '85399946800'], [26500.0, 500000.0, '85399947000'], [26432.0, 41490000.0, '85399947136'], [26369.0, 190000.0, '85399947262'], [26321.0, 80000.0, '85399947358'], [26100.0, 3830000.0, '85399947800'], [26087.0, 80000.0, '85399947826'], [26080.5, 20000000.0, '85399947839'], [26000.0, 500000.0, '85399948000'], [25800.0, 25000000.0, '85399948400'], [25750.0, 290000.0, '85399948500'], [25700.0, 190000.0, '85399948600'], [25637.0, 30000.0, '85399948726'], [25590.0, 1990000.0, '85399948820'], [25580.5, 25000000.0, '85399948839'], [25500.0, 170000.0, '85399949000'], [25476.0, 80000.0, '85399949048'], [25452.0, 50000.0, '85399949096'], [25450.0, 2960000.0, '85399949100'], [25322.0, 10000.0, '85399949356'], [25300.0, 25000000.0, '85399949400'], [25241.5, 14500000.0, '85399949517'], [25207.0, 50000000.0, '85399949586'], [25087.0, 80000.0, '85399949826'], [25000.0, 300000.0, '85399950000'], [24950.0, 430000.0, '85399950100'], [24919.0, 39920000.0, '85399950162'], [24900.0, 5010000.0, '85399950200'], [24875.0, 70000.0, '85399950250'], [24847.0, 840000.0, '85399950306'], [24810.0, 1540000.0, '85399950380'], [24800.0, 25000000.0, '85399950400'], [24700.0, 200000.0, '85399950600'], [24573.5, 80000.0, '85399950853'], [24500.0, 200000.0, '85399951000'], [24225.5, 80000.0, '85399951549'], [24161.0, 60000.0, '85399951678'], [24047.0, 200000.0, '85399951906'], [24042.0, 60000.0, '85399951916'], [24012.0, 60000.0, '85399951976'], [24000.0, 510000.0, '85399952000'], [23907.0, 50000000.0, '85399952186'], [23700.0, 420000.0, '85399952600'], [23610.0, 500000.0, '85399952780'], [23564.0, 60000.0, '85399952872'], [23500.0, 640000.0, '85399953000'], [23372.0, 120000.0, '85399953256'], [23200.0, 3430000.0, '85399953600'], [23000.0, 740000.0, '85399954000'], [22807.0, 50000000.0, '85399954386'], [22643.0, 70000.0, '85399954714'], [22500.0, 670000.0, '85399955000'], [22134.0, 39500000.0, '85399955732'], [22024.5, 20000.0, '85399955951'], [22014.0, 30000.0, '85399955972'], [22000.0, 1000000.0, '85399956000'], [21993.0, 90000.0, '85399956014'], [21927.0, 80000.0, '85399956146'], [21885.0, 40000.0, '85399956230'], [21849.5, 10000.0, '85399956301'], [21771.0, 90000.0, '85399956458'], [21700.0, 460000.0, '85399956600'], [21500.0, 930000.0, '85399957000'], [21000.0, 1270000.0, '85399958000'], [20914.0, 80000.0, '85399958172'], [20550.0, 2000000.0, '85399958900'], [20500.0, 1220000.0, '85399959000'], [20300.0, 490000.0, '85399959400'], [20000.0, 1580000.0, '85399960000'], [19983.5, 150000.0, '85399960033'], [19974.5, 20000.0, '85399960051'], [19831.0, 80000.0, '85399960338'], [19719.0, 20000.0, '85399960562'], [19661.0, 40000.0, '85399960678'], [19624.0, 110000.0, '85399960752'], [19500.0, 1590000.0, '85399961000'], [19420.0, 130000.0, '85399961160'], [19349.0, 39400000.0, '85399961302'], [19308.0, 5180000.0, '85399961384'], [19280.0, 2590000.0, '85399961440'], [19200.0, 500000.0, '85399961600'], [19000.0, 2750000.0, '85399962000'], [18800.0, 26600000.0, '85399962400'], [18500.0, 310000.0, '85399963000'], [18490.0, 20000.0, '85399963020'], [18000.0, 310000.0, '85399964000'], [17800.0, 28090000.0, '85399964400'], [17722.0, 20000.0, '85399964556'], [17500.0, 13390000.0, '85399965000'], [17000.0, 12480000.0, '85399966000'], [16800.0, 29760000.0, '85399966400'], [16564.5, 40050000.0, '85399966871'], [16500.0, 14350000.0, '85399967000'], [16189.0, 2150000.0, '85399967622'], [16080.0, 7260000.0, '85399967840'], [16000.0, 370000.0, '85399968000'], [15850.0, 7480000.0, '85399968300'], [15800.0, 63290000.0, '85399968400'], [15799.0, 330000.0, '85399968402'], [15789.0, 940000.0, '85399968422'], [15768.0, 620000.0, '85399968464'], [15750.0, 200000.0, '85399968500'], [15620.0, 8050000.0, '85399968760'], [15594.0, 320000.0, '85399968812'], [15500.0, 15190000.0, '85399969000'], [15490.0, 250000.0, '85399969020'], [15400.0, 3190000.0, '85399969200'], [15390.0, 9060000.0, '85399969220'], [15300.0, 3190000.0, '85399969400'], [15279.0, 240000.0, '85399969442'], [15250.0, 200000.0, '85399969500'], [15200.0, 3190000.0, '85399969600'], [15189.0, 1220000.0, '85399969622'], [15100.0, 3190000.0, '85399969800'], [15000.0, 3440000.0, '85399970000'], [14999.0, 1050000.0, '85399970002'], [14989.0, 240000.0, '85399970022'], [14980.0, 310000.0, '85399970040'], [14900.0, 5020000.0, '85399970200'], [14899.0, 640000.0, '85399970202'], [14890.0, 640000.0, '85399970220'], [14879.0, 300000.0, '85399970242'], [14800.0, 67570000.0, '85399970400'], [14567.0, 8000000.0, '85399970866'], [14500.0, 1180000.0, '85399971000'], [14300.0, 69930000.0, '85399971400'], [14189.0, 1790000.0, '85399971622'], [14060.0, 3560000.0, '85399971880'], [14000.0, 290000.0, '85399972000'], [13980.0, 70000.0, '85399972040'], [13880.0, 720000.0, '85399972240'], [13800.0, 72460000.0, '85399972400'], [13678.0, 180000.0, '85399972644'], [13501.0, 2000000.0, '85399972998'], [13500.0, 370000.0, '85399973000'], [13300.0, 75190000.0, '85399973400'], [13001.0, 2000000.0, '85399973998'], [13000.0, 7860000.0, '85399974000'], [12800.0, 2430000.0, '85399974400'], [12789.0, 6440000.0, '85399974422'], [12680.0, 70000.0, '85399974640'], [12544.0, 10000000.0, '85399974912'], [12500.0, 2000000.0, '85399975000'], [12000.0, 4480000.0, '85399976000'], [11527.0, 13090000.0, '85399976946'], [11500.0, 2240000.0, '85399977000'], [11300.0, 13270000.0, '85399977400'], [11000.0, 2440000.0, '85399978000'], [10899.0, 5120000.0, '85399978202'], [10500.0, 1950000.0, '85399979000'], [10400.0, 14420000.0, '85399979200'], [10150.0, 147800000.0, '85399979700'], [10000.0, 2720000.0, '85399980000'], [9900.0, 1990000.0, '85399980200'], [9500.0, 3710000.0, '85399981000'], [9130.0, 3060000.0, '85399981740'], [9000.0, 15040000.0, '85399982000'], [8900.0, 11240000.0, '85399982200'], [8825.0, 1000000.0, '85399982350'], [8750.0, 5940000.0, '85399982500'], [8700.0, 4600000.0, '85399982600'], [8400.0, 1220000.0, '85399983200'], [6800.0, 4030000.0, '85399986400'], [6790.0, 14730000.0, '85399986420'], [6250.0, 20000000.0, '85399987500'], [5680.0, 3050000.0, '85399988640'], [4156.0, 30000000.0, '85399991688'], [3000.0, 10000.0, '85399994000'], [2249.0, 40000.0, '85399995502'], [1970.0, 10000.0, '85399996060'], [1000.0, 200000.0, '85399998000'], [300.0, 2000000.0, '85399999400'], [100.0, 2000000.0, '85399999800'], [59.0, 100320000.0, '85399999882'], [49.0, 69960000.0, '85399999902'], [30.0, 35000000.0, '85399999940'], [25.0, 100000000.0, '85399999950'], [22.0, 201090000.0, '85399999956'], [17.0, 200000000.0, '85399999966'], [14.0, 5000000000.0, '85399999972'], [10.0, 509600000.0, '85399999980'], [9.5, 82840000.0, '85399999981'], [9.0, 15670000.0, '85399999982'], [8.5, 940000.0, '85399999983'], [8.0, 190880000.0, '85399999984'], [7.5, 100000000.0, '85399999985'], [7.0, 202000000.0, '85399999986'], [6.0, 200000000.0, '85399999988'], [5.0, 1425800000.0, '85399999990'], [4.0, 1175250000.0, '85399999992'], [3.0, 1606000000.0, '85399999994'], [2.5, 107600000.0, '85399999995'], [2.0, 2326010000.0, '85399999996'], [1.5, 10000000000.0, '85399999997'], [1.0, 12336000000.0, '85399999998'], [0.5, 31062000000.0, '85399999999']],
 'datetime': '2023-03-27T08:30:58.809Z',
 'nonce': None,
 'symbol': 'XBT_USDT',
 'timestamp': 1679905858809}
```
