### PR TITLE
cex - fix deposit address

### LINKED ISSUE #15541: Can NOT get BTC deposit address for cex for CCXT version 2.1.14
- OS: Windows 10 PRO (21H2)
- Programming Language version: Node.js (Ver 19.0.0)
- CCXT version: 2.1.4

```JavaScript
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

if (process.argv.length != 3)
{
        console.error('Usage: USDT');
        console.error('Get [coin1] deposit address at [cex]');
        console.error('Please try again!');
        process.exit(1);
}
const [nodejs, script1, coin1] = process.argv;

const exchange = new ccxt.cex ({
    'apiKey': keys.cex.apiKey,
    'secret': keys.cex.secret,
    'uid': 'My_UID',
    adjustForTimeDifference: true,
    defaultType: 'spot',
    verbose: false,
});

const deposit1CoinAddress = async (coin1) => {
try
{
        const deposits = await exchange.fetchDepositAddress(coin1);
        if (typeof deposits !== 'undefined')
        {
                const json_deposits = JSON.stringify(deposits);
                console.log(json_deposits);
        }
        else
        {
                const obj_deposit0 = ({ 'Symbol': coin1, 'Data': [] });
                const json_deposit0 = JSON.stringify(obj_deposit0);
                console.log(obj_deposit0);
        }
}
catch (err)
{
        console.error(err)
}
};
deposit1CoinAddress(coin1);
```

```
D:\nodejs\CCXT_Address>node cex_deposit1CoinAddress.js BTC
CCXT Version: 2.1.14
(node:27568) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ExchangeError: cex {"e":"get_address","error":"System error","ok":"error"}
    at cex.handleErrors (D:\nodejs\CCXT_Address\node_modules\ccxt\js\cex.js:1572:19)
    at D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async cex.fetch2 (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1811:16)
    at async cex.request (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1815:16)
    at async cex.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\cex.js:1510:26)
    at async deposit1CoinAddress (D:\nodejs\CCXT_Address\cex_deposit1CoinAddress.js:27:19) {
  constructor: [class ExchangeError extends BaseError]
}
```

Hello:
I want to use CCXT to get some currency deposit address, for USDT and ETH, my code works, but for BTC and others not.
How to fix this strange issue?  Some works, some not.
Please advise!
Thanks,

### PR DESCRIPTION
**Pull request by ttodua**
fix #15541 
(copied the most of the codes from bybit. I think that we soon have to migrate the network parsing/related methods into base. I'll make PRs for them in near future).

= CEX.IO =
```
await e.fetchDepositAddress ('USDT') :

{
  currency: "USDT",
  address: "TRX1XpuFRuinxdHBv9MQWyT2JirevABCD4",
  tag: undefined,
  network: "TRC20",
  info: {
    blockchain: "Tron",
    address: "TRX1XpuFRuinxdHBv9MQWyT2JirevABCD4",
  },
}


await e.fetchDepositAddress ('USDT', {network: 'ERC20'}) :

{
  currency: "USDT",
  address: "0xd08ec6bW123d822fae43d7967a92a8b6d6er7gd3",
  tag: undefined,
  network: "ERC20",
  info: {
    blockchain: "Ethereum",
    address: "0xd08ec6bW123d822fae43d7967a92a8b6d6er7gd3",
  },
}
```

= Bybit =
```
await e.fetchDepositAddress ('USDT') : 

{
  currency: "USDT",
  address: "TC2NCAC5WSVCCwaE3kWZXyW91ZKKhLa99c",
  tag: undefined,
  network: "TRX",
  info: {
    chainType: "TRC20",
    addressDeposit: "TC2NCAC5WSVCCwaE3kWZXyW91ZKKhLa99c",
    tagDeposit: "",
    chain: "TRX",
  },
}


await e.fetchDepositAddress ('USDT', {network: 'ERC20'}) : 

{
  currency: "USDT",
  address: "0xb88897c6717c1d1c11c30554468ed50a9b4444ee",
  tag: undefined,
  network: "ETH",
  info: {
    chainType: "ERC20",
    addressDeposit: "0xb88897c6717c1d1c11c30554468ed50a9b4444ee",
    tagDeposit: "",
    chain: "ETH",
  },
}

```

### CODE REVIEW

File: js/cex.js [hunk 1]
```diff
@@ -1507,18 +1520,89 @@ module.exports = class cex extends Exchange {
...
             'address': address,
             'tag': undefined,
-            'network': undefined,
-            'info': response,
+            'network': networkCode,
+            'info': addressObject,
         };
     }
 
+    networkIdToCode (networkId) {
```
Comment (carlosmiei) [inline js/cex.js:1568]: @ttodua so we define the exact same methods in bybit too, if we're going to use this approach we should move them to Exchange.js no?

Comment (ttodua) [reply js/cex.js:1568]: > @ttodua so we define the exact same methods in bybit too, if we're going to use this approach we should move them to Exchange.js no?

yes, right, I was already going to submit them in base, but at first, made this PR to demonstrate that we will need to use those methods in most implementation.
I'll modify this PR and ask your re-review tomorrow.

Comment (ttodua) [reply js/cex.js]: @carlosmiei , after thorough revision and planning, I have submitted the most optimal and unified methods that are reusable (can show other existing exchanges too which will benefit from these methods, even the above mentioned 'bybit').
If you look into them thoroughly, you understand what each of those methods do and all of them is important in the process of network-unification across lib.

Comment (ttodua) [reply js/cex.js]: I've attached example responses in the top-post.

File: js/bybit.js [hunk 2]
```diff
@@ -4503,27 +4466,10 @@ module.exports = class bybit extends Exchange {
...
-                const ids = Object.keys (chainsIndexedById);
-                const defaultNetwordId = this.defaultNetworkId (code);
-                chosenNetworkId = (defaultNetwordId in chainsIndexedById) ? defaultNetwordId : ids[0];
-            }
-            const addressInfo = chainsIndexedById[chosenNetworkId];
-            return this.parseDepositAddress (addressInfo, currency);
-        }
+        const chainsIndexedById = this.indexBy (chains, 'chain');
+        const selectedNetworkId = this.selectDefaultNetworkId (code, networkCode, chainsIndexedById);
+        const addressObject = this.safeValue (chainsIndexedById, selectedNetworkId, {});
```
Comment (ttodua) [inline js/bybit.js:4471]: the above two lines replaced dozens of custom codes in CEX & bybit (other exchanges in the row of update).

File: js/cex.js [hunk 3]
```diff
@@ -1498,24 +1515,47 @@ module.exports = class cex extends Exchange {
          * @param {object} params extra parameters specific to the cex api endpoint
          * @returns {object} an [address structure]{@link https://docs.ccxt.com/en/latest/manual.html#address-structure}
          */
-        if (code === 'XRP' || code === 'XLM') {
-            // https://github.com/ccxt/ccxt/pull/2327#issuecomment-375204856
-            throw new NotSupported (this.id + ' fetchDepositAddress() does not support XRP and XLM addresses yet (awaiting docs from CEX.io)');
-        }
```
Comment (ttodua) [inline js/cex.js:1504]: these codes are now available.

File: js/cex.js [hunk 4]
```diff
@@ -1498,24 +1515,47 @@ module.exports = class cex extends Exchange {
...
+        //                 }
+        //             ]
+        //         }
+        //     }
+        //
+        const data = this.safeValue (response, 'data', {});
+        const addresses = this.safeValue (data, 'addresses', []);
+        const chainsIndexedById = this.indexBy (addresses, 'blockchain');
+        const selectedNetworkId = this.selectDefaultNetworkId (code, networkCode, chainsIndexedById);
+        const addressObject = this.safeValue (chainsIndexedById, selectedNetworkId, {});
```
Comment (ttodua) [inline js/cex.js:1550]: the above two-three lines are exactly same as in bybit.

File: js/cex.js (hunk 1 above)
Comment (ttodua) [reply js/cex.js]: I think this PR might be needed soon, because `networkCodeToId` and other methods will be also necessary for @AlgoQ / @samgermain  to work on network-related slugs (in fetchTransactionFees, which is underway).

File: js/base/Exchange.js [hunk 5]
```diff
@@ -1634,6 +1634,71 @@ module.exports = class Exchange {
...
+            // otherwise, try to use the global-scope 'defaultNetwork' value (even if that network is not supported by currency, it doesn't make any problem, this will be just used "at first" if currency supports this network at all)
+            const defaultNetwork = this.safeValue (this.options, 'defaultNetwork');
+            if (defaultNetwork !== undefined) {
+                defaultNetworkCode = defaultNetwork;
+            }
+        }
+        return defaultNetworkCode;
+    }
+
+    getDefaultNetworkIdFromRawNetworks (currencyCode, networkCode, networkEntriesIndexed) {
```
Comment (carlosmiei) [inline js/base/Exchange.js:1672]: @ttodua  "Default" does not seem correct here because if `networkCode` is specified, it might not be the default.

What do you think of `getNetworkIdFromAvailableNetworks` ?

Comment (ttodua) [reply js/base/Exchange.js:1672]: You are somewhat right, I've changed around 5 different names in the process frankly, and none of them seemed absolutely fit. on one hand,  if `networkCode` is provided, then it ignores any "defaults" or whatever, but if `networkCode` is not passed, then it yes, tries to detect 'default network'. but in overall, i think your version will be less intrusive. I'm pushing it now.

Comment (ttodua) [reply js/base/Exchange.js]: done. tests passes now, `bitbns` no longer breaks the build.

**Comment by carlosmiei** [comment]
LGTM ✅ 
```
 p cex fetchDepositAddress USDT '{"network":"BSC"}' 
Python v3.10.8
CCXT v2.1.89
cex.fetchDepositAddress(USDT,{'network': 'BSC'})
{'address': '0x09cb5cc268eff4fa9c96a7e05ce21ed0cfee61a7',
 'currency': 'USDT',
 'info': {'addresses': [{'address': '0x09cb5cc268eff4fa9c96a7e05ce21ed0cfee61a7',
                         'blockchain': 'Binance Smart Chain'},
                        {'address': '0x09cb5cc268eff4fa9c96a7e05ce21ed0cfee61a7',
                         'blockchain': 'Ethereum'},
                        {'address': 'TSrvQ6Zd5jFS82oRYeBT9i72gNUan36Nam',
                         'blockchain': 'Tron'}],
          'name': 'USDT'},
 'network': 'BEP20',
 'tag': None}
```

**Review by carlosmiei — APPROVED** [review]
