### PR TITLE
fix(coinex): parse cfx deposit address correctly. fix #17197

### LINKED ISSUE #17197: CoinEx parse_deposit_address tag issue for CFX addresses
### Operating System

Debian 11

### Programming Languages

php

### CCXT Version

3.0.1

### Description

For coins with deposit tags, Coinex's api returns deposit addresses in the format of [address]:[tag].

However, Conflux (CFX) mainnet addresses start with "cfx:", but Conflux does not use deposit tags. An example CFX address returned by CoinEx's api is cfx:aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k.

This causes ccxt's CoinEx parse_deposit_address function to incorrectly think that the address is cfx and the tag is aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k

Examples:
[Correct - EOS]
```php
Array
(
    [info] => Array
        (
            [coin_address] => coinexdoteos:XpYUqxingQMmYD1oHrjTJS
            [is_bitcoin_cash] =>
        )

    [currency] => EOS
    [address] => coinexdoteos
    [tag] => XpYUqxingQMmYD1oHrjTJS
    [network] => EOSIO
)
```
[Incorrect - CFX]
```php
Array
(
    [info] => Array
        (
            [coin_address] => cfx:aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k
            [is_bitcoin_cash] =>
        )

    [currency] => CFX
    [address] => cfx
    [tag] => aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k
    [network] => CFX
)
```

### PR DESCRIPTION
**Pull request by pcriadoperez**

### CODE REVIEW

File: ts/src/coinex.ts [hunk 1]
```diff
@@ -2647,7 +2647,7 @@ export default class coinex extends Exchange {
         let address = undefined;
         let tag = undefined;
         const partsLength = parts.length;
-        if (partsLength > 1) {
+        if (partsLength > 1 && parts[0] !== 'cfx') {
```
Comment (carlosmiei) [inline ts/src/coinex.ts:2650]: @pcriadoperez Did you test this? Also can you elaborate a bit more why this is needed?

**Review by carlosmiei — APPROVED** [review]
