### PR TITLE
fix(binance): editOrder ws timestamp, fix #18051

### LINKED ISSUE #18051: Expected modify response is overriden by previoulsy closed/recieved fully FILLED/TRADE message | Binance Future/WebSocket/TestMarket
### Operating System

ubuntu

### Programming Languages

python

### CCXT Version

3.1.10

### Description

Issue summary: Expected order modify response from the websocket (clientorderid: 10001) is overriden by previoulsy received FULL_FILLED (TRADE) message of clientorderid: 10002 | websocket (watch_order) - Binance Future / Test Market

Link to original issue: https://github.com/ccxt/ccxt/issues/18028

Below, pls find logs to analyise the issue (I am able to simulate the issue each every time).

//Placed NEW order request clientid: 10001 from CCXT to Binance (REST)
fetch Request: binance POST https://testnet.binancefuture.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': 'b39ae4c71d96765d319f7cb0fb46c2619d9aeefbc7e7aadb5fa66de55536be0f', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: timestamp=1685253241106&symbol=XRPUSDT&side=BUY&newClientOrderId=10001&newOrderRespType=RESULT&type=LIMIT&quantity=20&price=0.4715&timeInForce=GTC&recvWindow=10000&signature=efed205a624f23595e5017430d2d00f4ee2271086c37fdf08e292f3838c9ec37
2023-05-28T05:54:01.404Z message {"e":"ORDER_TRADE_UPDATE","T":1685253241288,"E":1685253241290,"o":{"s":"XRPUSDT","c":"10001","S":"BUY","o":"LIMIT","f":"GTC","q":"20","p":"0.4715","ap":"0","sp":"0","x":"NEW","X":"NEW","i":246195608,"l":"0","z":"0","L":"0","n":"0","N":"USDT","T":1685253241288,"t":0,"b":"9.43000","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"LIMIT","ps":"BOTH","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}

// Recieved execution_type=NEW, clientorderid: 10001 (WEB SOCKET)
Reciever-response::clientOrder_id= 1 10001 exchangeOrder_id= 246195608 execution_type= NEW {'info': {'s': 'XRPUSDT', 'c': '10001', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '20', 'p': '0.4715', 'ap': '0', 'sp': '0', 'x': 'NEW', 'X': 'NEW', 'i': 246195608, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1685253241288, 't': 0, 'b': '9.43000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0}, 'symbol': 'XRP/USDT:USDT', 'id': '246195608', 'clientOrderId': '10001', 'timestamp': 1685253241288, 'datetime': '2023-05-28T05:54:01.288Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 0.4715, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 20.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 20.0, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}

// Recieved execution_type=NEW, clientorderid: 10001 (REST)
binance POST https://testnet.binancefuture.com/fapi/v1/order 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 28 May 2023 05:54:01 GMT', 'Server': 'Bengine', 'Vary': 'Accept-Encoding', 'x-mbx-used-weight-1m': '-1', 'x-mbx-order-count-10s': '1', 'x-mbx-order-count-1m': '1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Content-Security-Policy': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Expires': '0', 'Pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c1a525e03173d332afbea7618ea1de52.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DEL51-P1', 'X-Amz-Cf-Id': 'OecDStMunlaHWBZ7VG-hAfgUoFSGkNc7Q8rPhP_Z2fXnt1_K-85CSQ=='} ResponseBody: {"orderId":246195608,"symbol":"XRPUSDT","status":"NEW","clientOrderId":"10001","price":"0.4715","avgPrice":"0.00","origQty":"20.0","executedQty":"0.0","cumQty":"0.0","cumQuote":"0.00000","timeInForce":"GTC","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0.0000","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"LIMIT","updateTime":1685253241288}

//Placed NEW order request clientid: 10002 from CCXT to Binance (REST)
fetch Request: binance POST https://testnet.binancefuture.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': 'b39ae4c71d96765d319f7cb0fb46c2619d9aeefbc7e7aadb5fa66de55536be0f', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: timestamp=1685253241734&symbol=XRPUSDT&side=SELL&newClientOrderId=10002&newOrderRespType=RESULT&type=LIMIT&quantity=20&price=0.472&timeInForce=GTC&recvWindow=10000&signature=c2e3a2d7790c8efb76a570641f171845c46c134ca59f936d3a94e39304198afb

//ORDER_TRADE_UPDATE
fetch Response:2023-05-28T05:54:02.332Z message {"e":"ORDER_TRADE_UPDATE","T":1685253242234,"E":1685253242239,"o":{"s":"XRPUSDT","c":"10002","S":"SELL","o":"LIMIT","f":"GTC","q":"20","p":"0.4720","ap":"0","sp":"0","x":"NEW","X":"NEW","i":246195610,"l":"0","z":"0","L":"0","n":"0","N":"USDT","T":1685253242234,"t":0,"b":"9.43000","a":"10.21000","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"LIMIT","ps":"BOTH","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}

// Recieved execution_type=FILLED, clientorderid: 10002 (REST)
binance POST https://testnet.binancefuture.com/fapi/v1/order 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 28 May 2023 05:54:02 GMT', 'Server': 'Bengine', 'Vary': 'Accept-Encoding', 'x-mbx-used-weight-1m': '-1', 'x-mbx-order-count-10s': '2', 'x-mbx-order-count-1m': '2', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Content-Security-Policy': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Expires': '0', 'Pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c1a525e03173d332afbea7618ea1de52.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DEL51-P1', 'X-Amz-Cf-Id': 'hkk_ttM_Yw6cZOB5XMWPLixJfPCPT3hCef_4XP4AkVMx4d0W4sHAzw=='} ResponseBody: {"orderId":246195610,"symbol":"XRPUSDT","status":"FILLED","clientOrderId":"10002","price":"0.4720","avgPrice":"0.51050","origQty":"20.0","executedQty":"20.0","cumQty":"20.0","cumQuote":"10.21000","timeInForce":"GTC","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"SELL","positionSide":"BOTH","stopPrice":"0.0000","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"LIMIT","updateTime":1685253242234}

//ACCOUNT_UPDATE 10002
2023-05-28T05:54:02.399Z message {"e":"ACCOUNT_UPDATE","T":1685253242235,"E":1685253242239,"a":{"B":[{"a":"USDT","wb":"15000.06670983","cw":"15000.06670983","bc":"0"}],"P":[{"s":"XRPUSDT","pa":"-160","ep":"0.51120","cr":"0.45745999","up":"6.20427040","mt":"cross","iw":"0","ps":"BOTH","ma":"USDT"}],"m":"ORDER"}}
Reciever-response::clientOrder_id= 1 10002 exchangeOrder_id= 246195610 execution_type= NEW {'info': {'s': 'XRPUSDT', 'c': '10002', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '20', 'p': '0.4720', 'ap': '0', 'sp': '0', 'x': 'NEW', 'X': 'NEW', 'i': 246195610, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1685253242234, 't': 0, 'b': '9.43000', 'a': '10.21000', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0}, 'symbol': 'XRP/USDT:USDT', 'id': '246195610', 'clientOrderId': '10002', 'timestamp': 1685253242234, 'datetime': '2023-05-28T05:54:02.234Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'sell', 'price': 0.472, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 20.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 20.0, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}

//ORDER_TRADE_UPDATE 10002
2023-05-28T05:54:02.447Z message {"e":"ORDER_TRADE_UPDATE","T":1685253242234,"E":1685253242239,"o":{"s":"XRPUSDT","c":"10002","S":"SELL","o":"LIMIT","f":"GTC","q":"20","p":"0.4720","ap":"0.51050","sp":"0","x":"TRADE","X":"FILLED","i":246195610,"l":"20","z":"20","L":"0.5105","n":"0.00408400","N":"USDT","T":1685253242234,"t":19321615,"b":"9.43000","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"LIMIT","ps":"BOTH","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}

// Recieved execution_type=FILLED, clientorderid: 10002 (WEB SOCKET)
Reciever-response::clientOrder_id= 1 10002 exchangeOrder_id= 246195610 execution_type= TRADE {'info': {'s': 'XRPUSDT', 'c': '10002', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '20', 'p': '0.4720', 'ap': '0.51050', 'sp': '0', 'x': 'TRADE', 'X': 'FILLED', 'i': 246195610, 'l': '20', 'z': '20', 'L': '0.5105', 'n': '0.00408400', 'N': 'USDT', 'T': 1685253242234, 't': 19321615, 'b': '9.43000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0}, 'symbol': 'XRP/USDT:USDT', 'id': '246195610', 'clientOrderId': '10002', 'timestamp': 1685253242234, 'datetime': '2023-05-28T05:54:02.234Z', 'lastTradeTimestamp': 1685253242234, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'sell', 'price': 0.472, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 20.0, 'cost': 10.21, 'average': 0.5105, 'filled': 20.0, 'remaining': 0.0, 'status': 'closed', 'fee': {'cost': 0.004084, 'currency': 'USDT'}, 'trades': [{'info': {'s': 'XRPUSDT', 'c': '10002', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '20', 'p': '0.4720', 'ap': '0.51050', 'sp': '0', 'x': 'TRADE', 'X': 'FILLED', 'i': 246195610, 'l': '20', 'z': '20', 'L': '0.5105', 'n': '0.00408400', 'N': 'USDT', 'T': 1685253242234, 't': 19321615, 'b': '9.43000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0}, 'timestamp': 1685253242234, 'datetime': '2023-05-28T05:54:02.234Z', 'symbol': 'XRP/USDT:USDT', 'id': '19321615', 'order': '246195610', 'type': 'limit', 'takerOrMaker': 'taker', 'side': 'sell', 'price': 0.5105, 'amount': 20.0, 'cost': 10.21, 'fee': {'cost': 0.004084, 'currency': 'USDT'}, 'fees': [{'cost': 0.004084, 'currency': 'USDT'}]}], 'fees': [{'cost': 0.004084, 'currency': 'USDT'}]}\

//Placed Modify order request clientid: 10001 from CCXT to Binance (REST)
fetch Request: binance PUT https://testnet.binancefuture.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': 'b39ae4c71d96765d319f7cb0fb46c2619d9aeefbc7e7aadb5fa66de55536be0f', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: timestamp=1685253242770&symbol=XRPUSDT&side=BUY&orderId=None&quantity=20&price=0.4716&origClientOrderId=10001&recvWindow=10000&signature=1ab66e6433b9a1e87cc9cbe53cd95302cb2e43b2f59dca0bdeaad51dc30a1486
2023-05-28T05:54:03.259Z message {"e":"ORDER_TRADE_UPDATE","T":1685253243193,"E":1685253243196,"o":{"s":"XRPUSDT","c":"10001","S":"BUY","o":"LIMIT","f":"GTC","q":"20","p":"0.4716","ap":"0","sp":"0","x":"AMENDMENT","X":"NEW","i":246195608,"l":"0","z":"0","L":"0","n":"0","N":"USDT","T":1685253243193,"t":0,"b":"9.43200","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"LIMIT","ps":"BOTH","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}

// Recieved execution_type=NEW, clientorderid: 10001 from CCXT (REST)
fetch Response: binance PUT https://testnet.binancefuture.com/fapi/v1/order 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 28 May 2023 05:54:03 GMT', 'Server': 'Bengine', 'Vary': 'Accept-Encoding', 'x-mbx-used-weight-1m': '-1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Content-Security-Policy': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Expires': '0', 'Pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c1a525e03173d332afbea7618ea1de52.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DEL51-P1', 'X-Amz-Cf-Id': 'rc_5UeAac5kshLi5Dhmj3i37bwEWdxG7Vjnj08zlmZCep00rIEzhHQ=='} ResponseBody: {"orderId":246195608,"symbol":"XRPUSDT","status":"NEW","clientOrderId":"10001","price":"0.4716","avgPrice":"0.00","origQty":"20.0","executedQty":"0.0","cumQty":"0.0","cumQuote":"0.00000","timeInForce":"GTC","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0.0000","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"LIMIT","updateTime":1685253243193}

// Recieved execution_type=FILLED, clientorderid: 10002 (WEB SOCKET)
// ******** BUG ********: clientorderid 10002 already FILLED and recieved previously by both REST & WEBSOCKET and recieved again which is not correct.
// Expected message to be recieved is modify response of clientorderid 10001 and which has been overriden by clientorderid 10002 FILLED message
Reciever-response::clientOrder_id= 1 10002 exchangeOrder_id= 246195610 execution_type= TRADE {'info': {'s': 'XRPUSDT', 'c': '10002', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '20', 'p': '0.4720', 'ap': '0.51050', 'sp': '0', 'x': 'TRADE', 'X': 'FILLED', 'i': 246195610, 'l': '20', 'z': '20', 'L': '0.5105', 'n': '0.00408400', 'N': 'USDT', 'T': 1685253242234, 't': 19321615, 'b': '9.43000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0}, 'symbol': 'XRP/USDT:USDT', 'id': '246195610', 'clientOrderId': '10002', 'timestamp': 1685253242234, 'datetime': '2023-05-28T05:54:02.234Z', 'lastTradeTimestamp': 1685253242234, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'sell', 'price': 0.472, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 20.0, 'cost': 10.21, 'average': 0.5105, 'filled': 20.0, 'remaining': 0.0, 'status': 'closed', 'fee': {'cost': 0.004084, 'currency': 'USDT'}, 'trades': [{'info': {'s': 'XRPUSDT', 'c': '10002', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '20', 'p': '0.4720', 'ap': '0.51050', 'sp': '0', 'x': 'TRADE', 'X': 'FILLED', 'i': 246195610, 'l': '20', 'z': '20', 'L': '0.5105', 'n': '0.00408400', 'N': 'USDT', 'T': 1685253242234, 't': 19321615, 'b': '9.43000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0}, 'timestamp': 1685253242234, 'datetime': '2023-05-28T05:54:02.234Z', 'symbol': 'XRP/USDT:USDT', 'id': '19321615', 'order': '246195610', 'type': 'limit', 'takerOrMaker': 'taker', 'side': 'sell', 'price': 0.5105, 'amount': 20.0, 'cost': 10.21, 'fee': {'cost': 0.004084, 'currency': 'USDT'}, 'fees': [{'cost': 0.004084, 'currency': 'USDT'}]}], 'fees': [{'cost': 0.004084, 'currency': 'USDT'}]}

### Code

```
  

```

### PR DESCRIPTION
**Pull request by pcriadoperez**
### Problem
When editting an order, the timestamp was getting overwritten by the old timestamp

### Solution
Only overwrite timestamp if undefined

### CODE REVIEW

File: ts/src/pro/binance.ts [hunk 1]
```diff
@@ -1688,8 +1688,11 @@ export default class binance extends binanceRest {
                     parsed['fees'] = fees;
                 }
                 parsed['trades'] = this.safeValue (order, 'trades');
-                parsed['timestamp'] = this.safeInteger (order, 'timestamp');
-                parsed['datetime'] = this.safeString (order, 'datetime');
+                const timestamp = this.safeInteger (parsed, 'timestamp');
```
Comment (carlosmiei) [inline ts/src/pro/binance.ts:1691]: @pcriadoperez sorry I don't fully understand this yet, how can we get an ws update with an outdated timestamp?

**Review by kroitor — APPROVED** [review]
