### PR TITLE
fix(bitfinex2): fix #17540 - bitfinex2 orderbook checksum

### LINKED ISSUE #17540: Bitfinex checksum error watching order book
### Operating System

Ubuntu

### Programming Languages

JS

### CCXT Version

3.0.54

### Description

I have subscribed to Bitfinex order book (XAUT/USDT) and I have been receiving the error **bitfinex2 invalid checksum**.

This is my subscription:

`const orderBook = await exchange.watchOrderBook('XAUT/USDT', 25);`

I read that if I use the limit it could cause this problem. But if I don't send a limit then I'm getting 25 bids and 25 asks because 25 is the dafult value for Bitfinex, so I suppose that I will get the error **bitfinex2 invalid checksum**.

What I did is increment the limit to 100:

`const orderBook = await exchange.watchOrderBook('XAUT/USDT', 100);`

I supposed that if I increase the limit then it would minimize the number of **bitfinex2 invalid checksum** errors that I get. The problem is that with this limit I start receiving order books, but after some order books (very few order books) I get this error:

```
my-app/node_modules/ccxt/dist/cjs/src/pro/bitfinex2.js:661
            stringArray.push(asks[i][0]);


TypeError: Cannot read properties of undefined (reading '0')
    at bitfinex2.handleChecksum (my-app/node_modules/ccxt/dist/cjs/src/pro/bitfinex2.js:661:37)
    at bitfinex2.handleMessage (my-app/node_modules/ccxt/dist/cjs/src/pro/bitfinex2.js:1124:31)
    at WsClient.onMessage (my-app/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:268:14)
    at callListener (my-app/node_modules/ccxt/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (my-app/node_modules/ccxt/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (my-app/node_modules/ccxt/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (my-app/node_modules/ccxt/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (my-app/node_modules/ccxt/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (my-app/node_modules/ccxt/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (my-app/node_modules/ccxt/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
```

If I limit to 100 instead of 25, should this avoid the error **bitfinex2 invalid checksum**?

If it doesn't solve the problem, is there a way to avoid this error? Would be safe if I set the **checksum** option to false?

Could be solved the error when the limit is set to 100?

Thank you very much!!

### Code

```
  

```

### PR DESCRIPTION
**Pull request by pcriadoperez**
Bitfinex2 does checksum only of first 25 bids and asks

### CODE REVIEW

File: ts/src/pro/bitfinex2.ts [hunk 1]
```diff
@@ -661,7 +661,7 @@ export default class bitfinex2 extends bitfinex2Rest {
         if (book === undefined) {
             return;
         }
-        const depth = this.safeInteger (subscription, 'len');
+        const depth = 25; // covers the first 25 bids and asks
```
Comment (carlosmiei) [inline ts/src/pro/bitfinex2.ts:664]: @pcriadoperez this does not seem to be fixing it
```
 'datetime': None,
 'nonce': None,
 'symbol': None,
 'timestamp': None}
2023-04-15T13:59:52.124Z message [91247,"cs",-564698696]
Traceback (most recent call last):
  File "/Users/cjg/Git/ccxt2/ccxt/examples/py/cli.py", line 232, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/cjg/Git/ccxt2/ccxt/examples/py/cli.py", line 211, in main
    result = await method(*args)
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/pro/bitfinex2.py", line 513, in watch_order_book
    orderbook = await self.subscribe('book', symbol, self.deep_extend(request, params))
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/pro/bitfinex2.py", line 62, in subscribe
    result = await self.watch(url, messageHash, self.deep_extend(request, params), messageHash, {'checksum': False})
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/async_support/base/ws/fast_client.py", line 27, in handler
    self.handle_message(message)
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/async_support/base/ws/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/async_support/base/ws/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/pro/bitfinex2.py", line 1056, in handle_message
    return method(client, message, subscription)
  File "/Users/cjg/Git/ccxt2/ccxt/python/ccxt/pro/bitfinex2.py", line 625, in handle_checksum
    payload = ':'.join(stringArray)
TypeError: sequence item 0: expected str instance, float found
bitfinex2 requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
```

Comment (pcriadoperez) [reply ts/src/pro/bitfinex2.ts:664]: good catch, put in a fix for python and php

File: ts/src/pro/bitfinex2.ts [hunk 2]
```diff
@@ -60,7 +60,7 @@ export default class bitfinex2 extends bitfinex2Rest {
         const checksum = this.safeValue (this.options, 'checksum', true);
         if (checksum && !client.subscriptions[messageHash]['checksum'] && (channel === 'book')) {
             client.subscriptions[messageHash]['checksum'] = true;
-            await client.send ({
+            client.send ({
```
Comment (carlosmiei) [inline ts/src/pro/bitfinex2.ts:63]: @pcriadoperez hum I think we need this `await` here otherwise we get
`/Users/cjg/Git/ccxt2/ccxt/python/ccxt/pro/bitfinex2.py:66: RuntimeWarning: coroutine 'ClientWebSocketResponse.send_str' was never awaited`

because 
```
    def send(self, message):
        if self.verbose:
            self.log(iso8601(milliseconds()), 'sending', message)
        return self.connection.send_str(message if isinstance(message, str) else json.dumps(message, separators=(',', ':')))
```
⬆️  send_str is async

**Comment by carlosmiei** [comment]
LGTM ✅ 
```
p bitfinex2 watchOrderBook "BTC/USDT"         
Python v3.10.9
CCXT v3.0.64
bitfinex2.watchOrderBook(BTC/USDT)
{'asks': [[29887.0, 0.13004106, 2.0], [29888.0, 0.14982419, 2.0], [29889.0, 0.47996895, 5.0], [29890.0, 0.22619789, 2.0], [29891.0, 0.24681394, 3.0], [29892.0, 2.27576978, 6.0], [29893.0, 1.20003572, 4.0], [29894.0, 1.14663234, 4.0], [29895.0, 0.31566452, 4.0], [29896.0, 0.87755531, 2.0], [29897.0, 0.27869256, 1.0], [29898.0, 0.69676959, 6.0], [29900.0, 0.64776814, 2.0], [29901.0, 0.1348, 2.0], [29903.0, 0.03373019, 2.0], [29904.0, 1.55981242, 5.0], [29905.0, 0.2528121, 1.0], [29906.0, 1.72725794, 2.0], [29907.0, 2.34372971, 5.0], [29908.0, 0.06687, 1.0], [29909.0, 0.41673786, 2.0], [29910.0, 0.3092, 1.0], [29911.0, 0.55903862, 4.0], [29912.0, 0.32895476, 2.0], [29913.0, 0.001, 1.0]],
 'bids': [[29885.0, 0.167203, 1.0], [29884.0, 0.0666, 1.0], [29882.0, 0.20078062, 2.0], [29881.0, 0.05, 1.0], [29880.0, 0.234128, 2.0], [29878.0, 0.05, 1.0], [29877.0, 0.301344, 3.0], [29876.0, 0.05, 1.0], [29875.0, 0.08270414, 2.0], [29874.0, 0.70219743, 5.0], [29873.0, 0.62954096, 2.0], [29872.0, 0.29051951, 2.0], [29871.0, 0.536356, 3.0], [29870.0, 0.28016445, 1.0], [29869.0, 0.16066953, 2.0], [29868.0, 1.30899634, 6.0], [29867.0, 0.41518501, 2.0], [29866.0, 0.03368368, 1.0], [29865.0, 0.09850598, 1.0], [29864.0, 0.39398127, 1.0], [29863.0, 0.94313917, 1.0], [29862.0, 0.9567, 2.0], [29861.0, 1.01277752, 2.0], [29859.0, 0.63993306, 3.0], [29857.0, 1.674673, 2.0]],
 'datetime': None,
 'nonce': None,
 'symbol': None,
 'timestamp': None}
{'asks': [[29887.0, 0.13004106, 2.0], [29888.0, 0.14982419, 2.0], [29889.0, 0.47996895, 5.0], [29890.0, 0.22619789, 2.0], [29891.0, 0.24681394, 3.0], [29892.0, 2.27576978, 6.0], [29893.0, 1.20003572, 4.0], [29894.0, 1.54573234, 5.0], [29895.0, 0.31566452, 4.0], [29896.0, 0.87755531, 2.0], [29897.0, 0.27869256, 1.0], [29898.0, 0.69676959, 6.0], [29900.0, 0.64776814, 2.0], [29901.0, 0.1348, 2.0], [29903.0, 0.03373019, 2.0], [29904.0, 1.55981242, 5.0], [29905.0, 0.2528121, 1.0], [29906.0, 1.72725794, 2.0], [29907.0, 2.34372971, 5.0], [29908.0, 0.06687, 1.0], [29909.0, 0.41673786, 2.0], [29910.0, 0.3092, 1.0], [29911.0, 0.55903862, 4.0], [29912.0, 0.32895476, 2.0], [29913.0, 0.001, 1.0]],
 'bids': [[29885.0, 0.167203, 1.0], [29884.0, 0.0666, 1.0], [29882.0, 0.20078062, 2.0], [29881.0, 0.05, 1.0], [29880.0, 0.234128, 2.0], [29878.0, 0.05, 1.0], [29877.0, 0.301344, 3.0], [29876.0, 0.05, 1.0], [29875.0, 0.08270414, 2.0], [29874.0, 0.70219743, 5.0], [29873.0, 0.62954096, 2.0], [29872.0, 0.29051951, 2.0], [29871.0, 0.536356, 3.0], [29870.0, 0.28016445, 1.0], [29869.0, 0.16066953, 2.0], [29868.0, 1.30899634, 6.0], [29867.0, 0.41518501, 2.0], [29866.0, 0.03368368, 1.0], [29865.0, 0.09850598, 1.0], [29864.0, 0.39398127, 1.0], [29863.0, 0.94313917, 1.0], [29862.0, 0.9567, 2.0], [29861.0, 1.01277752, 2.0], [29859.0, 0.63993306, 3.0], [29857.0, 1.674673, 2.0]],
 'datetime': None,
 'nonce': None,
 'symbol': None,
 'timestamp': None}
```
