### PR TITLE
Fix Coinegg loadMarkets and fetchTickers

### LINKED ISSUE #5086: CoinEgg LoadMarkets Unknown Markets
OS: Ubuntu 18.03
Programming Language version: Node v10
CCXT version: Latest
Exchange: CoinEgg
Method: LoadMarkets

```
Exchange Name:  coinegg
Exchange Markets: [
             '0/BTC',            '1/BTC',            '2/BTC',            '3/BTC',
             '4/BTC',            '5/BTC',            '6/BTC',            '7/BTC',
             '8/BTC',            '9/BTC',           '10/BTC',           '11/BTC',
            '12/BTC',           '13/BTC',           '14/BTC',           '15/BTC',
            '16/BTC',           '17/BTC',           '18/BTC',           '19/BTC',
            '20/BTC',           '21/BTC',           '22/BTC',           '23/BTC',
            '24/BTC',           '25/BTC',           '26/BTC',           '27/BTC',
            '28/BTC',           '29/BTC',           '30/BTC',           '31/BTC',
            '32/BTC',           '33/BTC',           '34/BTC',           '35/BTC',
            '36/BTC',           '37/BTC',           '38/BTC',           '39/BTC',
            '40/BTC',           '41/BTC',           '42/BTC',           '43/BTC',
            '44/BTC',           '45/BTC',           '46/BTC',           '47/BTC',
            '48/BTC',           '49/BTC',           '50/BTC',           '51/BTC',
            '52/BTC',           '53/BTC',           '54/BTC',           '55/BTC',
            '56/BTC',           '57/BTC',           '58/BTC',           '59/BTC',
            '60/BTC',           '61/BTC',           '62/BTC',           '63/BTC',
            '64/BTC',           '65/BTC',           '66/BTC',           '67/BTC',
            '68/BTC',           '69/BTC',           '70/BTC',           '71/BTC',
            '72/BTC',           '73/BTC',           '74/BTC',           '75/BTC',
            '76/BTC',           '77/BTC',           '78/BTC',           '79/BTC',
            '80/BTC',            '0/ETH',            '1/ETH',            '2/ETH',
             '3/ETH',            '4/ETH',            '5/ETH',            '6/ETH',
             '7/ETH',            '8/ETH',            '9/ETH',           '10/ETH',
            '11/ETH',           '12/ETH',           '13/ETH',           '14/ETH',
            '15/ETH',           '16/ETH',           '17/ETH',           '18/ETH',
  ... 224 more items
]
coinegg fetchTicker failed due to exchange error: coinegg coin does not exist 0/BTC


```

### PR DESCRIPTION
**Pull request by Legogris**
This fixes #5086 . Note that this is a breaking change since IDs are now using the identifiers returned by CoinEgg (`base_quote` as opposed to `basequote`).

### CODE REVIEW

File: js/coinegg.js [hunk 1]
```diff
@@ -258,36 +255,14 @@ module.exports = class coinegg extends Exchange {
...
-                        'vol': ticker[6],
-                        'quoteVol': ticker[7],
-                    }, market);
-                }
+        for (let i = 0; i < markets.length; i++) {
+            const market = markets[i];
+            if (symbols !== undefined && symbols.indexOf (market['symbol']) < 0) {
+                continue;
             }
+            result[market['symbol']] = await this.fetchTicker (market['symbol'], params);
```
Comment (kroitor) [inline js/coinegg.js]: Oops )

I suggest to drop `fetchTickers`, because by a rule of thumb we stick to one https request per unified call (so methods can be combined in userland, and always behave in a more-or-less unified fashion). We very rarely send more than one call per method, only if we absolutely have to and it cannot be done otherwise. 

Also, we usually don't invent `fetchTickers`, if the exchange in question does not have it. So, in this case the [exchange metainfo](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata) for would contain `has['fetchTickers'] == 'emulated'`. 

However, due to rate-limiting and other factors, we don't emulate `fetchTickers` with multiple consequent calls looping over all markets with `fetchTicker`. It would be hard to account for all possible use-cases, retry-strategies and so on...  

Instead, we just tell the user the actual truth, which is: `exchange.has['fetchTickers'] == false && exchange.has['fetchTicker'] == true` and let the user wrap `fetchTicker` how he wants )

Comment (Legogris) [reply js/coinegg.js]: Makes sense, updating with `fetchTickers` removed as suggested.

Comment (Legogris) [reply js/coinegg.js]: Updated, hope I got it right

Comment (kroitor) [reply js/coinegg.js]: Thx for your help! Appreciate it very much!
