### PR TITLE
Coinspot :: Add missing markets and small sign fix

### LINKED ISSUE #11063: coinspot no ADA-AUD
- OS: MacOS BigSur 11.3.1
- Programming Language version: PHP 7.4
- CCXT version: 1.56.44

### PR DESCRIPTION
**Pull request by carlosmiei**
fixes #11063

### CODE REVIEW

File: js/coinspot.js [hunk 1]
```diff
@@ -265,9 +267,6 @@ module.exports = class coinspot extends Exchange {
     }
 
     sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
```
Comment (carlosmiei) [inline js/coinspot.js:269]: @kroitor although there's only one public method, we don't need credentials to access it, so I've removed this assertion.
If there's anything I'm not seeing, lmk, I'll add it back
image
