### PR TITLE
fix(invalidNonce): handleInvalid nonce to reset subscription, fix #21997

### LINKED ISSUE #21997: Bitget watchorderbook bug - invalid checksum when watch_order_book
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.2.85

### Description

Hello,

When watching for order book in Bitget exchange using ccxt pro (ccxt.pro) and watch_order_book function, I am getting the following error 

`bitget invalid checksum`

This was working fine till 4.2.72 to the best of my knowledge. This bug is similar to the closed issue `https://github.com/ccxt/ccxt/issues/18322` which was closed a year ago approximately. 

```python
orderbook = await exchange.watch_order_book(symbol)
```

### Code

```
  orderbook = await exchange.watch_order_book(symbol)

```

### PR DESCRIPTION
**Pull request by pcriadoperez**
When throwing an invalid nonce, the subscription was not being reset, and therefore the user would receive continuosly an invalidNonce error after the first time it appeared.

Tested by skipping messages randomly inside the handleOrderBook to cause an invalidNonce

### CODE REVIEW

File: ts/src/pro/okx.ts [hunk 1]
```diff
@@ -706,6 +710,8 @@ export default class okx extends okxRest {
         //         ]
         //     }
         //
+        const random = Math.random()
```
Comment (carlosmiei) [inline ts/src/pro/okx.ts:713]: what's this? 😅
