### PR TITLE
Fix currency in 'fetchTransactions'

### LINKED ISSUE #11027: [bitfinex2] Currency always None in transactions
- OS: Ubuntu 21.10
- Programming Language version: Python 3.9
- CCXT version: 1.65.23

The `currency` key is always set to `None` in the transactions returned by `fetch_transactions()`. The `currency` key in `fee` is also `None`.

On a side note, fetching currencies by currency code does not seem to work at all. I have a very recent XLM transactions which does show up as the last transaction (without currency code) in the result of the a `fetch_transactions` call without `code` argument, but it does not show up when I run `fetch_transactions("XLM")`.

```python
import asyncio
from contextlib import asynccontextmanager
from pprint import pprint

import ccxt.async_support as ccxt
from ccxt import AuthenticationError, ExchangeNotAvailable, InvalidNonce, RateLimitExceeded, RequestTimeout


@asynccontextmanager
async def safe_api(api) -> ccxt.Exchange:
    try:
        yield api
    except (
            AuthenticationError,
            ExchangeNotAvailable,
            InvalidNonce,
            RateLimitExceeded,
            RequestTimeout,
    ):
        raise
    finally:
        await api.close()


async def main():
    properties = {...}

    bitfinex = ccxt.bitfinex2(properties)
    await bitfinex.load_markets()

    async with safe_api(bitfinex) as api:
        transactions = await api.fetch_transactions()
        xlm_transactions = await api.fetch_transactions("XLM")
        
    print("Total transactions: ", len(transactions))
    assert all(tx["currency"] is None for tx in transactions)

    print("Last transaction:")
    pprint(transactions[-1])
    print("XLM transactions:")
    pprint(xlm_transactions)


if __name__ == "__main__":
    asyncio.run(main())
```

Output of this script:

```
Total transactions:  10
Last transaction:
{'address': 'abcdefg',
 'addressFrom': None,
 'addressTo': 'abcdefg',
 'amount': 1.00,
 'currency': None,
 'datetime': '2021-12-25T00:00:00.000Z',
 'fee': {'cost': -0.0, 'currency': None, 'rate': None},
 'id': '123456',
 'info': ['123456',
          'XLM',
          'XLM',
          None,
          None,
          '1640390400000',
          '1640390400000',
          None,
          None,
          'COMPLETED',
          None,
          None,
          '1.00',
          '0',
          None,
          None,
          'abcdefg',
          None,
          None,
          None,
          '1234abcdefg',
          None],
 'status': 'COMPLETED',
 'tag': None,
 'tagFrom': None,
 'tagTo': None,
 'timestamp': 1640390400000,
 'txid': '1234abcdefg',
 'type': 'deposit',
 'updated': 1640390400000}
XLM transactions:
[]
```

### PR DESCRIPTION
**Pull request by ttodua**
- Fix currencies in fetchTransactions
- Replaced a commented lines with correct commenting
[ fixes #11027 ]

### CODE REVIEW

File: js/bitfinex2.js [hunk 1]
```diff
@@ -1440,8 +1440,15 @@ module.exports = class bitfinex2 extends bitfinex {
             }
             tag = this.safeString (data, 3);
             type = 'withdrawal';
-        } else {
+        } else if (transactionLength === 22) {
```
Comment (kroitor) [inline js/bitfinex2.js:1443]: Comparing the size of the array to 22 doesn't look totally right to me. Is this intentional?

File: js/bitfinex2.js [hunk 2]
```diff
@@ -1440,8 +1440,15 @@ module.exports = class bitfinex2 extends bitfinex {
...
             id = this.safeString (transaction, 0);
+            if (currency !== undefined) {
+                code = currency['code'];
+            } else {
+                const currencyId = this.safeString (transaction, 1);
+                currency = this.safeCurrency (currencyId, currency);
+                code = currency['code'];
+            }
```
Comment (kroitor) [inline js/bitfinex2.js:1451]: Let's rewrite the above lines 1445-1451, since `if (currency !== undefined)` is already done in `safeCurrency`:

```JavaScript
const currencyId = this.safeString (transaction, 1);
currency = this.safeCurrency (currencyId, currency);
code = currency['code'];
```

File: js/bitfinex2.js (hunk 1 above)
Comment (ttodua) [reply js/bitfinex2.js:1443]: It was intentional in my opinion (even though not directly related to this issue, because in my mind, each object passed to the 'parseXYZ' functions should have its specific deterministic 'if' block, otherwise, it may not be clear what object (from same class or even its derived class) are passed to 'parseXYZ'.
in this specific case, as bitfinex returns array-responses (without keys) the only reliable way to target the 'fetchTransaction' record was to compare to array-size.

But if you think it's not ok, then sure, lets remove and be there only 'else'. (I'll leave this part to you during merge, so I won't re-commit).

**Comment by ljnsn** [comment]
Thanks for the patch!

**Comment by kroitor** [comment]
@ljnsn thx for reporting!
