### PR TITLE
Easier subaccount management for FTX, just by using a parameter in methods | fix #8215 | fix #10794 | fix #9805 | fix #10794 | fix #8383 | fix #6985

### LINKED ISSUE #6985: FTX Endpoint POST subaccounts error "Not logged in"
- OS: Win 10
- Programming Language version: PHP
- CCXT version:  1.28.11

```
<?php

include "ccxt/ccxt.php";

date_default_timezone_set('UTC');

$api_key  = 'XXXXXXX';
$api_secret = 'YYYYYYY';
$exchange = new \ccxt\ftx();
$exchange->apiKey = $api_key;
$exchange->secret = $api_secret;

$param = array ('nickname' =>  'aaa');

echo "<pre>";
var_dump($exchange->private_post_subaccounts($param));
echo "</pre>";

?>```

```
Fatal error:  Uncaught ccxt\ExchangeError: ftx {"error":"Not logged in","success":false}
 in C:\xampp\htdocs\ftx\ccxt\php\ftx.php:1437
Stack trace:
#0 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1429): ccxt\ftx->handle_errors(401, '', 'https://ftx.com...', 'POST', Array, '{"error":"Not l...', Array, Array, '{"nickname":"aa...')
#1 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1195): ccxt\Exchange->fetch('https://ftx.com...', 'POST', Array, '{"nickname":"aa...')
#2 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1199): ccxt\Exchange->fetch2('subaccounts', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('subaccounts', 'private', 'POST', Array)
#4 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(2428): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\ftx\main.php(20): ccxt\Exchange->__call('private_post_su...', Array)
#6 {main}
  thrown in C:\xampp\htdocs\ftx\ccxt\php\ftx.php on line 1437```

Cuando hago la llamada al endpoint de FTX "POST /subaccounts" me da un error como el que se muestra arriba. Sin embargo si llamo al endpoint "POST /subaccounts/update_name" funciona perfectamente.

### LINKED ISSUE #8215: FTX watchOrders returns  "Only have permissions for subaccount test"
`await exchange.watchOrders();` returns ExchangeError ` Only have permissions for subaccount test`
For example `await exchange.watchTrades('BTC/USD');` works without error. 

- OS:  DEBIAN stretch (Docker)
- Programming Language version: NodeJS (v13.12.0)
- CCXT version:  Pro version 0.5.20

**Code to reproduce:**
```
const ccxt = require('ccxt.pro');
async function monitor() {
    const exchange = new ccxt.ftx ({
        enableRateLimit: true,
        apiKey: 'API_KEY',
        secret: 'SECRET_KEY',
        headers: { 'FTX-SUBACCOUNT': 'test' }
    });
    
    // real-time mode
    const limit = 5; // optional
    while (true) {
        try {
            const orders = await exchange.watchOrders();
            console.log (orders) // every update
        } catch (e) {
            console.log (e);
            throw e // uncomment to stop the loop on exceptions
        }
    }
}

monitor(); // ExchangeError: Only have permissions for subaccount test

### LINKED ISSUE #8383: FTX has subaccount in HTTP header
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version: 1.38.87

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
FTX offers subaccounts,so if you want to access private apis in ur subaccounts，u should add 'FTX-SUBACCOUNT' in request headers.FTX's api doc lists below.
image
https://docs.ftx.com/#rest-api
image

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
If not supplied, server response 401

### LINKED ISSUE #9805: Fetching FTX subaccount balances with subaccount API Key fails
Hi, 
I'm trying to fetch balances for an FTX subaccount with an FTX subaccount API key with trade and withdraw permissions and I'm doing something wrong. I can fetch the subaccount balance with the main account key but not with the subaccount key. Am I forgetting to set a header?

- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.54.83

```
import ccxt

main_account_api_key = '<my_main_account_api_key>'
main_account_secret = '<my_main_account_secret>'
sub_account_api_key = '<my_subaccount_api_key>'
sub_account_secret = '<my_subaccount_secret>'

exchange = ccxt.ftx({
    'apiKey': main_account_api_key,
    'secret': main_account_secret,
    'hostname': 'ftx.us',
    'headers': {
        'FTX-SUBACCOUNT': '<my_subaccount>'
    }
})

exchange.private_get_subaccounts_nickname_balances(params={'nickname': '<my_subaccount>'})
# Works with main account key. Subaccount balance returned

exchange.apiKey = sub_account_api_key
exchange.secret = sub_account_secret

exchange.private_get_subaccounts_nickname_balances(params={'nickname': '<my_subaccount>'})
# Fails -> ccxt.base.errors.PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount <my_subaccount>"}

exchange.fetch_balance()
# Fails -> ccxt.base.errors.PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount <my_subaccount>"}
```

Complete traceback for `
exchange.private_get_subaccounts_nickname_balances(params={'nickname': '<my_subaccount>'})` :
```
Traceback (most recent call last):
  File <...>/python3.8/site-packages/ccxt/base/exchange.py", line 597, in fetch
    response.raise_for_status()
  File <...>/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://ftx.us/api/subaccounts/<my-subaccount>/balances
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File <...>/python3.8/site-packages/ccxt/base/exchange.py", line 613, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File <...>/python3.8/site-packages/ccxt/ftx.py", line 1891, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File <...>/python3.8/site-packages/ccxt/base/exchange.py", line 509, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount <my-subaccount>"}
```

### LINKED ISSUE #10794: FTX Only have permissions for subaccount
Hi

1 Created sub account for FTX
2 Created API key for that subaccount with trading permissions
3 When calling `fetch_balance`, getting error:

`"Only have permissions for subaccount trading2"`

How is this possible? The API key and Secret are created for that specific account

ccxt = 1.63.10

### PR DESCRIPTION
**Pull request by ttodua**
Re-citing from previous PR:

I think CCXT should follow the route of being easy to do typical exchange actions. Subaccounts on FTX are quite popular, and that is just another internal functionality. However, at this moment, using subaccounts for FTX is (in my opinion) a bit complicated. User needs to set a non-regular syntax `headers: { 'FTX-SUBACCOUNT': 'testname' }` and user shouldn't be forced to "set headers manually in a very custom way" (like user doesn't need to set headers or whatever while needs to make actions on spot or margin, and the 'method parameters' do the whole thing.

Like that way,  (even thought the FTX API itself works that way) user shouldnt be needed to care at all about "what headers to set to trade on FTX", instead a single parameter (like in other exchange methods 'spot/margin' params do the job) should facilitate trading on FTX from multiple sub-accounts. This will have further benefit, users won't be needed to "initialize" several FTX exchange objects (saving much of resources and userland code handling) and from a single exchange object, users will do everything they want. 

This suggested implementation relies on a property named 'FTX-SUBACCOUNT' passed in 'params' object, like:

```
  const ex = new ccxt.ftx  ({ 
      'apiKey': '......', 
      'secret': '...'
  })
  await ex.loadMarkets();
  console.log(await ex.fetchBalance({'FTX-SUBACCOUNT':'mySubAccountName'}));
  console.log(await ex.fetchBalance());
// 
  console.log(await ex.createorder(.....));
  console.log(await ex.createorder(....., ...,  params: {'FTX-SUBACCOUNT':'mySubAccountName'}));

```

| fix #8215 | fix #10794 | fix #9805 | fix #10794 |  fix #8383 | fix #6985 |

### CODE REVIEW

File: js/ftx.js [hunk 1]
```diff
@@ -2101,6 +2101,13 @@ module.exports = class ftx extends Exchange {
 
     sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
         let request = '/api/' + this.implodeParams (path, params);
+        const signOptions = this.safeValue (this.options, 'sign', {});
+        const headerPrefix = this.safeString (signOptions, this.hostname, 'FTX');
+        const subaccountField = headerPrefix + '-SUBACCOUNT';
+        const chosenSubaccount = this.safeString (params, subaccountField, undefined);
```
Comment (kroitor) [inline js/ftx.js:2107]: We can remove the third argument from here, the default value of safeString is optional.

**Comment by frosty00** [comment]
we could probably unify this even more and just change the parameter name inputted here to `subaccount`

**Comment by kroitor** [comment]
> we could probably unify this even more and just change the parameter name inputted here to `subaccount`

Added that.l
