### PR TITLE
Exchange upgrade - MEXC v3

### LINKED ISSUE #12352: MEXC API v3
https://support.mexc.com/hc/en-001/articles/4474142124953-MEXC-Announcement-on-Launching-Spot-API-V3
Docs: https://mxcdevelop.github.io/apidocs/spot_v3_en/#introduction

### LINKED ISSUE #12534: Issue With Fetching Swap Orders/Trades From MEXC Global
Hi Guys,

I am unable to fetch the orders/trades on the mexc swap exchange. 

When I try to fetch an order that I created, it just gives me an order not found error.
I have pasted the output below as well.
It looks like the fetchOrder function is not complete, it does not check if its spot or swap. 

```
console.log ('CCXT Version:', ccxt.version)
const exchange = new ccxt['mexc']({
    apiKey,
    secret,
});
exchange.options.defaultType = 'swap';
exchange.verbose = true
await exchange.fetchOrder('263687272107482624')
```

```
CCXT Version: 1.77.36
fetch Request:
 mexc GET https://www.mexc.com/open/api/v2/order/query?order_ids=263687272107482624
RequestHeaders:
 {
  ApiKey: apiKey,
  'Request-Time': '1648538539277',
  'Content-Type': 'application/json',
  Signature: signature
}
RequestBody:
 undefined

handleRestResponse:
 mexc GET https://www.mexc.com/open/api/v2/order/query?order_ids=263687272107482624 200 OK
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Length': '22',
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Tue, 29 Mar 2022 07:22:19 GMT',
  'Server-Timing': 'cdn-cache; desc=MISS, edge; dur=217, origin; dur=21'
}
ResponseBody:
 {"code":200,"data":[]}

error: mexc fetchOrder() could not find the order id 263687272107482624 {"name":"OrderNotFound","stack":"OrderNotFound: mexc fetchOrder() could not find the order id 263687272107482624\n    at mexc.fetchOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:2059:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async placeOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\src\\services\\exchange.service.js:142:19)\n    at async Trader.buy (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\src\\services\\scraper.service.js:218:27)","timestamp":"2022-03-29 11:22:19"}
```

Could you please help me out on this issue?

### LINKED ISSUE #12696: MEXC market orders not supported
```
import ccxt
mexc = ccxt.mexc({'apiKey': '...', 'secret': '...'})
exchange.createMarketBuyOrder('TRX/USDT', 1)
```
results in:
```
raise InvalidOrder(self.id + ' createOrder() does not support ' + type + ' order type, specify one of LIMIT, LIMIT_ORDER, POST_ONLY or IMMEDIATE_OR_CANCEL
```

However MEXC API does support market orders.
Issue present in CCXT 1.78.43

### PR DESCRIPTION
**Pull request by ttodua**
* Spot: https://mxcdevelop.github.io/apidocs/spot_v3_en/
* Contracts: https://mxcdevelop.github.io/APIDoc/

[fixes #12352 , fixes #12534, fixes #12696]

### CODE REVIEW

**Comment by ttodua** [comment]
@kroitor PR is ready now with its full (imho) implementation of spot/contracts. passes current tests.

File: js/mexc3.js [hunk 1]
```diff
@@ -0,0 +1,3659 @@
...
+            'ETH': 'ETH',
+            'ERC20': 'ERC20',
+            'BEP20(BSC)': 'BEP20',
+            'TRX': 'TRC20',
+        };
+        return this.safeString (networksById, networkId, networkId);
+    }
+
+    async fetchMarkets (params = {}) {
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('fetchMarkets', undefined, params);
```
Comment (carlosmiei) [inline js/mexc3.js:608]: @ttodua Seems to me that we could distinguish spot and swap markets from the exchange response as marketIds and the response structure are different.

Do you see foresee any trouble if we decided to load swap + spot at the same time?

File: js/mexc3.js [hunk 2]
```diff
@@ -0,0 +1,3659 @@
...
+        };
+        if (limit !== undefined) {
+            request['limit'] = limit;
+        }
+        // if (since !== undefined) {
+        //     request['startTime'] = since; bug in api, waiting for fix
+        // }
+        let trades = undefined;
+        if (market['spot']) {
+            let method = this.safeString (this.options, 'fetchTradesMethod', 'spotPublicGetAggTrades');
```
Comment (carlosmiei) [inline js/mexc3.js:899]: Any reason for making `spotPublicGetAggTrades` the default method? I would say that users are expecting more of what is returned by `spotPublicGetTrades` (regular recent trade info) but I might be missing something here

File: js/mexc3.js [hunk 3]
```diff
@@ -0,0 +1,3659 @@
...
+        const type = undefined;
+        let side = undefined;
+        let takerOrMaker = undefined;
+        let priceString = undefined;
+        let amountString = undefined;
+        let costString = undefined;
+        // if swap
+        if ('v' in trade) {
+            //
+            // spot: fetchTrades
```
Comment (carlosmiei) [inline js/mexc3.js:970]: you meant swap here right?

File: js/mexc3.js [hunk 4]
```diff
@@ -0,0 +1,3659 @@
...
+            //         "t": 1609831235985
+            //     }
+            //
+            timestamp = this.safeInteger (trade, 't');
+            market = this.safeMarket (undefined, market);
+            symbol = market['symbol'];
+            priceString = this.safeString (trade, 'p');
+            amountString = this.safeString (trade, 'v');
+            side = this.parseOrderSide (this.safeString (trade, 'T'));
+            takerOrMaker = 'taker';
```
Comment (carlosmiei) [inline js/mexc3.js:987]: Can we be sure that every trade will be a "taker" one?

Comment (kroitor) [reply js/mexc3.js:987]: Public trades don't really differentiate between `taker` or `maker`. We can assume that all public trades are takers.

File: js/mexc3.js [hunk 5]
```diff
@@ -0,0 +1,3659 @@
...
+            }
+        }
+        return id;
+    }
+
+    async fetchOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const options = this.safeValue (this.options, 'timeframes', {});
+        const timeframes = this.safeValue (options, market['type'], {});
```
Comment (carlosmiei) [inline js/mexc3.js:1129]: This timeframe logic is currently broken because the  "timeframes" object is not yet indexed by market type

https://github.com/ccxt/ccxt/pull/12376/files#diff-321f459daa26ff101cea1bedf2b82d023dcbb2422700f94579df4e193e1323caR273

File: js/mexc3.js [hunk 6]
```diff
@@ -0,0 +1,3659 @@
...
+                        },
+                        'delete': {
+                            'order/cancel': 1,
+                            'order/cancel_by_symbol': 1,
+                            'asset/withdraw': 2,
+                        },
+                    },
+                },
+            },
+            'timeframes': {
```
Comment (carlosmiei) [inline js/mexc3.js:273]: I guess this is a leftover and should be removed, we have the correct "timeframes" object inside options

File: js/mexc3.js [hunk 7]
```diff
@@ -0,0 +1,3659 @@
...
+                        '4h': '4h',
+                        '6h': '6h',
+                        '8h': '8h',
+                        '12h': '12h',
+                        '1d': '1d',
+                        '3d': '3d',
+                        '1w': '1w',
+                        '1M': '1M',
+                    },
+                    'contract': {
```
Comment (carlosmiei) [inline js/mexc3.js:330]: This should be `swap` instead

File: js/mexc3.js [hunk 8]
```diff
@@ -0,0 +1,3659 @@
...
+                            'linear': false,
+                            'inverse': false,
+                        },
+                        'swap': {
+                            'linear': true,
+                            'inverse': false,
+                        },
+                    },
+                },
+                'timeframes': {
```
Comment (carlosmiei) [inline js/mexc3.js:312]: Question, why is this inside options?

File: js/mexc3.js (hunk 4 above)
Comment (carlosmiei) [reply js/mexc3.js:987]: @kroitor thanks for the clarification

File: js/mexc3.js [hunk 9]
```diff
@@ -0,0 +1,3659 @@
...
+            this.safeNumber (ohlcv, 4),
+            this.safeNumber (ohlcv, 5),
+        ];
+    }
+
+    async fetchTickers (symbols = undefined, params = {}) {
+        await this.loadMarkets ();
+        const request = {};
+        if (symbols !== undefined) {
+            request['symbol'] = symbols.join (',');
```
Comment (carlosmiei) [inline js/mexc3.js:1215]: You're using here symbols directly instead of the marketIds 

Example:
```
const marketIds = this.marketIds (symbols);
 request['symbol'] = marketIds.join (',');
```

File: js/mexc3.js [hunk 10]
```diff
@@ -0,0 +1,3659 @@
...
+        }
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('fetchTickers', undefined, params);
```
Comment (carlosmiei) [inline js/mexc3.js:1217]: Also, this is not taking into consideration the provided symbols

File: js/mexc3.js [hunk 11]
```diff
@@ -0,0 +1,3659 @@
...
+        let tickers = undefined;
+        if (marketType === 'spot') {
```
Comment (carlosmiei) [inline js/mexc3.js:1219]: After some tests and looking into the docs, I don't think this "," separation in the URL is valid (see images below). To fetch multiple tickers you omit the symbol so the exchange returns everything and you do the filtering afterward.



image

image

File: js/mexc3.js [hunk 12]
```diff
@@ -0,0 +1,3659 @@
...
+            //         }
+            //     }
+            //
+            tickers = this.safeValue (response, 'data', []);
+        }
+        return this.parseTickers (tickers, symbols);
+    }
+
+    async fetchTicker (symbol, params = {}) {
+        await this.loadMarkets ();
```
Comment (carlosmiei) [inline js/mexc3.js:1279]: this method is pretty much the same as `fetchTickers` but with a symbols array of length 1. So I think we replace this by:

```Javascript
async fetchTicker (symbol, params = {}) { 
    const symbols = [ symbol ];
   return await this.fetchTickers(symbols, params)
}
```

what do you think?

File: js/mexc3.js [hunk 13]
```diff
@@ -0,0 +1,3659 @@
...
+        let baseVolume = undefined;
+        let quoteVolume = undefined;
+        let open = undefined;
+        let high = undefined;
+        let low = undefined;
+        let changePcnt = undefined;
+        let changeValue = undefined;
+        let prevClose = undefined;
+        // if swap
+        if ('timestamp' in ticker) {
```
Comment (carlosmiei) [inline js/mexc3.js:1358]: This condition is fragile because timestamp is an agnostic property and can be added in the future to spot markets. If you really want to split the spot and swap parsing why not use something like `market['symbol']` it is available for both and it's bulletproof

File: js/mexc3.js [hunk 14]
```diff
@@ -0,0 +1,3659 @@
...
+            //         "symbol": "AEUSDT",
+            //         "bidPrice": "0.11001",
+            //         "bidQty": "115.59",
+            //         "askPrice": "0.11127",
+            //         "askQty": "215.48"
+            //       },
+            //     ]
+            //
+        } else if (marketType === 'swap') {
+            throw new BadRequest (this.id + ' fetchBidsAsks() is not available for ' + marketType + ' markets');
```
Comment (carlosmiei) [inline js/mexc3.js:1475]: I would argue that this is more "Not Supported" than a bad request

File: js/mexc3.js (hunk 1 above)
Comment (ttodua) [reply js/mexc3.js:608]: Thanks for notes, I'll start reviewing them today.
about markets combination - in a month or so, they are going to release new Futures Api, so at this moment, I would refrain from merging them, as the structure might need to be changed again in a month or so.  I thought we could wait till that and then decide after new API is integrated.

Comment (kroitor) [reply js/mexc3.js:608]: @ttodua let's prioritize this PR after solving Kraken if possible. 

> about markets combination - in a month or so, they are going to release new Futures Api, so at this moment, I would refrain from merging them, as the structure might need to be changed again in a month or so. I thought we could wait till that and then decide after new API is integrated.

I suggest that we implement the loading of all types at once for now and later rewrite it when the exchange adds a new version of the API. It could take a month or longer before that happens, so we should not wait in this case.

File: js/mexc3.js (hunk 2 above)
Comment (ttodua) [reply js/mexc3.js:899]: yes, in most cases we use not `/trades`, but `/aggTrades`  endpoint (iirc , you can look through binance's implementation of fetchTrades, and it's same there). the reason behind that is that, getting granular detailed trades required much higher rate limit (i.e. 5x times more) and is not any much different (in binance docs it's explained), as aggTrades satisfies probably 99.9% cases ( and same applies to mexc and other exchanges) .

File: js/mexc3.js [hunk 15]
```diff
@@ -0,0 +1,3659 @@
...
+        const market = this.market (symbol);
+        if (market['spot']) {
+            return await this.createSpotOrder (market, type, side, amount, price, params);
+        } else if (market['swap']) {
+            return await this.createSwapOrder (market, type, side, amount, price, params);
+        }
+    }
+
+    async createSpotOrder (market, type, side, amount, price = undefined, params = {}) {
+        const symbol = market['symbol'];
```
Comment (carlosmiei) [inline js/mexc3.js:1492]: I can't create market orders although this seems to be following the docs spec, waiting on a MEXC clarification
image

File: js/mexc3.js [hunk 16]
```diff
@@ -0,0 +1,3659 @@
...
+            'price': price, // TODO: should we do this?
+            'amount': amount,
+        });
+    }
+
+    async createSwapOrder (market, type, side, amount, price = undefined, params = {}) {
+        await this.loadMarkets ();
+        const symbol = market['symbol'];
+        const openType = this.safeInteger (params, 'openType');
+        if (openType === undefined) {
```
Comment (carlosmiei) [inline js/mexc3.js:1531]: isn't it a bit more intuitive to require a "margin" parameter and convert it to `openType` internally? Also if not provided can't we assume a default value?

File: js/mexc3.js [hunk 17]
```diff
@@ -0,0 +1,3659 @@
...
+            throw new ArgumentsRequired (this.id + ' createSwapOrder() requires an integer openType parameter, 1 for isolated margin, 2 for cross margin');
+        }
```
Comment (carlosmiei) [inline js/mexc3.js:1533]: For some reason I could not figure out yet I can't also create swap Orders

Output:

```
mexc3.createOrder (LTC/USDT:USDT, limit, 1, 0.5, 50, [object Object])
fetch Request:
 mexc3 POST https://contract.mexc.com/api/v1/private/order/submit 
RequestHeaders:
RequestBody:
 {"symbol":"LTC_USDT","vol":0.5,"side":1,"type":1,"openType":2,"price":50} 

handleRestResponse:
 mexc3 POST https://contract.mexc.com/api/v1/private/order/submit 200 OK 
ResponseHeaders:
ResponseBody:
 {"success":false,"code":1002,"message":"Contract not allow place order!"} 

InvalidOrder mexc3 {"success":false,"code":1002,"message":"Contract not allow place order!"}
---------------------------------------------------
[InvalidOrder] mexc3 {"success":false,"code":1002,"message":"Contract not allow place order!"}

    at throwBroadlyMatchedException  ../../js/base/Exchange.js:647         throw new broad[broadKey] (message)                                             
    at handleErrors                  ../../js/mexc3.js:3659                this.throwBroadlyMatchedException (this.exceptions['broad'], body, feedback);   
    at                               ../../js/base/Exchange.js:717         const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
    at processTicksAndRejections     node:internal/process/task_queues:96                                                                                  
    at async timeout                 ../../js/base/functions/time.js:203   return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
    at createSwapOrder               ../../js/mexc3.js:1605                const response = await this[method] (this.extend (request, params));            
    at createOrder                   ../../js/mexc3.js:1492                return await this.createSwapOrder (market, type, side, amount, price, params);  
    at async main                    cli.js:269                            const result = await exchange[methodName] (... args)                            

mexc3 {"success":false,"code":1002,"message":"Contract not allow place order!"}
```

File: js/mexc3.js [hunk 18]
```diff
@@ -0,0 +1,3659 @@
...
+            //         ]
+            //     }
+            //
+            const data = this.safeValue (response, 'data');
+            return this.parseOrders (data, market);
+        }
+    }
+
+    async fetchOpenOrders (symbol = undefined, since = undefined, limit = undefined, params = {}) {
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('fetchOpenOrders', undefined, params);
```
Comment (carlosmiei) [inline js/mexc3.js:1880]: When calling `fetchOpenOrders` for the `swap` type ends up calling `fetchOrdersByState` and the latter calls `fetchOrders`.

The problem is that we're losing the marketType in the middle of this chain and `fetchOrder` assumes the `spot` market resulting in an error

As you can see in the image on line 1940 we omit it from params and then on line 1952 we call `fetchOrders` but `query` does not have the type anymore
image

File: js/mexc3.js [hunk 19]
```diff
@@ -0,0 +1,3659 @@
...
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('cancelOrder', undefined, params);
+        await this.loadMarkets ();
+        const request = {};
+        let market = undefined;
+        if (symbol !== undefined) {
+            market = this.market (symbol);
+            request['symbol'] = market['id'];
+        }
+        let data = undefined;
+        if (marketType === 'spot' || (market && market['spot'])) {
```
Comment (carlosmiei) [inline js/mexc3.js:1961]: As suggested before, If you replace all occurrences of 

```
const [ marketType, query ] = this.handleMarketTypeAndParams ('methodName', undefined, params);
````
by

```Javascript
const market = symbol !== undefined this.symbol(market) : undefined
const [ marketType ] = this.handleMarketTypeAndParams ('methodName', market, params);
```
then you can simply replace all of these conditions  by:

```Javascript
if (marketType !== 'spot) {
(...)
}
```

File: js/mexc3.js [hunk 20]
```diff
@@ -0,0 +1,3659 @@
...
+        //         "openType": "1",
+        //         "state": "1",
+        //         "orderType": "1",
+        //         "errorCode": "0",
+        //         "createTime": "1648984276000",
+        //         "updateTime": "1648984276000",
+        //     }
+        //
+        let id = undefined;
+        if (typeof order === 'string') {
```
Comment (carlosmiei) [inline js/mexc3.js:2181]: When the order is a string only should we pass it to `parseOrder`? Even if we do it we should return right away otherwise this will crash on python and PHP because `safeMethods` assume they'll get an object/dict not a string

File: js/mexc3.js [hunk 21]
```diff
@@ -0,0 +1,3659 @@
...
+    }
+
+    async addMargin (symbol, amount, params = {}) {
+        return await this.modifyMarginHelper (symbol, amount, 'ADD', params);
+    }
+
+    async setLeverage (leverage, symbol = undefined, params = {}) {
+        const positionId = this.safeInteger (params, 'positionId');
+        if (positionId === undefined) {
+            throw new ArgumentsRequired (this.id + ' setLeverage() requires a positionId parameter');
```
Comment (carlosmiei) [inline js/mexc3.js:2588]: Can't we choose between providing a positionId or openType+symbol+positionType?
image

File: js/mexc3.js [hunk 22]
```diff
@@ -0,0 +1,3659 @@
...
+        // TODO: add support for all aliases here
+        result = this.safeValue (response, rawNetwork);
+        if (result === undefined) {
+            throw new InvalidAddress (this.id + ' fetchDepositAddress() cannot find ' + network + ' deposit address for ' + code);
+        }
+        return result;
+    }
+
+    async fetchDeposits (code = undefined, since = undefined, limit = undefined, params = {}) {
+        await this.loadMarkets ();
```
Comment (carlosmiei) [inline js/mexc3.js:3008]: From my tests, I don't think this is working as is. When we provide a code let's say USDT we have to attach the network to it (although I did not find any mention in the docs regarding that).

So a valid request would be

```
request['currency'] = 'USDT-TRX';

```
Please check this output:

```
 node cli.js mexc3 fetchDeposits "USDT" --verbose
Debugger attached.
2022-04-22T16:47:44.066Z
Node.js: v16.13.2
CCXT v1.77.63
mexc3.fetchDeposits (USDT)
fetch Request:
 mexc3 GET https://www.mexc.com/open/api/v2/asset/deposit/list?currency=USDT-TRX 
RequestHeaders:

RequestBody:
 undefined 

handleRestResponse:
 mexc3 GET https://www.mexc.com/open/api/v2/asset/deposit/list?currency=USDT-TRX 200 OK 
ResponseHeaders:
ResponseBody:
 {"code":200,"data":{"page_size":20,"total_page":1,"total_size":2,"page_num":1,"result_list":[{"currency":"USDT-TRX","amount":61.984632,"fee":0.0,"confirmations":40,"address":"TGKyBGx7m3QGNJctddF1eEr7eVMJQB3mfC","state":"SUCCESS","tx_id":"12b9bcd2aefe52f686bc0a3e73bc211c699f8f47aedcd774252dee4a05475870","require_confirmations":20,"create_time":"2022-04-22T15:52:59.000+00:00","update_time":"2022-04-22T15:53:00.000+00:00"},{"currency":"USDT-TRX","amount":150.0,"fee":0.0,"confirmations":40,"address":"TGKyBGx7m3QGNJctddF1eEr7eVMJQB3mfC","state":"SUCCESS","tx_id":"0438e31941fcfaada5ff91d3880485135390d7dc19d459b0709deeba908a5644","require_confirmations":20,"create_time":"2022-04-22T09:22:59.000+00:00","update_time":"2022-04-22T09:23:00.000+00:00"}]}} 

2022-04-22T16:47:51.132Z iteration 0 passed in 385 ms

id |                                                             txid |     timestamp |                 datetime | network |                            address | addressTo | addressFrom | tag | tagTo | tagFrom |    type |    amount | currency | status |       updated |                          fee
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   | 0438e31941fcfaada5ff91d3880485135390d7dc19d459b0709deeba908a5644 | 1650619379000 | 2022-04-22T09:22:59.000Z |   TRC20 | TGKyBGx7m3QGNJctddF1eEr7eVMJQB3mfC |           |             |     |       |         | deposit |       150 |     USDT |     ok | 1650619380000 | {"cost":0,"currency":"USDT"}
   | 12b9bcd2aefe52f686bc0a3e73bc211c699f8f47aedcd774252dee4a05475870 | 1650642779000 | 2022-04-22T15:52:59.000Z |   TRC20 | TGKyBGx7m3QGNJctddF1eEr7eVMJQB3mfC |           |             |     |       |         | deposit | 61.984632 |     USDT |     ok | 1650642780000 | {"cost":0,"currency":"USDT"}
2 objects
Waiting for the debugger to disconnect...
```

File: js/mexc3.js [hunk 23]
```diff
@@ -0,0 +1,3659 @@
...
+        const market = this.market (symbol);
+        const request = {
+            'symbol': market['id'],
+        };
+        const response = await this.fetchPositions (undefined, this.extend (request, params));
+        return this.safeValue (response, 0);
+    }
+
+    async fetchPositions (symbols = undefined, params = {}) {
+        await this.loadMarkets ();
```
Comment (carlosmiei) [inline js/mexc3.js:3217]: this symbols parameter is not being used, if the exchange returns every position shouldn't we use it in the end to filter them out?

File: js/mexc3.js [hunk 24]
```diff
@@ -0,0 +1,3659 @@
...
+
+    sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
+        const [ section, access ] = api;
+        [ path, params ] = this.resolvePath (path, params);
+        let url = undefined;
+        if (section === 'spot') {
+            url = this.urls['api'][section][access] + '/api/' + this.version + '/' + path;
+            let paramsEncoded = '';
+            if (access === 'private') {
+                params['timestamp'] = Date.now ();
```
Comment (carlosmiei) [inline js/mexc3.js:3580]: `  Date.now (); ` breaks the transpiled languages please use `this.milliseconds ();` instead

File: js/mexc3.js [hunk 25]
```diff
@@ -0,0 +1,3659 @@
...
+                params['recvWindow'] = this.safeInteger (this.options, 'recvWindow', 5000);
+            }
+            if (Object.keys (params).length) {
+                paramsEncoded = this.urlencode (params);
+                url += '?' + paramsEncoded;
+            }
+            if (access === 'private') {
+                this.checkRequiredCredentials ();
+                const signature = this.hmac (this.encode (paramsEncoded), this.encode (this.secret), 'sha256');
+                url += '&signature=' + signature;
```
Comment (carlosmiei) [inline js/mexc3.js:3590]: In PHP this is translated to `&$signature=` (with the $) breaking the signing.

You can do instead:
`url += '&' + 'signature=' + signature;`

File: js/mexc3.js (hunk 3 above)
Comment (ttodua) [reply js/mexc3.js:971]: yes , right, must be a mistake

File: js/mexc3.js (hunk 6 above)
Comment (ttodua) [reply js/mexc3.js:273]: no, it's not leftover. I'll drop a link for more clarification, this was confusing to me too before I understood the reason behind this.
( here link: https://discord.com/channels/690203284119617602/921046068555313202/957697009324789801 )

so, in case when there are 2+ market types with possible different timeframe values-groups, then in main `options.timeframes` object, we set unified-to-exchange-specific mappings. i suggest read through Igor's comments, and if you'll have a bit doubts in understanding, I'll write-up small paragraph, probalby to be added in manuals.

File: js/mexc3.js (hunk 7 above)
Comment (ttodua) [reply js/mexc3.js:330]: good catch!

File: js/mexc3.js (hunk 9 above)
Comment (ttodua) [reply js/mexc3.js:1216]: good catch! 
swaps needed additional change too. tnx

File: js/mexc3.js (hunk 10 above)
Comment (ttodua) [reply js/mexc3.js:1218]: I think it's expected way for multiple symbols. (but if we load both swap & spot together, then it should be changed).

@kroitor what should we do in plural symbols cases? i thought we are skipping them for hMTAP. should i detect at least one symbol (market) and provide it to hMTAP?

File: js/mexc3.js (hunk 9 above)
Comment (ttodua) [reply js/mexc3.js:1216]: we have simplified method for it  `this.marketIds (symbols)`.

File: js/mexc3.js (hunk 11 above)
Comment (ttodua) [reply js/mexc3.js:1220]: yes right, as noted above, the request was incorrect from the beggining, i don't remind the reason, probably missed when integrated swaps.

File: js/mexc3.js (hunk 10 above)
Comment (kroitor) [reply js/mexc3.js:1218]: I would ignore the `symbols` argument in the input phase, would use the defaultType to fetch the tickers that we can fetch in no more than one call, and then the filtering by symbols is done in parseTickers.
We definitely should not send the unified `symbols` as is to the exchange. They must be transformed to market ids. But since we can't mix them, we can ignore them in the request and handle them in the response.
Alternatively, we can try to check if there's just one unique market type among all symbols, but I would keep that out for now.

File: js/mexc3.js (hunk 12 above)
Comment (ttodua) [reply js/mexc3.js:1280]: yes, right, they are same endpoints, however because of I was expecting to wait for new swap api, i've not removed the fetchTicker implementation logic, but as noted already , we will not wait for new API, so i'll route them through fetchTickers now.

Comment (ttodua) [reply js/mexc3.js:1280]: one nuance is that `fetchTickers` (or any plural method) shouldn't have a body where there happens cheching whether one symbol is being called or not (it's not plural methods desired implementation), but in this case I think it will be ok as you say. @kroitor  do you confirm, can I route fT through fTs?

Comment (kroitor) [reply js/mexc3.js:1280]: I would keep them separate for now because of the defaultType thing in fetchTickers.

File: js/mexc3.js (hunk 17 above)
Comment (kroitor) [reply js/mexc3.js:1534]: According to the info from the exchange techs:

> BTC_USDT ETH_USDT LTC_USDT has not been opened yet

Try any other symbol.

File: js/mexc3.js (hunk 12 above)
Comment (ttodua) [reply js/mexc3.js:1280]: another nuance is that singular fetchX methods might be provided with `method` prop in params, which means user might need to call specific `method` (i.e. privateGetWhatever) for that singular fetchX method, or even set different `defaultType` under options for that singular method. so in those cases, singular method should have it's own implementation. 
but, again, in this particular case, there seems no such issue, and can be routed.

File: js/mexc3.js (hunk 20 above)
Comment (kroitor) [reply js/mexc3.js:2182]: In some cases like these we do pass arrays/strings in place of dicts, parseOrder will handle that. Most often, the string is just an order id.

File: js/mexc3.js (hunk 22 above)
Comment (kroitor) [reply js/mexc3.js:3010]: This aspect of networks is not entirely unified yet, check huobi.js, okx.js, mexc.js (v1) for reference.
In short, the unified `currency` structure must have a `networks` subdictionary. The networks codes should be translated to exchange-specific network names and back in methods like withdraw, fetchWithdrawals, fetchDeposits or fetchDepositAddress and related parsing methods. We also have a more or less unified `network` param. And some unified network identifiers. This is still a work in progress (in its early stage).

File: js/mexc3.js (hunk 17 above)
Comment (kroitor) [reply js/mexc3.js:1535]: We could probably use BadSymbol in this case, cause the order is valid, but the symbol is not tradeable.
I would add more comments here and a map of "not opened" contracts in the options, for a more meaningful exception message and to avoid further confusion among the devs and users.

File: js/mexc3.js (hunk 13 above)
Comment (ttodua) [reply js/mexc3.js:1315]: right, but are we sure market is always available? the signature (market = undefiend) probably suggests that we shouldn't rely that market is always defined. let me check again, maybe you are right.

Comment (ttodua) [reply js/mexc3.js:1315]: i've replaced that with `if (market['swap'] || 'timestamp' in ticker)` . they have recently released the spot-api so they not be going to change it in near future probably. anyway, per your suggestion, if symbol is present, it will not fail 👍

File: js/mexc3.js [hunk 26]
```diff
@@ -0,0 +1,3659 @@
...
+            'average': undefined,
+            'baseVolume': baseVolume,
+            'quoteVolume': quoteVolume,
+            'info': ticker,
+        }, market, false);
+    }
+
+    async fetchBidsAsks (symbols = undefined, params = {}) {
+        await this.loadMarkets ();
+        const [ marketType, query ] = this.handleMarketTypeAndParams ('fetchBidsAsks', undefined, params);
```
[the remark this answers is not in the document]
Comment (ttodua) [reply js/mexc3.js:1416]: good note, i'll amend

File: js/mexc3.js (hunk 14 above)
Comment (ttodua) [reply js/mexc3.js]: right !

File: js/mexc3.js (hunk 17 above)
Comment (ttodua) [reply js/mexc3.js:1564]: @kroitor should I wait , will you be pushing changes for this in the PR?

Comment (kroitor) [reply js/mexc3.js:1564]: @ttodua It's ok, i'll get to it later.

File: js/mexc3.js (hunk 13 above)
Comment (carlosmiei) [reply js/mexc3.js]: @ttodua From what I could test symbol is always available on the response and from that we can always infer the market regardless if it's passed to `parseTicker` or not 🙁

Comment (kroitor) [reply js/mexc3.js]: > @ttodua From what I could test symbol is always available on the response and from that we can always infer the market regardless if it's passed to `parseTicker` or not 🙁

If the symbol is always available, then we can **almost** always infer the market from it, except for cases when a new market is listed that we don't have in exchange.markets_by_id.

File: js/mexc3.js (hunk 23 above)
Comment (ttodua) [reply js/mexc3.js:3253]: yes, that's right. However, `parsePositions` base method [PR ](https://github.com/ccxt/ccxt/pull/12750) was submitted parallely, and it's signa ture yet is not defined. so, we need to have that method merged in base at first.
@kroitor whenever you have time, advise me - should I wait that PR to be merged or use parsePositions local method in mexc3 ?

File: js/mexc3.js (hunk 16 above)
Comment (ttodua) [reply js/mexc3.js:1567]: pushed. I'll resolve this one.

File: js/mexc3.js (hunk 24 above)
Comment (ttodua) [reply js/mexc3.js:3616]: right ! done.

File: js/mexc3.js (hunk 25 above)
Comment (ttodua) [reply js/mexc3.js]: done !  also, seems other exchanges also have same problem when you search `&signature`  - do they also break? if you have time, you can PR for them too , one or two cases .

File: js/mexc3.js (hunk 19 above)
Comment (ttodua) [reply js/mexc3.js:2009]: good note! you can go on with them

File: js/mexc3.js (hunk 18 above)
Comment (ttodua) [reply js/mexc3.js:1928]: haven't revised - left for you 👍

File: js/mexc3.js (hunk 15 above)
Comment (ttodua) [reply js/mexc3.js:1528]: left for you too.

File: js/mexc3.js (hunk 8 above)
Comment (ttodua) [reply js/mexc3.js:312]: I'll mark this as resolved, as discussed above.

File: js/mexc3.js (hunk 22 above)
Comment (ttodua) [reply js/mexc3.js:3056]: also one note about deposits - i've explained that in telegram chat - they have different chain names for same (i.e. bsc) network accross different coins, so 'fetchDeposits' might misbehave if you will append same chain name to all i.e. bsc networks, like:
`coinname-BSC` as each coin might need to save their specific chain-title in instance property, and extract those chain-titles inside `fetchDeposits` for that specific coin name... shortly, a bit tricky thing.

File: js/mexc3.js (hunk 21 above)
Comment (carlosmiei) [reply js/mexc3.js]: done

File: js/mexc3.js (hunk 15 above)
Comment (carlosmiei) [reply js/mexc3.js:1532]: done

File: js/mexc3.js [hunk 27]
```diff
@@ -3094,8 +3094,15 @@ module.exports = class mexc3 extends Exchange {
         };
         let currency = undefined;
         if (code !== undefined) {
+            const rawNetwork = this.safeString (params, 'network');
```
Comment (ttodua) [inline js/mexc3.js:3094]: I think `network` might need to be recognized as unified network name too (not only exchange specific network-id), and that should be transformed into rawNetwork. i.e. if user calls `fetchDeposits ('USDT', ..,.., {network:'TRC20'})`  (or other unified names [mentioned here](https://discord.com/channels/690203284119617602/921046068555313202/968499931193155604)) then it should be transformed into `TRX` or whatever exchange specific chain-name is for mexc.  

--update--
It's a bit tricky, because mexc has different chain-names for same network, and maybe you might leave your implementation as is.

Comment (carlosmiei) [reply js/mexc3.js:3094]: @ttodua the thing is for most of the other cases mexc uses TRC20, so supposedly that would be the exchange-specific id, however for this method requires "TRX" so we don't have yet a safe way to convert unified network <-> exchange specific network

Comment (kroitor) [reply js/mexc3.js:3094]: > @ttodua the thing is for most of the other cases mexc uses TRC20, so supposedly that would be the exchange-specific id, however for this method requires "TRX" so we don't have yet a safe way to convert unified network <-> exchange specific network

@carlosmiei see how that is done in okx/huobi in withdraw()/fetchDepositAddres()

File: js/mexc3.js (hunk 17 above)
Comment (samgermain) [reply js/mexc3.js:1600]: I haven't been able to find any swap symbols that don't return this error, I think that we should disable `createOrder` for swap, and also remove `options["unavailableContracts"]` for the purpose of avoiding errors/confusion when/if they ever do fix their api and allow the creation of swap orders
