### PR TITLE
Bitfinex v2 fetchTransactions / movements endpoint issue fix

### LINKED ISSUE #10172: bitfinex2 throws currency: invalid on fetchTransactions
- OS: MacOS
- Programming Language version: node v16.8.0
- CCXT version: ccxt@1.57.68

Basically `bitfinex2` fetchTransactions does not seem to work. 

```js
const exchange = new ccxt.bitfinex2({
  // ...
})
const currencies = await exchange.fetchCurrencies()
for (const currency in currencies) {
	const code = currencies[currency].code
	await exchange.fetch(code, since, limit)
}
```

Throws this, e.g. with parameter AAVE or BTC or really any currency code:

```
Bitfinex fetchTransactions BTC 1420070400000 2015-01-01T00:00:00.000Z 100 BadRequest: bitfinex2 currency: invalid
    at bitfinex2.throwExactlyMatchedException (/Users/luca/projects/exchanges/node_modules/ccxt/js/base/Exchange.js:595:19)
    at bitfinex2.handleErrors (/Users/luca/projects/exchanges/node_modules/ccxt/js/bitfinex2.js:1648:18)
    at /Users/luca/projects/exchanges/node_modules/ccxt/js/base/Exchange.js:657:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/Users/luca/projects/exchanges/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async bitfinex2.fetchTransactions (/Users/luca/projects/exchanges/node_modules/ccxt/js/bitfinex2.js:1476:26) {
  constructor: [class BadRequest extends ExchangeError]
}

```

I'm using `bitfinex2` as it seems that the opposite behaviour applies to `bitfinex` as I can fetch the transactions but not the trades. Is this a known issue? Or am I doing something wrong? The same code works for other exchanges.

### PR DESCRIPTION
**Pull request by ttodua**
This specific endpoint  ( https://docs.bitfinex.com/reference#rest-auth-movements ) requires the currency code without prepended chars.
( Also, I've added a temporary reference link to the partial code i've stared, but atm cant proceed with it, and will return to it later. )

[ fixes #10172 ]

### CODE REVIEW

**Comment by ttodua** [comment]
@kroitor  do you know why appveyor fails?

**Comment by kroitor** [comment]
@ttodua i've fixed the appveyor, is there something wrong with this PR? Why was it closed?

File: js/bitfinex2.js [hunk 1]
```diff
@@ -1491,7 +1491,7 @@ module.exports = class bitfinex2 extends bitfinex {
         let method = 'privatePostAuthRMovementsHist';
         if (code !== undefined) {
             currency = this.currency (code);
-            request['currency'] = currency['id'];
+            request['currency'] = currency['code'].toUpper ();
```
Comment (kroitor) [inline js/bitfinex2.js:1494]: This is a bit wrong – we should never send unified CCXT codes and CCXT symbols to the exchange as is.
Also, the code of the currency must always be uppercase, if that's not the case, it has to be fixed as well.
We send out exchange-specific ids, and we receive exchange-specific ids, so, it should be `currency['id']` here. We use unified symbols internally. Also, it does not make much sense to uppercase it every single time, instead I suggest adding `uppercaseId` to the currency structure once upon parsing it, if that is absolutely necessary.

**Comment by ttodua** [comment]
@kroitor I've had implemented the 'code' (uppercase is not relevant to say frankly) and not 'id' was the reason of PR, as documented in https://docs.bitfinex.com/reference#rest-auth-movements  there you see, that `.../movements/BTC/...` the code needs to be there and not `id` (as bitfinex2 currency ids are like `fBTC` , `fUSDT` ---prepended with `f`) and that caused https://github.com/ccxt/ccxt/issues/10172 issue (`movements` endpoint will be erroring again with 'id' approach)
