### PR TITLE
fix(proxy) - explanations

### LINKED ISSUE #20686: I get errors when I try to use proxy with ccxt
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.1.28

### Description

I am trying to connect binance (also tried other exchanges) and retrieve my account balance by using a proxy. I've tested with http, https, socks5 proxies and with different implementations but even I can make any call without proxy, when I use proxy it gives error.

Could anyone help me about it?

### Code

```
const ccxt = require("ccxt");
const binance = new ccxt.binance({
  });
binance.proxyUrl = "https://84.39.112.144:3128/";
const ticker = await binance.fetchTicker('BTC/USDT');
console.log("ticker",ticker)
```
This code gives that error:
image

also this one gives the same error
```
 binance.socksProxy = "socks5://199.187.210.54:4145/";
```
I also tried this implementation it doesn't give any error but it seems it doesn't make request via proxy but make the request with my own IP. (I added IP access restriction to my API Key but it still makes the request)
```
 const binance = new ccxt.binance({
            proxies: "http://103.231.78.36:80/"
        });
```

### PR DESCRIPTION
**Pull request by ttodua**
last comment fix #20686

Users should be aware that from browser-side JS, they can't use proxies (because proxy modules rely on 'net & http' native nodejs modules and there does not exist browser-side support for JS proxy functionality yet).

### CODE REVIEW

File: ts/src/base/Exchange.ts [hunk 1]
```diff
@@ -1043,6 +1043,10 @@ export default class Exchange {
 
     setProxyAgents (httpProxy, httpsProxy, socksProxy) {
         let chosenAgent = undefined;
+        // in browser-side, proxy modules are not supported in 'fetch/ws' methods
+        if (!isNode && (httpProxy || httpsProxy || socksProxy)) {
+            throw new NotSupported (this.id + ' - proxies in browser-side projects are not supported. You have several choices: [A] Use `exchange.proxyUrl` property to redirect through local/remote cors-proxy snippet (find sample file named "sample-local-proxy-server-with-cors" in https://github.com/ccxt/ccxt/tree/master/examples/ folder, which includes sample for REST requests) [B] override `exchange.fetch` && `exchange.watch` methods to send request through your custom setup local/remote corst proxy server');
```
Comment (carlosmiei) [inline ts/src/base/Exchange.ts:1048]: > property to redirect through local/remote cors-proxy snippet

this sentence does not make sense, what is snippet here? we should replace it with server or just remove it

Comment (ttodua) [reply ts/src/base/Exchange.ts]: ah, it should have been 'server' not 'snippet'.  edited
