### PR TITLE
bybit - fetchOrders - fix #16822

### LINKED ISSUE #16822: Bybit v3 fetchOrders without symbol: 'settleCoin' not supported
### Operating System

OS X 13

### Programming Languages

JS

### CCXT Version

2.7.78

### Description

Hi,

`fetchOrders` without a symbol fails with the error `bybit {"retCode":10001,"retMsg":"params error: settle_coin not support","result":{},"retExtInfo":{},"time":1676112208522}`.

CCXT adds the `settleCoin` param to the request which isn't documented in the Bybit API docs and apparently causes the error above: https://bybit-exchange.github.io/docs/derivatives/contract/order-list

Calling the implicit API `privateGetContractV3PrivateOrderList` without the settleCoin param works fine.

### Code

```
handleRestResponse:
 bybit GET https://api.bybit.com/contract/v3/private/order/list?api_key=XXX&recv_window=5000&settleCoin=USDT&timestamp=1676112208286&sign=7e66a4bca5344825013eeb04b160c2867d3242a4ea6ff2fa81d4fccde74679f6 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Length': '115',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Sat, 11 Feb 2023 10:43:28 GMT',
  Expires: 'Sat, 11 Feb 2023 10:43:28 GMT',
  Pragma: 'no-cache',
  Ret_code: '10001',
  Server: 'Openresty',
  Timenow: '1676112208522',
  Traceid: '5b38b547e9e6184f1421066c1176a9ba'
}
ResponseBody:
 {"retCode":10001,"retMsg":"params error: settle_coin not support","result":{},"retExtInfo":{},"time":1676112208522}
```

### PR DESCRIPTION
**Pull request by pcriadoperez**
We were passing settleCoin as a parameter when it was not a parameter of this end point, and was throwing an error. This PR removes the parameter to allow the endpoint to be called succesfully.

Ref: https://bybit-exchange.github.io/docs/derivatives/contract/order-list

### CODE REVIEW

**Comment by carlosmiei** [comment]
[🤖 TestsManager 🤖  Id: 63e789a2ff417f917201ae56]
 ```

Testing { exchanges: ["bybit"], symbol: "all", keys: { '--js': true, '--php': false, '--python': false, '--python-async': true, '--php-async': false }, exchangeSpecificFlags: { '--sandbox': false, '--verbose': false, '--private': false, '--privateOnly': true }, maxConcurrency: 5 } (run-tests.js:274)
[100%] Testing bybit FAIL (testExchange @ run-tests.js:191)

FAILED bybit (JavaScript): (explain @ run-tests.js:209)

TESTING { exchange: 'bybit', symbol: 'all' } 

414 symbols BTC/ETH, BTC/USDT, ETH/BTC, LTC/BTC + more...
SYMBOL: BTC/USDT
Testing bybit signIn ( )
Testing bybit fetchBalance ( )
fetching balance...
fetched balance items: 6
Testing bybit fetchAccounts ( )
Testing bybit fetchTransactionFees ( )
Testing bybit fetchTradingFees ( )
Testing bybit fetchStatus ( )
Testing bybit fetchOrders ( BTC/USDT )
Not supported bybit fetchOrders ( BTC/USDT )
Testing bybit fetchOpenOrders ( BTC/USDT )
fetched 0 open orders
Testing bybit fetchClosedOrders ( BTC/USDT )
fetched 0 closed orders, testing each
Testing bybit fetchMyTrades ( BTC/USDT )
fetched 0 trades
Testing bybit fetchLeverageTiers ( BTC/USDT )
Testing bybit fetchOpenInterestHistory ( BTC/USDT )
BadRequest bybit fetchOpenInterestHistory() symbol does not support market BTC/USDT
[BadRequest] bybit fetchOpenInterestHistory() symbol does not support market BTC/USDT
BadRequest: bybit fetchOpenInterestHistory() symbol does not support market BTC/USDT
    at bybit.fetchOpenInterestHistory (/home/ec2-user/rust-tester/ccxt/js/bybit.js:6679:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.module.exports [as fetchOpenInterestHistory] (/home/ec2-user/rust-tester/ccxt/js/test/Exchange/test.fetchOpenInterestHistory.js:12:37)
    at async test (/home/ec2-user/rust-tester/ccxt/js/test/test.js:132:20)
    at async runPrivateTests (/home/ec2-user/rust-tester/ccxt/js/test/test.js:363:5)
    at async testExchange (/home/ec2-user/rust-tester/ccxt/js/test/test.js:338:9)
    at async tryAllProxies (/home/ec2-user/rust-tester/ccxt/js/test/test.js:415:13)
    at async main (/home/ec2-user/rust-tester/ccxt/js/test/test.js:455:9) {
  constructor: [class BadRequest extends ExchangeError]
} BadRequest: bybit fetchOpenInterestHistory() symbol does not support market BTC/USDT
    at bybit.fetchOpenInterestHistory (/home/ec2-user/rust-tester/ccxt/js/bybit.js:6679:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.module.exports [as fetchOpenInterestHistory] (/home/ec2-user/rust-tester/ccxt/js/test/Exchange/test.fetchOpenInterestHistory.js:12:37)
    at async test (/home/ec2-user/rust-tester/ccxt/js/test/test.js:132:20)
    at async runPrivateTests (/home/ec2-user/rust-tester/ccxt/js/test/test.js:363:5)
    at async testExchange (/home/ec2-user/rust-tester/ccxt/js/test/test.js:338:9)
    at async tryAllProxies (/home/ec2-user/rust-tester/ccxt/js/test/test.js:415:13)
    at async main (/home/ec2-user/rust-tester/ccxt/js/test/test.js:455:9) (explain @ run-tests.js:212)

WARN bybit (Python 3 Async): (explain @ run-tests.js:210)

bybit BTC/USDT fetchOrders() failed with: bybit fetchOrders() does not support spot markets, use exchange.fetch_open_orders() and exchange.fetchClosedOrders() instead
/home/ec2-user/rust-tester/ccxt /home/ec2-user/rust-tester/ccxt/python/ccxt/async_support
['python/ccxt/test/test_async.py', 'bybit', '--privateOnly']
bybit using proxy ``
EXCHANGE: bybit
Testing fetch_orders:BTC/USDT
bybit BTC/USDT fetchOrders() failed with: bybit fetchOrders() does not support spot markets, use exchange.fetch_open_orders() and exchange.fetchClosedOrders() instead
Testing fetch_open_orders:BTC/USDT
bybit BTC/USDT fetched 0 open orders
Testing fetch_closed_orders:BTC/USDT
bybit BTC/USDT fetched 0 closed orders
Testing fetch_transactions:WAVES
bybit WAVES fetchTransactions() is not supported
Testing fetch_balance
bybit fetched balance
Testing fetch_positions:BTC/USDT
bybit fetching positions...
bybit fetched 2 positions
bybit BTC/USDT fetching positions...
bybit BTC/USDT fetched 0 positions (explain @ run-tests.js:212)
FAIL ["bybit"] (run-tests.js:290)
All done, 1 failed (run-tests.js:295)


```

File: js/bybit.js [hunk 1]
```diff
@@ -4515,29 +4515,19 @@ module.exports = class bybit extends Exchange {
...
+            // 'orderId': 'string'
+            // 'orderLinkId': 'string', // unique client order id, max 36 characters
+            // 'orderStatus': 'Created,New'
+            // 'orderFilter': 'StopOrder', // 'Order' or 'StopOrder'
+            // 'limit': 20, // Limit for data size per page. [1, 50]. Default: 20
+            // 'cursor': 'string', // used for pagination
         };
         if (symbol !== undefined) {
             market = this.market (symbol);
-            settle = market['settle'];
```
Comment (carlosmiei) [inline js/bybit.js:4534]: Interestingly, this method was working on my side even with the settleCoin, but ofc we should fix it

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p bybit fetchDerivativesOrders "LTC/USDT:USDT" None 1 --sandbox
Python v3.10.9
CCXT v2.7.78
bybit.fetchDerivativesOrders(LTC/USDT:USDT,None,1)
[{'amount': 0.5,
  'average': 54.48,
  'clientOrderId': None,
  'cost': 27.24,
  'datetime': '2022-10-06T13:49:23.140Z',
  'fee': {'cost': 0.016344, 'currency': 'USDT'},
  'fees': [{'cost': 0.016344, 'currency': 'USDT'}],
  'filled': 0.5,
  'id': '98eb8439-1838-4079-bf48-9bf9c9d33847',
  'info': {'blockTradeId': '',
           'cancelType': 'UNKNOWN',
           'closeOnTrigger': True,
           'createdTime': '1665064163140',
           'cumExecFee': '0.016344',
           'cumExecQty': '0.5',
           'cumExecValue': '27.24',
           'iv': '',
           'lastPriceOnCreated': '0.00',
           'leavesQty': '0.0',
           'leavesValue': '0',
           'orderId': '98eb8439-1838-4079-bf48-9bf9c9d33847',
           'orderLinkId': '',
           'orderStatus': 'Filled',
           'orderType': 'Market',
           'positionIdx': '1',
           'price': '51.83',
           'qty': '0.5',
           'reduceOnly': True,
           'rejectReason': 'EC_NoError',
           'side': 'Sell',
           'slTriggerBy': 'UNKNOWN',
           'stopLoss': '0.00',
           'stopOrderType': 'UNKNOWN',
           'symbol': 'LTCUSDT',
           'takeProfit': '0.00',
           'timeInForce': 'ImmediateOrCancel',
           'tpTriggerBy': 'UNKNOWN',
           'triggerBy': 'UNKNOWN',
           'triggerDirection': '0',
           'triggerPrice': '0.00',
           'updatedTime': '1665064163146'},
  'lastTradeTimestamp': None,
  'postOnly': False,
  'price': 51.83,
  'reduceOnly': None,
  'remaining': 0.0,
  'side': 'sell',
  'status': 'closed',
  'stopPrice': None,
  'symbol': 'LTC/USDT:USDT',
  'timeInForce': 'IOC',
  'timestamp': 1665064163140,
  'trades': [],
  'triggerPrice': None,
  'type': 'market'}]
```

**Review by carlosmiei — APPROVED** [review]
