### PR TITLE
base - `safeTrade` ->cost to number

### LINKED ISSUE #14247: gateio fetch_my_trades fees "cost" has wrong type
- OS: linux
- Programming Language version: python
- CCXT version:1.90.27

```python
import ccxt
ct = ccxt.gateio({'options': {'defaultType': 'swap'}})
_ = ct.loadMarkets()

trades = ct.fetch_my_trades('APE/USDT:USDT')
# Obviously assumes that trades exist
print(trades[0])
```

```
[{'amount': 13.0,
  'cost': 47.7087,
  'datetime': '2022-06-17T20:54:37.108Z',
  'fee': None,
  'fees': [{'cost': '0.019560567', 'currency': None}],
  'id': '8799416',
  'info': {'contract': 'APE_USDT',
           'create_time': '1655499277.1085',
           'fee': '0.019560567',
           'id': '8799416',
           'order_id': '173423995062',
           'point_fee': '0',
           'price': '3.6699',
           'role': 'taker',
           'size': '13',
           'text': 'api'},
  'order': 'xxxxx',
  'price': 3.6699,
  'side': 'buy',
  'symbol': 'APE/USDT:USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1655499277108,
  'type': None},
```

in the fees response (which is great that this was added!) `'fees': [{'cost': '0.019560567', 'currency': None}],`  - 'cost' is returned as string.

I suspect the problem comes form this area
https://github.com/ccxt/ccxt/blob/38dfe65b39e77b731dba05fe80a92d8902ddf128/js/gate.js#L2678-L2679
- which i suspect should be "safeNumber" - to return this as a number OR a string, depending on global settings.

I guess it's not properly converted "back" to number in `safe_trade` as it's already parsed / assigned.

What's odd here though is that (at least in the python version) - fees seem to be converted / parsed twice (`shouldParseFees` is True in this case - as `parseFee` is None) - but are then not used (`parseFees` is False).
https://github.com/ccxt/ccxt/blob/38dfe65b39e77b731dba05fe80a92d8902ddf128/python/ccxt/base/exchange.py#L2172-L2186

This is not really an issue - it may be something that can be optimized in the future.

### LINKED ISSUE #14264: safeTrade eventually parses fees again while then ignoring the outcome
- OS: linux
- Programming Language version: python
- CCXT version:1.90.27

Pulled from #14247 to be treated as separate issue as requested.

I guess it's not properly converted "back" to number in `safe_trade` as it's already parsed / assigned.

(at least in the python version) - fees seem to be converted / parsed twice (`shouldParseFees` is True in this case - as `parseFee` is None) - but are then not used (`parseFees` is False).
https://github.com/ccxt/ccxt/blob/38dfe65b39e77b731dba05fe80a92d8902ddf128/python/ccxt/base/exchange.py#L2172-L2186

This is not really an issue - it may however be something that can be optimized in the future.

### PR DESCRIPTION
**Pull request by ttodua**
fixes #14247  fixes #14264

### CODE REVIEW

File: js/base/Exchange.js [hunk 1]
```diff
@@ -1304,6 +1301,10 @@ module.exports = class Exchange {
                 trade['fee'] = tradeFee;
             }
         }
+        const tradeFees = this.safeValue (trade, 'fees', []);
+        for (let j = 0; j < tradeFees.length; j++) {
+            trade['fees'][j]['cost'] = this.safeNumber (trade['fees'][j], 'cost');
+        }
```
Comment (xmatthias) [inline js/base/Exchange.js:1307]: i'm really not trying to be pesky - but i think if you fix it in exchange.js - you'll need to replicate that for Python and php - as exchange.js will not be transpiled.

Comment (kroitor) [reply js/base/Exchange.js:1307]: > i'm really not trying to be pesky - but i think if you fix it in exchange.js - you'll need to replicate that for Python and php - as exchange.js will not be transpiled.

@xmatthias not anymore, base js file is now partially transpiled to py/php (actually, mostly transpiled) since recently )

Comment (xmatthias) [reply js/base/Exchange.js:1307]: oh that's nice :+1:

Comment (ttodua) [reply js/base/Exchange.js:1307]: > i'm really not trying to be pesky - but i think if you fix it in exchange.js - you'll need to replicate that for Python and php - as exchange.js will not be transpiled.

Nope, your notes are more then welcome. Just as a good news, we had departed the transpilable codes inside base exchange files, from here and down below as you see: https://github.com/ccxt/ccxt/commit/e98328d46f2b7df6539f22f762dbe744ba317742#diff-306362d145a5405ce27b41bc5613c5371dcbd0857a90cfc7be651bf584db6656R758

**Comment by carlosmiei** [comment]
@ttodua looks good to me and seems to be working fine, but I would give the last word to @frosty00, just to make sure we're not breaking edge cases 

```
p gateio fetchMyTrades
Python v3.9.7
CCXT v1.90.35
gateio.fetchMyTrades()
[{'amount': 0.1,
  'cost': 5.96,
  'datetime': '2022-08-03T16:34:17.590Z',
  'fee': {'cost': 0.0002, 'currency': 'LTC'},
  'fees': [{'cost': 0.0002, 'currency': 'LTC'}],
  'id': '3927253087',
  'info': {'amount': '0.1',
           'create_time': '1659544457',
           'create_time_ms': '1659544457590.991000',
           'currency_pair': 'LTC_USDT',
           'fee': '0.0002',
           'fee_currency': 'LTC',
           'gt_fee': '0',
           'id': '3927253087',
           'order_id': '187273757328',
           'point_fee': '0',
           'price': '59.6',
           'role': 'taker',
           'side': 'buy'},
  'order': '187273757328',
  'price': 59.6,
  'side': 'buy',
  'symbol': 'LTC/USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1659544457590,
  'type': None}]
```

**Comment by ttodua** [comment]
related #14264

**Comment by ttodua** [comment]
@carlosmiei this PR seems ready, irrelevant failures (other PR is needed to fix those things)
