### PR TITLE
lbank2 - network related fixes

### LINKED ISSUE #14984: lbank2 fetch_deposit_address not have network or chain params

### PR DESCRIPTION
**Pull request by ttodua**
fix #14984

### CODE REVIEW

File: js/lbank2.js [hunk 1]
```diff
@@ -258,6 +258,9 @@ module.exports = class lbank2 extends Exchange {
                     'btctron': 'BTCTRON',
                     'xrp': 'XRP',
                 },
+                'defaultNetworks': {
+                    'USDT': 'TRC20',
```
Comment (carlosmiei) [inline js/lbank2.js:262]: we usually default to `ERC20` no ?

Comment (ttodua) [reply js/lbank2.js:262]: > we usually default to `ERC20` no ?
In the past, when I asked this question to Igor, he said that ETH was redundant for USDT. To remind, we have two things "defaultNetwork" and "defaultNetworks"(plural). ETH might be candidate of "defaultNetwork" (so, all coins, which are not specifically declared in "defaultNetworks", would use from "defaultNetwork"), however, for USDT, most ppl use TRC20.
Also, I think we might make `networkCode` as mandatory argument, to avoid any such "defaults" at all (which I think will be much better).

**Comment by hosseinab** [comment]
@kroitor @frosty00 @carlosmiei 
this merge not approved

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]
