### PR TITLE
Huobi :: fix fetchBalance

### LINKED ISSUE #12670: Huobi Futures bugs detected
Hi, very greate job on this library, is not easy to manage all. (sorry for my english)
I'm using it for huobi and on spot trading is good, but for the features I'm not find it easy for those reasons:

- the fetchAccount method is calling only the spot account and not any futures
- in some methods mapping from isolated or cross management are missing
- in other there are linearSwap missing despite the fact that the methods to call are implemented

I get to knew that were missing after looking at these code:  https://github.com/ccxt/ccxt/blob/master/js/huobi.js

and going verbose mode otherwise I couldn't get how everything wasn't returning the right results.

### PR DESCRIPTION
**Pull request by carlosmiei**
Fixes #12670

- Added the isolated margin endpoint and fixed the balance parsing

Cross output
```
{
    "info":{
       "status":"ok",
       "data":[
          (...)
       ],
       "ts":"1649415601244"
    },
    "USDT":{
       "free":20.920440895,
       "used":2,
       "total":22.920440895
    },
    "free":{
       "USDT":20.920440895
    },
    "used":{
       "USDT":2
    },
    "total":{
       "USDT":22.920440895
    }
 }

```
Isolated output
```
{
   "info":{
      "status":"ok",
        "data": [
         {
            "symbol":"GMT",
            "margin_balance":"0",
            "margin_position":"0",
            "margin_frozen":"0",
            "margin_available":"0",
            "profit_real":"0",
            "profit_unreal":"0",
            "risk_rate":null,
            "withdraw_available":"0",
            "liquidation_price":null,
            "lever_rate":"5",
            "adjust_factor":"0.100000000000000000",
            "margin_static":"0",
            "contract_code":"GMT-USDT",
            "margin_asset":"USDT",
            "margin_mode":"isolated",
            "margin_account":"GMT-USDT",
            "trade_partition":"USDT",
            "position_mode":"dual_side"
         }
         (...)
      ],
      "ts":"1649415422720"
   },
   "BTC/USDT:USDT":{
      "USDT":{
         "free":0,
         "used":0,
         "total":0
      },
      "free":{
         "USDT":0
      },
      "used":{
         "USDT":0
      },
      "total":{
         "USDT":0
      }
   }
   (...)
}
```

### CODE REVIEW

File: js/huobi.js [hunk 1]
```diff
@@ -2570,10 +2574,8 @@ module.exports = class huobi extends Exchange {
                 const code = this.safeCurrencyCode (currencyId);
                 result[code] = account;
             } else if (isolated) {
-                const fieldName = future ? 'futures_contract_detail' : 'contract_detail';
```
Comment (carlosmiei) [inline js/huobi.js:2573]: These fields are not isolated margin related but cross. In this case, I don't really find them useful so they're not being used even in cross balance parsing
image
