### PR TITLE
fix(bitmex): market states & expiry for perps

### LINKED ISSUE #25784: bitmex market expiry not parsed
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.4.74

### Description

For bitmex markets the expiry date is not parsed from the info and the market status is still active while it has expired a few hours ago.

### Code

```
{'active': True,
 'base': 'USUAL',
 'baseId': 'USUAL',
 'contract': True,
 'contractSize': 1.0,
 'created': 1734580800000,
 'expiry': None,
 'expiryDatetime': None,
 'future': False,
 'id': 'USUALUSDT',
 'index': None,
 'info': {'askPrice': '0.1343',
          'bidPrice': '0.129',
          'capped': False,
          'deleverage': True,
          'expiry': '2025-04-24T12:00:00.000Z',
          'fairBasis': '0',
  },
}
```

### PR DESCRIPTION
**Pull request by ttodua**
fix #25784

### CODE REVIEW

File: ts/src/bitmex.ts [hunk 1]
```diff
@@ -753,9 +753,9 @@ export default class bitmex extends Exchange {
                 const multiplierString = Precise.stringAbs (this.safeString (market, 'multiplier'));
                 contractSize = this.parseNumber (multiplierString);
             }
-            if (future) {
-                expiryDatetime = this.safeString (market, 'expiry');
-                expiry = this.parse8601 (expiryDatetime);
+            expiryDatetime = this.safeString (market, 'expiry');
+            expiry = this.parse8601 (expiryDatetime);
+            if (expiry !== undefined) {
```
Comment (ttodua) [inline ts/src/bitmex.ts:758]: only moved out of `if` clause
