### PR TITLE
gate - fix fetchMytrades null fees

### LINKED ISSUE #14515: gate.io parseTrade fees
I have some questions about `fee/fees` on gate.io.
In code of  `parseTrade` we have:
```
 'fee': undefined,
 'fees': fees,
```

In case of zero fees:
```
{
    info: {
      id: '3890811349',
      create_time: '1659011681',
      create_time_ms: '1659011681543.849900',
      currency_pair: 'BTC_USDT',
      side: 'sell',
      role: 'maker',
      amount: '0.0018',
      price: '22892.76',
      order_id: '184929604262',
      fee: '0',
      fee_currency: 'USDT',
      point_fee: '0',
      gt_fee: '0'
    },
    id: '3890811349',
    timestamp: 1659011681543,
    datetime: '2022-07-28T12:34:41.543Z',
    symbol: 'BTC/USDT',
    order: '184929604262',
    type: undefined,
    side: 'sell',
    takerOrMaker: 'maker',
    price: 22892.76,
    amount: 0.0018,
    cost: 41.206968,
    fee: undefined,
    fees: []
  }
```

`fee` is `undefined` in all cases. Is it normal? 
Because there is no fee in my case, is it normal that `fees` is an empty array? Or it should be like `[{ 'cost': 0, 'currency': 'USDT'}]`?

### PR DESCRIPTION
**Pull request by ttodua**
fix #14515

related PR, please review that too: https://github.com/ccxt/ccxt/pull/14268

### CODE REVIEW

File: js/gate.js [hunk 1]
```diff
@@ -2680,7 +2680,7 @@ module.exports = class gate extends Exchange {
         const gtFee = this.safeString (trade, 'gt_fee');
         const pointFee = this.safeString (trade, 'point_fee');
```
Comment (carlosmiei) [inline js/gate.js:2681]: @ttodua to avoid having to remember to check against every operation (costly since it's a string comparison), why not use `omitZero` upon parsing the value?

```Javascript
const pointFee = this.omitZero (this.safeString (trade, 'point_fee'));
````

Comment (ttodua) [reply js/gate.js:2681]: can you please re-review the code? i think you are commenting on old code (currently, we are removing that comparison at all).

Comment (carlosmiei) [reply js/gate.js:2681]: @ttodua You're right, sorry my bad

**Comment by ndubel** [comment]
is it normal, that now in `cost` in `fees` is `string`?
```
fee: undefined,
fees: [
    { cost: '0', currency: 'ETH' },
    { cost: '0', currency: 'GT' },
    { cost: '0', currency: 'POINT' }
  ]
```

**Comment by carlosmiei** [comment]
Hi @ndubel, it isn't, fees should be returned as numbers; we will patch it soon, thanks for letting us know!

**Comment by ttodua** [comment]
@carlosmiei @ndubel this is the PR that should fix the 'string' issue: https://github.com/ccxt/ccxt/pull/14268

**Comment by ndubel** [comment]
hope @kroitor will merge it soon
