### PR TITLE
gateio.fetchMarkets margin markets fix #12020

### LINKED ISSUE #12020: gateio precision is None when 'options': { 'defaultType': 'margin' }
- OS: win10
- Programming Language version: 3.7
- CCXT version: 1.73.41

```
gateio_key = ''
gateio_secret = ''
exchange_class = getattr(ccxt, 'gateio')
cex_client = exchange_class({
                    'apiKey': gateio_key,
                    'secret': gateio_secret,
                  'options': { 'defaultType': 'margin' }
                })
symbol='METIS/USDT'
amount=1.535641686865297
price=102.83248
r = cex_client.create_limit_buy_order(symbol, amount, price,
                                                      params={'account': 'cross_margin',
                                                              'auto_borrow': True,
                                                              })
```

```
Traceback (most recent call last):
  File "C:\Users\a\Documents\working_dir\crypto_trading_scripts\trading_send_order_gate.py", line 21, in <module>
    'auto_borrow': True,
  File "c:\users\a\appdata\local\programs\python\python37\lib\site-packages\ccxt\base\exchange.py", line 2196, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "c:\users\a\appdata\local\programs\python\python37\lib\site-packages\ccxt\gateio.py", line 2163, in create_order
    'amount': self.amount_to_precision(symbol, amount),
  File "c:\users\a\appdata\local\programs\python\python37\lib\site-packages\ccxt\base\exchange.py", line 1426, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
  File "c:\users\a\appdata\local\programs\python\python37\lib\site-packages\ccxt\base\decimal_to_precision.py", line 38, in decimal_to_precision
    assert precision is not None
AssertionError
```

### PR DESCRIPTION
**Pull request by samgermain**
Fixes #12020 

```
2022-02-23T06:51:54.567Z
Node.js: v14.17.0
CCXT v1.73.85
gateio.fetchMarkets ()
371 ms
           id |                symbol |             base | quote | settle |   baseId | quoteId | settleId |   type | spot | margin |  swap | future | option | active | contract | linear | inverse | taker | maker | contractSize | expiry | expiryDatetime | strike | optionType |                         precision |                                                                    limits
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     ERN_USDT |              ERN/USDT |              ERN |  USDT |        |      ERN |    USDT |          | margin | true |   true | false |  false |  false |   true |    false |        |         | 0.002 | 0.002 |              |        |                |        |            |    {"amount":0.001,"price":0.001} |  {"leverage":{"min":1,"max":3},"amount":{},"price":{},"cost":{"min":100}}
...
     ZEC_USDT |              ZEC/USDT |              ZEC |  USDT |        |      ZEC |    USDT |          | margin | true |   true | false |  false |  false |   true |    false |        |         | 0.002 | 0.002 |              |        |                |        |            |    {"amount":0.0001,"price":0.01} |  {"leverage":{"min":1,"max":3},"amount":{},"price":{},"cost":{"min":100}}
   JASMY_USDT |            JASMY/USDT |            JASMY |  USDT |        |    JASMY |    USDT |          | margin | true |   true | false |  false |  false |   true |    false |        |         | 0.002 | 0.002 |              |        |                |        |            | {"amount":0.001,"price":0.000001} |  {"leverage":{"min":1,"max":3},"amount":{},"price":{},"cost":{"min":100}}
403 objects
```

### CODE REVIEW

File: js/gateio.js [hunk 1]
```diff
@@ -761,6 +761,15 @@ module.exports = class gateio extends Exchange {
...
             response = await this[method] (query);
+            const spotMarkets = {};
+            if (margin) {
+                const spotMarketsArray = await this.publicSpotGetCurrencyPairs (query);
+                for (let i = 0; i < spotMarketsArray.length; i++) {
+                    const spotMarket = spotMarketsArray[i];
+                    const spotMarketId = this.safeString (spotMarket, 'id');
+                    spotMarkets[spotMarketId] = spotMarket;
+                }
+            }
```
Comment (kroitor) [inline js/gateio.js:772]: Let's rewrite lines 764-772 in a shorter way:

```JavaScript
let spotMarkets = {}
if (margin) {
    const spotMarketsResponse = await this.publicSpotGetCurrencyPairs (query);
    spotMarkets = this.indexBy (spotMarketsResponse, 'id');
}
```
