### PR TITLE
base & binance - fix currency_to_precision

### LINKED ISSUE #26682: currency_to_precision for binance API works not as expected
### Operating System

mac os

### Programming Language

Python

### CCXT Version

Latest

### Description

**Issue**:
When I call currency_to_precision('ASR', 32.2, 'CHZ2'), it should return 32, but instead it returns 32.2.

**Details**:

The currency_to_precision function in the Binance API ignores the networkCode argument.

Precision for the CHZ2 network is 1.0, so the function should return 32.

**Expected Behavior for Binance API:**
currency_to_precision('ASR', 32.2, 'CHZ2') → 32

### PR DESCRIPTION
**Pull request by ttodua**
fix #26682

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua can you elaborate a bit more on what is this PR fixing? Also if needed we can add some tests to validate the fix

**Comment by ttodua** [comment]
> @ttodua can you elaborate ..

I've added in top-post.

File: ts/src/base/Exchange.ts [hunk 1]
```diff
@@ -3723,10 +3723,18 @@ export default class Exchange {
             precision = this.safeValue (networkItem, 'precision', precision);
         }
         if (precision === undefined) {
-            return fee;
+            return this.forceString (fee);
```
Comment (ttodua) [inline ts/src/base/Exchange.ts:3726]: this change is in base. it affects **only few exchanegs** where currency precisions are not available from `fetchCurrencies`.
for those exchanges, we need to return `string` as in `else` clause through `decimalToPrecision` we return `string`. 
so, currently we have a bug as in few exchanges we are returning `numeric` instead of `string`

File: ts/src/base/Exchange.ts [hunk 2]
```diff
@@ -3723,10 +3723,18 @@ export default class Exchange {
...
         } else {
-            return this.decimalToPrecision (fee, ROUND, precision, this.precisionMode, this.paddingMode);
+            const roundingMode = this.safeValue (this.options, 'currencyToPrecisionRoundingMode', ROUND);
```
Comment (ttodua) [inline ts/src/base/Exchange.ts:3728]: this would support binance and other similar exchanges

File: ts/src/binance.ts [hunk 3]
```diff
@@ -2506,15 +2507,6 @@ export default class binance extends Exchange {
         return this.decimalToPrecision (cost, TRUNCATE, this.markets[symbol]['precision']['quote'], this.precisionMode, this.paddingMode);
     }
 
-    currencyToPrecision (code, fee, networkCode = undefined) {
```
Comment (ttodua) [inline ts/src/binance.ts:2756]: we remove from here and use base's currencyToPrecision, which is more accurate

**Comment by carlosmiei** [comment]
@ttodua can you please add a static tests that validates this fix?

**Comment by ttodua** [comment]
> @ttodua can you please add a static tests that validates this fix?

added 👍
