### PR TITLE
[Luno] Fixed balance bug.

### LINKED ISSUE #959: [Luno] Free and Balance are swapped
[Luno] Free and Balance are swapped

- OS: Linux
- Programming Language: Node (JS)
- CCXT version: ccdfefd84636b4f3a2312f1a325195e803881905
- Exchange: Luno
- Method: FetchBalance()

I am currently testing a fix for this and I will submit it as soon as I am satisfied. I'm not including code because it is a very simple problem and any code that would reveal the problem would expose personal information.

### PR DESCRIPTION
**Pull request by WilhelmErasmus**
Fixes #959 

Signed-off-by: Wilhelm Erasmus <wilhelm.erasmus@burtronix.com>

### CODE REVIEW

File: js/luno.js [hunk 1]
```diff
@@ -112,11 +112,11 @@ module.exports = class luno extends Exchange {
...
             let unconfirmed = parseFloat (balance['unconfirmed']);
             let account = {
-                'free': parseFloat (balance['balance']),
+                'free': 0.0,
                 'used': this.sum (reserved, unconfirmed),
-                'total': 0.0,
+                'total': parseFloat (balance['balance']),
             };
-            account['total'] = this.sum (account['free'], account['used']);
+            account['free'] = account['free'] - account['used'];
```
Comment (kroitor) [inline js/luno.js]: This line looks like a typo, shouldn't it be 
```JavaScript
account['free'] = account['total'] - account['used']
``` 
?

Comment (WilhelmErasmus) [reply js/luno.js]: Yes. Sorry I will fix it now.

Comment (kroitor) [reply js/luno.js]: Thanks!
