### PR TITLE
huobi - watchOrderBook

### LINKED ISSUE #15641: Huobi future swap watchOrderBook maintaining the orderbook in an incorrect way
- OS: MacOS 11.5.1
- Programming Language version: nodejs 
- CCXT version: 2.1.56 v16.9.0
- Exchange: huobi future, huobi swap
- Method: watchOrderBook

# Question

Huobi future swap watchOrderBook maintaining the orderbook in an incorrect way, local orderbook always is old data!

**Huobi spot watchOrderBook work well.**

# Solution

Subscribing huobi future, swap orderbook, when got first message(huobi snapshot orderbook), we should using the to maintain local orderbook, not fetchOrderBook required.

# Details

# 0. Example Code

```
import ccxt from 'ccxt'
import HttpsProxyAgent from 'https-proxy-agent';

// const httpsAgent = new HttpsProxyAgent(process.env.HTTP_PROXY);
const httpsAgent = null;

const exchange = new ccxt.pro.huobi({
    httpsAgent: httpsAgent,
    options: {
        'ws': {
            'options': {agent: httpsAgent},
        },
    },
});

while (true) {
    exchange.verbose = true;
    try {
        const orderbook = await exchange.watchOrderBook('BTC/USDT:USDT-221118');

        console.info(`logging orderbook=${JSON.stringify(orderbook)}`);

    } catch (error) {
        console.error(error.message);
    }
}
```

Some import output as follow:

1. [debug-full.log](https://github.com/ccxt/ccxt/files/9986714/debug-full.log)
2. [debug-simple.log](https://github.com/ccxt/ccxt/files/9986715/debug-simple.log)

# 1. ws message

```txt
2022-11-11T05:20:44.271Z connecting to wss://api.hbdm.com/linear-swap-ws
2022-11-11T05:20:44.897Z onUpgrade
2022-11-11T05:20:44.899Z onOpen
2022-11-11T05:20:44.900Z sending {
  sub: 'market.BTC-USDT-221118.depth.size_150.high_freq',
  id: '1',
  data_type: 'incremental'
}
2022-11-11T05:20:45.196Z onMessage {
  ch: 'market.BTC-USDT-221118.depth.size_150.high_freq',
  tick: {
    asks: [
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array],
      [Array], [Array], [Array]
    ],
    bids: [
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array]
    ],
    ch: 'market.BTC-USDT-221118.depth.size_150.high_freq',
    event: 'snapshot',
    id: 1662463050,
    mrid: 1662463050,
    ts: 1668144045036,
    version: 6936227
  },
  ts: 1668144045036
}
2022-11-11T05:20:45.199Z onMessage {
  id: '1',
  subbed: 'market.BTC-USDT-221118.depth.size_150.high_freq',
  ts: 1668144045104,
  status: 'ok'
}
```

1. ws send `sub`
    1. message is `{"sub":"market.BTC-USDT-221118.depth.size_150.high_freq","id":"1","data_type":"incremental"}`
2. ws receive `snapshot` event 
    1. call `handleSubject`
    2. call `handleOrderBook` and save snapshot data into **cache** by  [orderbook.cache.push (message);](https://github.com/ccxt/ccxt/blob/2.1.56/js/pro/huobi.js#L591), **But not store into this.orderbooks**. (**WE LOSS `snapshot`**)
3. ws receive `subbed`
    1. message is `{"id":"1","subbed":"market.BTC-USDT-221118.depth.size_150.high_freq","ts":1668144045104,"status":"ok"}`
    2. call `handleSubscriptionStatus`
    3. call `handleOrderBookSubscription` and **delete local orderbook** [delete this.orderbooks[symbol];](https://github.com/ccxt/ccxt/blob/2.1.56/js/pro/huobi.js#L602)
    4. call `fetchOrderBookSnapshot` using fetchOrderBook to get orderbook [const snapshot = await this.fetchOrderBook (symbol, limit);](https://github.com/ccxt/ccxt/blob/2.1.56/js/pro/huobi.js#L420) (**NOT REQUIRED!**)

Huobi official docs tell us, using the `snapshot` and `update` event to maintain local orderbook.

1. https://huobiapi.github.io/docs/dm/v1/en/#subscribe-incremental-market-depth-data
2. https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#subscribe-incremental-market-depth-data
3. https://huobiapi.github.io/docs/usdt_swap/v1/en/#general-subscribe-incremental-market-depth-data

> - when `data_type` is `incremental`,`snapshot` data wil be pushed for the **first time**. When re-connection occurs, `snapshort` data will be pushed for the first time.
> - `version`: auto increment in single websocket connection. `version` may be different among several websocket subscription connections.
> - orderbook will be pushed if orderbook is updated whenever `incremental` or `snapshot`.
> - orderbook event will be checked every 30ms. If there is no orderbook event, you will not receive any orderbook data.
> - you HAVE TO maintain local orderbook data,such as updating your local orderbook bids and asks data.

### PR DESCRIPTION
**Pull request by pcriadoperez**
- fixes #15641 
- add docs links
- update allowed limits

### CODE REVIEW

**Comment by pcriadoperez** [comment]
Build failing due to ftxus tests. I'm assuming we are going to unlist ftx?

**Comment by carlosmiei** [comment]
@pcriadoperez yes, as a quick fix will disable it from tests

File: js/pro/huobi.js [hunk 1]
```diff
@@ -512,17 +475,56 @@ module.exports = class huobi extends huobiRest {
...
+        const seqNum = this.safeInteger2 (tick, 'seqNum', 'version');
         const prevSeqNum = this.safeInteger (tick, 'prevSeqNum');
+        const event = this.safeString (tick, 'event');
+        const timestamp = this.safeInteger (message, 'ts');
+        if (event === 'snapshot') {
+            const snapshot = this.parseOrderBook (tick, symbol, timestamp);
+            orderbook.reset (snapshot);
+            orderbook['nonce'] = seqNum;
+        }
+        if (event === 'update') {
```
Comment (carlosmiei) [inline js/pro/huobi.js:517]: @pcriadoperez since now we get everything from the WS channel, I don't think we need these verifications

File: js/pro/huobi.js [hunk 2]
```diff
@@ -512,17 +475,56 @@ module.exports = class huobi extends huobiRest {
...
+            if (seqNum !== orderbook['nonce'] + 1) {
+                throw new ExchangeError (this.id + ' invalid nonce in orderbook update message for ' + symbol);
+            }
+        }
         if ((prevSeqNum === undefined || prevSeqNum <= orderbook['nonce']) && (seqNum > orderbook['nonce'])) {
```
Comment (carlosmiei) [inline js/pro/huobi.js:522]: this if condition can be removed as well I think

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
Python v3.9.7
CCXT v2.1.72
huobi.watchOrderBook(BTC/USDT:USDT)
{'asks': [[16623.1, 2562.0], [16623.7, 1100.0], [16623.8, 949.0], [16623.9, 1.0], [16624.0, 46.0], [16625.0, 210.0], [16625.1, 1101.0], [16625.2, 342.0], [16626.0, 342.0], [16626.5, 1101.0], [16626.7, 1101.0], [16626.8, 443.0], [16626.9, 6.0], [16627.0, 18.0], [16627.1, 16275.0], [16627.2, 1101.0], [16627.7, 342.0], [16628.2, 33.0], [16628.3, 1170.0], [16628.5, 1442.0], [16629.3, 24409.0], [16629.4, 187.0], [16629.6, 77.0], [16629.7, 286.0], [16630.1, 91.0], [16630.5, 286.0], [16631.0, 284.0], [16631.8, 284.0], [16632.2, 376.0], [16632.6, 5549.0], [16632.7, 399.0], [16632.8, 16.0], [16633.5, 274.0], [16633.8, 10593.0], [16634.3, 283.0], [16634.7, 86.0], [16634.8, 245.0], [16635.2, 274.0], [16635.8, 235.0], [16636.0, 7.0], [16636.3, 83.0], [16636.6, 235.0], [16637.2, 83.0], [16637.5, 235.0], [16638.0, 85.0], [16638.1, 1.0], [16638.3, 242.0], [16638.8, 85.0], [16639.1, 242.0], [16639.2, 90.0], [16640.0, 252.0], [16640.1, 89.0], [16640.6, 53.0], [16640.8, 252.0], [16640.9, 52.0], [16641.0, 144.0], [16641.6, 306.0], [16641.8, 62.0], [16642.0, 2491.0], [16642.1, 180.0], [16642.4, 362.0], [16642.6, 43.0], [16642.9, 201.0], [16643.0, 73.0], [16643.3, 56.0], [16643.5, 276.0], [16644.0, 180.0], [16644.3, 276.0], [16644.8, 201.0], [16645.0, 48.0], [16645.1, 82.0], [16645.3, 113.0], [16645.5, 81.0], [16645.6, 134.0], [16645.7, 70.0], [16645.9, 55.0], [16646.0, 30.0], [16646.1, 198.0], [16646.5, 200.0], [16646.9, 63.0], [16647.0, 21.0], [16647.4, 4921.0], [16648.0, 120.0], [16648.1, 118.0], [16648.2, 29.0], [16649.2, 17.0], [16649.9, 11.0], [16650.1, 55.0], [16650.6, 54.0], [16650.9, 25.0], [16651.6, 10.0], [16652.0, 91.0], [16652.3, 90.0], [16652.5, 58.0], [16652.8, 43.0], [16653.5, 10.0], [16655.2, 90.0], [16655.3, 72.0], [16656.8, 77.0], [16657.0, 113.0], [16659.3, 9997.0], [16660.3, 119.0], [16661.9, 123.0], [16662.2, 107.0], [16662.5, 1.0], [16662.6, 110.0], [16668.0, 271.0], [16670.7, 161.0], [16671.4, 156.0], [16672.3, 2579.0], [16672.5, 185.0], [16673.3, 202.0], [16673.6, 75.0], [16674.7, 2750.0], [16676.7, 13443.0], [16680.0, 1.0], [16683.5, 201.0], [16685.2, 1.0], [16687.8, 236.0], [16688.5, 2677.0], [16690.0, 2.0], [16690.9, 456.0], [16691.9, 4.0], [16692.1, 2.0], [16696.4, 17218.0], [16697.5, 1.0], [16700.0, 30735.0], [16700.8, 261.0], [16703.8, 7.0], [16710.0, 53.0], [16715.0, 93.0], [16717.0, 92.0], [16720.0, 7.0], [16725.0, 2.0], [16729.3, 1.0], [16732.0, 271.0], [16732.5, 1.0], [16733.3, 19914.0], [16740.0, 179.0], [16743.6, 381.0], [16745.0, 92.0], [16748.5, 2.0], [16750.0, 13.0], [16757.0, 2.0], [16759.4, 12317.0], [16760.0, 1602.0], [16762.9, 5464.0], [16764.0, 271.0], [16766.6, 14943.0], [16767.5, 1.0]],
 'bids': [[16623.0, 2896.0], [16622.9, 1100.0], [16622.8, 141.0], [16622.7, 77.0], [16622.6, 14.0], [16622.5, 1.0], [16621.4, 1100.0], [16621.3, 133.0], [16621.2, 1100.0], [16621.1, 1.0], [16621.0, 1101.0], [16620.9, 406.0], [16620.8, 1.0], [16620.2, 123.0], [16620.1, 337.0], [16620.0, 6.0], [16619.4, 78.0], [16619.3, 460.0], [16618.4, 337.0], [16618.1, 16504.0], [16617.8, 1101.0], [16617.7, 2492.0], [16617.6, 337.0], [16617.4, 1.0], [16616.9, 205.0], [16616.8, 73.0], [16616.7, 69.0], [16616.3, 4089.0], [16616.1, 1101.0], [16615.9, 284.0], [16615.6, 91.0], [16615.4, 286.0], [16615.0, 259.0], [16614.9, 1.0], [16614.6, 286.0], [16614.2, 1.0], [16613.8, 332.0], [16613.4, 90.0], [16613.0, 332.0], [16612.9, 2767.0], [16612.5, 332.0], [16612.1, 18.0], [16611.8, 173.0], [16611.7, 235.0], [16611.4, 4960.0], [16610.9, 336.0], [16610.7, 180.0], [16610.5, 62.0], [16610.3, 43.0], [16610.1, 460.0], [16610.0, 1.0], [16608.3, 53.0], [16608.2, 10053.0], [16607.3, 2763.0], [16607.1, 55.0], [16607.0, 55.0], [16606.7, 107.0], [16606.4, 48.0], [16606.0, 63.0], [16605.4, 90.0], [16605.2, 53.0], [16605.1, 19.0], [16604.9, 65.0], [16604.8, 69.0], [16604.5, 56.0], [16604.3, 64.0], [16604.2, 17.0], [16604.1, 1.0], [16604.0, 331.0], [16603.7, 20.0], [16602.8, 108.0], [16602.4, 92.0], [16602.1, 65.0], [16602.0, 249.0], [16601.0, 80.0], [16600.5, 81.0], [16600.0, 396.0], [16599.3, 138.0], [16598.4, 70.0], [16597.0, 3162.0], [16595.6, 6707.0], [16595.5, 2.0], [16594.7, 1106.0], [16594.6, 240.0], [16594.3, 71.0], [16592.6, 179.0], [16592.5, 1.0], [16590.6, 1248.0], [16589.0, 1.0], [16588.0, 189.0], [16587.6, 191.0], [16587.5, 185.0], [16587.3, 200.0], [16585.0, 1.0], [16582.0, 744.0], [16579.1, 13293.0], [16577.3, 44.0], [16577.0, 2.0], [16575.0, 1.0], [16574.1, 73.0], [16572.3, 14.0], [16572.2, 186.0], [16572.0, 271.0], [16571.5, 66.0], [16570.9, 269.0], [16570.6, 29955.0], [16570.5, 382.0], [16570.4, 1.0], [16567.9, 6.0], [16565.7, 51.0], [16562.6, 18.0], [16562.5, 16854.0], [16560.7, 46.0], [16558.3, 19632.0], [16557.8, 2.0], [16557.5, 1.0], [16555.7, 63.0], [16555.0, 100.0], [16552.4, 47.0], [16551.9, 5.0], [16551.0, 277.0], [16550.7, 820.0], [16550.1, 307.0], [16550.0, 1425.0], [16549.9, 282.0], [16548.3, 519.0], [16545.8, 60.0], [16545.5, 493.0], [16545.2, 12505.0], [16543.1, 1.0], [16542.3, 1032.0], [16541.0, 60.0], [16540.8, 51.0], [16540.0, 532.0], [16538.7, 106.0], [16538.0, 5.0], [16536.0, 5.0], [16535.8, 61.0], [16535.0, 1.0], [16530.8, 47.0], [16530.2, 398.0], [16530.1, 900.0], [16528.8, 1.0], [16527.1, 1.0], [16525.9, 66.0], [16525.1, 14855.0], [16525.0, 4.0], [16522.5, 1.0], [16521.2, 402.0], [16520.9, 69.0]],
 'datetime': '2022-11-13T12:41:09.220Z',
 'nonce': 2672053637,
 'symbol': 'BTC/USDT:USDT',
 'timestamp': 1668343269220}
```

```
Python v3.9.7
CCXT v2.1.72
huobi.watchOrderBook(BTC/USDT)
{'asks': [[16603.06, 0.0949], [16603.07, 0.136116], [16603.22, 0.010196], [16603.23, 0.003635], [16603.82, 0.011428], [16604.95, 0.006757], [16604.97, 0.134169], [16605.53, 0.033449], [16605.54, 0.156126], [16605.56, 0.04], [16605.6, 0.000448], [16606.01, 0.18], [16606.16, 0.1], [16606.17, 0.06], [16606.34, 0.08], [16606.43, 0.132534], [16607.56, 0.071726], [16609.62, 0.07297], [16610.0, 2.666945], [16610.47, 0.076681], [16610.99, 0.1], [16613.11, 0.12], [16613.13, 0.077534], [16613.16, 0.003735], [16613.28, 0.240958], [16613.4, 5.162532], [16614.15, 0.074311], [16614.85, 0.601871], [16615.06, 0.1], [16615.09, 0.047922], [16616.0, 0.35], [16616.29, 0.2], [16616.6, 0.234265], [16617.47, 0.021064], [16618.26, 0.240909], [16618.4, 0.047696], [16618.83, 0.006023], [16619.25, 0.017353], [16619.26, 0.125747], [16619.92, 0.251876], [16620.79, 0.175], [16621.3, 0.13], [16623.23, 0.072], [16623.24, 0.030289], [16626.04, 0.8], [16626.56, 0.238096], [16630.92, 0.05], [16631.01, 0.05], [16631.02, 0.31781], [16631.1, 7.573999], [16633.74, 0.014067], [16633.8, 0.064831], [16635.31, 0.05544], [16636.83, 0.6943], [16637.07, 0.6863], [16637.55, 0.001783], [16637.99, 0.018031], [16639.35, 0.002945], [16639.4, 12.94943], [16640.83, 0.000461], [16645.29, 0.149631], [16646.53, 4e-06], [16646.56, 1.0], [16648.9, 0.35], [16649.8, 0.453813], [16650.0, 0.120282], [16651.29, 0.012677], [16652.53, 0.074041], [16652.54, 0.037259], [16655.01, 0.048324], [16655.04, 0.057113], [16659.38, 0.000261], [16662.19, 0.000862], [16665.0, 0.120024], [16667.55, 0.010823], [16671.84, 41.101382], [16672.55, 0.041952], [16675.05, 0.082874], [16676.3, 0.017963], [16676.31, 0.097984], [16677.56, 0.085871], [16680.06, 0.052672], [16681.31, 0.011154], [16683.77, 0.066108], [16683.82, 0.056642], [16685.07, 0.123985], [16685.68, 0.003433], [16686.32, 0.050638], [16687.58, 0.021439], [16688.83, 0.018922], [16695.42, 0.018443], [16695.65, 0.001945], [16696.35, 0.102517], [16696.77, 10.330147], [16703.96, 0.012588], [16705.76, 0.003459], [16710.06, 0.763581], [16710.6, 0.000313], [16712.13, 0.004804], [16712.36, 0.001219], [16713.23, 0.000751], [16714.28, 0.002076], [16718.0, 0.00033], [16728.53, 0.000193], [16729.45, 0.00018], [16730.0, 0.000281], [16733.0, 0.0205], [16733.13, 0.00646], [16733.33, 0.000252], [16735.77, 0.000794], [16736.4, 0.0205], [16736.45, 0.004838], [16737.0, 0.5254490191790644], [16738.66, 0.000182], [16739.13, 0.000443], [16740.83, 0.002065], [16741.24, 0.000299], [16742.6, 0.001794], [16743.87, 0.00036], [16745.71, 0.000718], [16746.0, 0.000622], [16746.9, 0.0205], [16747.0, 1.0], [16747.36, 0.000127], [16747.68, 0.001023], [16750.0, 0.055821], [16752.59, 0.001244], [16754.09, 0.001219], [16754.6, 0.0205], [16754.68, 0.048167], [16756.8, 0.000876], [16757.0, 1.0], [16758.57, 0.000559], [16759.2, 0.000403], [16762.71, 0.001661], [16766.08, 0.000142], [16767.0, 1.0], [16767.65, 0.000664], [16767.75, 0.000381], [16769.23, 0.003793], [16771.34, 0.000366], [16772.88, 0.01], [16774.57, 0.004827], [16774.86, 0.00137], [16775.31, 0.000211], [16775.51, 0.019289], [16777.0, 1.0], [16777.77, 0.000252], [16779.41, 0.009843], [16779.66, 0.00153]],
 'bids': [[16603.05, 0.093423], [16600.46, 0.236282], [16600.45, 0.01549], [16600.43, 0.138761], [16600.15, 0.022097], [16599.78, 0.136348], [16599.46, 0.08], [16599.3, 0.04], [16599.06, 0.02], [16598.9, 0.02], [16598.83, 0.16], [16598.78, 0.136348], [16598.24, 0.137554], [16597.57, 0.125488], [16597.08, 0.8], [16597.07, 0.038568], [16595.95, 0.069952], [16593.98, 0.2], [16593.41, 0.001812], [16593.37, 0.060303], [16592.8, 2.666945], [16591.7, 0.240964], [16590.0, 0.00015], [16589.75, 0.001683], [16589.52, 0.001247], [16589.36, 0.000659], [16589.04, 0.05544], [16588.45, 0.02], [16588.23, 0.001235], [16587.96, 0.25], [16587.88, 0.602849], [16586.72, 0.194886], [16585.89, 0.240919], [16584.06, 0.006786], [16583.98, 0.000284], [16583.4, 0.194019], [16580.11, 0.000371], [16580.1, 7.573999], [16580.08, 0.23938], [16579.0, 5.162532], [16577.44, 0.000878], [16577.23, 0.175], [16576.75, 0.259417], [16574.1, 0.072], [16574.09, 0.017158], [16571.7, 12.94943], [16571.42, 0.004101], [16570.88, 1.0], [16570.44, 0.000518], [16570.0, 1.0], [16569.69, 0.6943], [16567.89, 0.001815], [16566.52, 0.003848], [16565.28, 0.004495], [16564.27, 0.00066], [16563.08, 0.001219], [16560.95, 2.0863], [16557.82, 0.004495], [16556.58, 0.008091], [16554.05, 0.000357], [16551.72, 0.00052], [16551.02, 0.00053], [16550.2, 0.722526], [16546.2, 2.2], [16543.93, 41.779023], [16540.24, 25.337535], [16538.46, 0.00042], [16538.31, 0.000335], [16535.14, 0.023527], [16533.04, 0.000177], [16530.29, 0.000753], [16529.41, 0.001788], [16528.92, 0.000844], [16527.0, 0.004814], [16526.44, 0.037021], [16525.42, 0.000304], [16524.13, 0.000182], [16523.48, 0.092554], [16521.82, 0.001219], [16519.34, 0.000901], [16518.98, 0.000317], [16518.74, 0.148086], [16518.2, 0.0205], [16518.1, 0.016218], [16517.65, 0.000426], [16516.86, 0.002703], [16515.4, 0.0205], [16515.31, 15.162538], [16515.0, 0.137764], [16514.49, 0.001344], [16514.0, 0.001479], [16512.85, 0.001006], [16512.82, 0.000561], [16510.4, 0.0205], [16510.29, 0.069091], [16510.08, 0.382836], [16510.0, 0.01834], [16509.18, 0.00031], [16508.58, 0.001247], [16508.47, 0.001094], [16508.0, 0.000163], [16504.24, 0.080608], [16501.29, 0.029435], [16500.0, 0.24172], [16499.99, 0.003928], [16495.18, 0.024381], [16494.68, 0.095657], [16493.75, 0.478545], [16492.75, 0.001949], [16492.52, 0.060358], [16492.32, 0.000517], [16490.28, 0.056081], [16490.0, 0.000405], [16488.48, 0.000878], [16487.4, 0.000518], [16486.39, 0.079056], [16485.71, 0.001551], [16484.67, 0.01], [16484.66, 0.063069], [16480.66, 0.001219], [16480.0, 0.001585], [16478.0, 0.000204], [16476.37, 0.006786], [16473.8, 0.000153], [16473.01, 0.001477], [16471.8, 0.0085], [16470.6, 0.735647], [16470.29, 0.000298], [16469.38, 0.001064], [16468.55, 0.02184], [16468.26, 0.102426], [16467.36, 0.000293], [16466.11, 0.013956], [16466.06, 0.109406], [16463.86, 0.001808], [16462.48, 0.000182], [16461.53, 0.003381], [16455.88, 0.001235], [16452.22, 0.00053], [16451.58, 0.000638], [16450.0, 1.0005], [16449.09, 0.000681], [16448.84, 10.542637], [16448.27, 0.000185], [16445.83, 0.00018], [16444.2, 0.000382], [16440.0, 0.003041], [16439.61, 0.001219], [16438.83, 0.00012], [16438.82, 0.000433]],
 'datetime': '2022-11-13T12:41:23.103Z',
 'nonce': 160942562160,
 'symbol': 'BTC/USDT',
 'timestamp': 1668343283103}
```

**Review by carlosmiei — APPROVED** [review]
