### PR TITLE
huobi - fix balance

### LINKED ISSUE #16543: Huobi fetchBalance of linear error 4002
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.2.62

### Description

I am trying to fetch Huobi futures account balance and catch error

`
ExchangeError: Huobi {"status":"error","err_code":4002,"err_msg":"The merged cross and isolated margin account for USDT-M futures is unavailable. Please complete the query with linear-swap-api/v3/unified_account_info","ts":1674149112391}
`

Would someone be able to help me?

### Code

```
const balance = await huobiExchange.fetchTotalBalance({
		"defaultType" : "swap",
		"defaultSubType": "linear"
});

```

### PR DESCRIPTION
**Pull request by ttodua**
fix #16543

### CODE REVIEW

File: js/huobi.js [hunk 1]
```diff
@@ -2954,12 +2954,6 @@ module.exports = class huobi extends Exchange {
                 request['account-id'] = accountId;
                 method = 'spotPrivateGetV1AccountAccountsAccountIdBalance';
             }
-        } else if (margin) {
-            if (isolated) {
-                method = 'spotPrivateGetV1MarginAccountsBalance';
-            } else {
-                method = 'spotPrivateGetV1CrossMarginAccountsBalance';
-            }
```
Comment (ttodua) [inline js/huobi.js:2962]: these endpoints were just duplicated, they should have been in above `if (spot || margin)` clause, like I've edited.

File: js/huobi.js [hunk 2]
```diff
@@ -3159,14 +3153,7 @@ module.exports = class huobi extends Exchange {
...
         } else if (linear) {
             const first = this.safeValue (data, 0, {});
-            if (cross) {
-                const account = this.account ();
-                account['free'] = this.safeString (first, 'margin_balance', 'margin_available');
-                account['used'] = this.safeString (first, 'margin_frozen');
-                const currencyId = this.safeString2 (first, 'margin_asset', 'symbol');
-                const code = this.safeCurrencyCode (currencyId);
-                result[code] = account;
-            } else if (isolated) {
```
Comment (ttodua) [inline js/huobi.js:3169]: just moved this `if (cross)` block in `else` clause below `if (isolated) ...`, because in all above part of the method, the logic is like that `if (isolated) else...` where `cross` is always meant in `else`.

File: js/huobi.js [hunk 3]
```diff
@@ -3187,7 +3174,13 @@ module.exports = class huobi extends Exchange {
                         result[symbol] = this.safeBalance (accountsByCode);
                     }
                 }
-                return result;
```
Comment (ttodua) [inline js/huobi.js:3190]: removed `return` from here, and moved in the last line of the method.

File: js/huobi.js [hunk 4]
```diff
@@ -3199,9 +3196,9 @@ module.exports = class huobi extends Exchange {
                 account['used'] = this.safeString (balance, 'margin_frozen');
                 result[code] = account;
             }
+            result = this.safeBalance (result);
         }
-        const isolatedMargin = isolated && (spot || margin);
-        return isolatedMargin ? result : this.safeBalance (result);
```
Comment (ttodua) [inline js/huobi.js:3204]: these two lines were vague, instead, i've moved the `.safeBalance` to places where it was needed.

File: js/huobi.js [hunk 5]
```diff
@@ -2943,23 +2942,20 @@ module.exports = class huobi extends Exchange {
         params = this.omit (params, [ 'defaultSubType', 'subType' ]);
         const isolated = (marginMode === 'isolated');
         const cross = (marginMode === 'cross');
-        if (spot) {
-            if (isolated) {
-                method = 'spotPrivateGetV1MarginAccountsBalance';
-            } else if (cross) {
-                method = 'spotPrivateGetV1CrossMarginAccountsBalance';
+        const margin = (type === 'margin') || cross || isolated;
```
Comment (carlosmiei) [inline js/huobi.js:2945]: @ttodua something is off here 
```
 p huobi balance
Python v3.10.9
CCXT v2.7.33
{}
huobi requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
```

Comment (ttodua) [reply js/huobi.js]: ah, forgot to place spot. please recheck now.
all I wanted to mean is that, if someone uses `fetchBalance ({marginMode: 'isolated/cross'})` I mean that user is requesting spot margin balance (isolated/cross). is not that correct expectation?

Comment (ttodua) [reply js/huobi.js]: hm, python version breaks, give me a min.

Comment (ttodua) [reply js/huobi.js]: the error seems to be happening in master too, without this PR.
```
cli.py huobi fetchBalance

Python v3.10.9
CCXT v2.7.33
Traceback (most recent call last):
  File "py\cli.py", line 232, in <module>
    asyncio.run(main())
  File "..\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "..\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "py\cli.py", line 109, in main
    keys = json.load(file)
  File "..\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "..\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 3901: character maps to <undefined>
```

Comment (ttodua) [reply js/huobi.js]: the last comment of mine turns out to be my local issue (another PR ready for that), but with this PR, i think there is no error at all. please re-check and let me know a bit more verbose log what/where you face issue.

Comment (carlosmiei) [reply js/huobi.js]: >  fetchBalance ({marginMode: 'isolated/cross'}) I mean that user is requesting spot margin balance 
@ttodua yes I think that is correct unless we have the ambiguity between isolated/cross on the swap wallet as well

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
2023-02-03T15:32:29.158Z
Node.js: v17.9.0
CCXT v2.7.33
huobi.fetchBalance ()
2023-02-03T15:32:34.874Z iteration 0 passed in 3374 ms

{
  IOI: { free: 0, used: 0, total: 0 },
  KSM: { free: 0, used: 0, total: 0 },
  TDX: { free: 0, used: 0, total: 0 },
  KCASH: { free: 0, used: 0, total: 0 },
  OPUL: { free: 0, used: 0, total: 0 },
  THETA: { free: 0, used: 0, total: 0 },
  EGS: { free: 0, used: 0, total: 0 },
```
```

2023-02-03T15:32:48.620Z
Node.js: v17.9.0
CCXT v2.7.33
huobi.fetchBalance ([object Object])
2023-02-03T15:32:51.284Z iteration 0 passed in 392 ms

{
  'LTC/USDT': {
    LTC: {
      free: 0.000008246105804156,
      used: 0,
      total: 0.000008246105804156
    },
    USDT: { free: 1.12e-15, used: 2e-18, total: 1.122e-15 },
    free: { LTC: 0.000008246105804156, USDT: 1.12e-15 },
    used: { LTC: 0, USDT: 2e-18 },
    total: { LTC: 0.000008246105804156, USDT: 1.122e-15 }
  },
  'ADA/USDT': {
    ADA: { free: 29.94000207132762, used: 0, total: 29.94000207132762 },
    USDT: { free: 1.0509500051832, used: 1e-18, total: 1.0509500051832 },
    free: { ADA: 29.94000207132762, USDT: 1.0509500051832 },
    used: { ADA: 0, USDT: 1e-18 },
    total: { ADA: 29.94000207132762, USDT: 1.0509500051832 }
  }
}
```
```
2023-02-03T15:33:10.025Z
Node.js: v17.9.0
CCXT v2.7.33
huobi.fetchBalance ([object Object])
2023-02-03T15:33:34.005Z iteration 0 passed in 21575 ms

{
  USDT: { free: 7.381427722875449, used: 0, total: 7.381427722875449 },
  free: { USDT: 7.381427722875449 },
  used: { USDT: 0 },
  total: { USDT: 7.381427722875449 }
}
2023-02-03T15:33:34.005Z iteration 1 passed in 21575 ms

```
```
2023-02-03T15:34:10.832Z
Node.js: v17.9.0
CCXT v2.7.33
huobi.fetchBalance ([object Object])
2023-02-03T15:34:16.116Z iteration 0 passed in 2972 ms

{
  USDT: { free: 14.574370218, used: 1e-18, total: 14.574370218 },
  LTC: { free: 0.000896272861189802, used: 0, total: 0.000896272861189802 },
  ADA: { free: 0, used: 0, total: 0 },
  AVAX: { free: undefined, used: undefined, total: undefined },
  KSM: { free: undefined, used: undefined, total: undefined },
  WICC: { free: undefined, used: undefined, total: undefined },
  DOGE: { free: undefined, used: undefined, total: undefined },
  FIL: { free: undefined, used: undefined, total: undefined },
  EOS: { free: undefined, used: undefined, total: undefined },
  HT: { free: undefined, used: undefined, total: undefined },
  THETA: { free: undefined, used: undefined, total: undefined },
  SOL: { free: undefined, used: undefined, total: undefined },
  LOOKS: { free: undefined, used: undefined, total: undefined },
```

**Review by carlosmiei — APPROVED** [review]
