### PR TITLE
Fix bittrex OHLCV endpoint

### LINKED ISSUE #7317: bittrex v3 fetch_ohlcv broken when supplying "since" for longer timeframes
- OS: linux
- Programming Language version: python
- CCXT version: 1.31.62

When fetching candles from bittrex, requests fail with 
`ExchangeNotAvailable: GET https://api.bittrex.com/v3/markets/ETH-USDT/candles/DAY_1/historical/2020/7/19 400 Bad Request {"code":"INVALID_DATE"}`.

``` python
import ccxt
from datetime import datetime, timedelta
ct  = ccxt.bittrex()
lm = ct.load_markets()

since = datetime.now() - timedelta(days=2)
# Broken
x = ct.fetch_ohlcv(pair, timeframe='1d', since=int(since.timestamp() * 1000))
# Broken
x = ct.fetch_ohlcv(pair, timeframe='1h', since=int(since.timestamp() * 1000))

# 5m and 1m are the only cases which seem to work when supplying a "since" argument.
x = ct.fetch_ohlcv(pair, timeframe='5m', since=int(since.timestamp() * 1000))

```

Now the problem seems to be "described" in the [changelog](https://bittrex.github.io/api/v3):

> Historical candles endpoint will no longer allow you to specify more portions of the date parameters than are necessary for the selected candle interval. Specify only year for day candles. Specify only year and month for hour candles.

The description of the API endpoint itself does not seem to describe this correctly ... it only says about the paremeters "month" and  "day": if applicable (but not when ...).

Now this results in something around the following logic:

*valid*:
https://api.bittrex.com/v3/markets/ETH-BTC/candles/DAY_1/historical/2019
https://api.bittrex.com/v3/markets/ETH-BTC/candles/DAY_1/recent (to get current trades)

*invalid*:
https://api.bittrex.com/v3/markets/ETH-BTC/candles/DAY_1/historical/2020  -> current year ...
https://api.bittrex.com/v3/markets/ETH-BTC/candles/DAY_1/historical/2020/01/01
https://api.bittrex.com/v3/markets/ETH-BTC/candles/DAY_1/historical/2019/01/01 -> Should not supply month

same for hourly candles:
*valid*:
https://api.bittrex.com/v3/markets/ETH-BTC/candles/HOUR_1/historical/2020/05

*invalid* 
https://api.bittrex.com/v3/markets/ETH-BTC/candles/HOUR_1/historical/2020/05/01
https://api.bittrex.com/v3/markets/ETH-BTC/candles/HOUR_1/historical/2020/07 -> current month

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    580             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 581             response.raise_for_status()
    582 

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 

HTTPError: 400 Client Error: Bad Request for url: https://api.bittrex.com/v3/markets/ETH-USDT/candles/DAY_1/historical/2020/7/19

During handling of the above exception, another exception occurred:

ExchangeNotAvailable                      Traceback (most recent call last)
<ipython-input-8-24d01dede9cb> in <module>
      1 since = datetime.now() - timedelta(days=2)
----> 2 ct.fetch_ohlcv(pair, timeframe='1d', since=int(since.timestamp() * 1000))

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/bittrex.py in fetch_ohlcv(self, symbol, timeframe, since, limit, params)
    660                 request['month'] = month
    661                 request['day'] = day
--> 662         response = getattr(self, method)(self.extend(request, params))
    663         #
    664         #     [

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/base/exchange.py in inner(_self, params)
    461                             if params is not None:
    462                                 inner_kwargs['params'] = params
--> 463                             return entry(_self, **inner_kwargs)
    464                         return inner
    465                     to_bind = partialer()

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/bittrex.py in request(self, path, api, method, params, headers, body)
   1442 
   1443     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
-> 1444         response = self.fetch2(path, api, method, params, headers, body)
   1445         # a workaround for APIKEY_INVALID
   1446         if (api == 'account') or (api == 'market'):

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body)
    480         self.lastRestRequestTimestamp = self.milliseconds()
    481         request = self.sign(path, api, method, params, headers, body)
--> 482         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    483 
    484     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    592         except HTTPError as e:
    593             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
--> 594             self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
    595             raise ExchangeError(method + ' ' + url)
    596 

~/.pyenv/versions/3.8.2/envs/trade_382/lib/python3.8/site-packages/ccxt/base/exchange.py in handle_rest_errors(self, http_status_code, http_status_text, body, url, method)
    619                     error = DDoSProtection
    620         if error:
--> 621             raise error(' '.join([method, url, string_code, http_status_text, body]))
    622 
    623     def handle_rest_response(self, response, json_response, url, method):

ExchangeNotAvailable: GET https://api.bittrex.com/v3/markets/ETH-USDT/candles/DAY_1/historical/2020/7/19 400 Bad Request {"code":"INVALID_DATE"}
```

### PR DESCRIPTION
**Pull request by xmatthias**
As described in #7317 - bittrex logic for historic endpoints did change recently, to not accept month / day arguments for the daily history endpoint.

If needed, i also have a sample (copy from `binance-fetch-ohlcv.js`) which can serve as a testing example for this behaviour (by modifying times / years).

I hope the way the logic is done is kind of compatible with the way ccxt does this normally (it transpiles fine ...) - if you need changes done let me know (or adjust as needed).

closes #7317

### CODE REVIEW

File: js/bittrex.js [hunk 1]
```diff
@@ -659,13 +661,26 @@ module.exports = class bittrex extends Exchange {
...
+            const parts = date.split ('-');
+            const year = this.safeInteger (parts, 0);
+            const month = this.safeInteger (parts, 1);
+            const day = this.safeInteger (parts, 2);
+            const curr_date = this.ymd (now);
+            const curr_parts = curr_date.split ('-');
+            const curr_year = this.safeInteger (curr_parts, 0);
+            const curr_month = this.safeInteger (curr_parts, 1);
+            if (timeframe === '1d' && year !== curr_year) {
+                // Current year is provided by the "current" endpoint
```
Comment (kroitor) [inline js/bittrex.js:674]: @xmatthias can you plz comment a bit on this line, what is meant under the "current" endpoint here?

Comment (kroitor) [reply js/bittrex.js:674]: As far as i see from their docs, they currently have two endpoints, namely:

- A _"recent"_ endpoint https://bittrex.github.io/api/v3#operation--markets--marketSymbol--candles--candleInterval--recent-get
- And a _"historical"_ endpoint https://bittrex.github.io/api/v3#operation--markets--marketSymbol--candles--candleInterval--historical--year---month---day--get

However, it's not entirely clear what "recent" and "historical" refer to.

Comment (xmatthias) [reply js/bittrex.js]: I think the key for this is in the changelog: https://bittrex.github.io/api/v3#topic-Change-Log (From 05/27/2020).

Basically, the historical endpoint provides history (excluding current month (for 1h) or current year (for 1d)) candles.
For current year / current month (1h) - the "recent" endpoint should be used.

clearly, my "spelling" is wrong - where it says "current" endpoint, it's really "recent" endpoint (must've mixed that up in my mind) (i've fixed this now).

Comment (kroitor) [reply js/bittrex.js]: @xmatthias alright, thanks for clarifying it for me ) I'll add the _"recent"_ family of endpoints and will make a few minor edits for it, will merge today! Thx again!

Comment (xmatthias) [reply js/bittrex.js]: i thought `v3publicGetMarketsMarketSymbolCandles` would cover this? (this does work fine to get the latest candles - and is what the above logic falls back to if the timerange is determined to be "recent").


also major edits are good - my javascript is improving - so i'll for sure look at your edits to learn 👍

Comment (kroitor) [reply js/bittrex.js]: > i thought v3publicGetMarketsMarketSymbolCandles would cover this? (this does work fine to get the latest candles - and is what the above logic falls back to if the timerange is determined to be "recent").

Yep, it works, but according to their doc it may go down anytime now, so we'd better move to their new schema entirely.

**Comment by xmatthias** [comment]
Great - this endpoint does make more sense (and simplifies the logic at the same time)!
Thanks a lot!
