### PR TITLE
Poloniex Futures

### LINKED ISSUE #16099: poloniex for future
In poloniex, it seems functions does not work for futures. 
for example, create_order, fetch_order, and so on.

If so, could you implement?

### PR DESCRIPTION
**Pull request by AlgoQ**
fix #16099

# Testing
## Python
**fetchMarkets**
`python3 examples/py/cli.py poloniexfutures fetchMarkets`
```js
[{
  'active': True,
  'base': 'APT',
  'baseId': 'APT',
  'contract': True,
  'contractSize': 1.0,
  'expiry': None,
  'expiryDatetime': None,
  'future': False,
  'id': 'APTUSDTPERP',
  'info': {'baseCurrency': 'APT',
           'createdAt': '1666681959000',
           'displayNameMap': {'contractName_en-US': 'APT '
                                                    'Perpetual(USDT-Margined)',
                              'contractName_ko-KR': 'APT계속(USDT-마진)',
                              'contractName_zh-CN': 'APT永续(USDT结算)'},
           'displaySettleCurrency': 'USDT',
           'fairMethod': 'FundingRate',
           'firstOpenDate': '1666701000000',
           'fundingBaseSymbol': '.APTINT8H',
           'fundingFeeRate': '0.000000',
           'fundingQuoteSymbol': '.USDTINT8H',
           'fundingRateSymbol': '.APTUSDTPERPFPI8H',
           'highPriceOf24h': '4.119999885559082',
           'indexPrice': '4.044',
           'indexPriceTickSize': '0.001',
           'indexSymbol': '.PAPTUSDT',
           'initialMargin': '0.05',
           'isDeleverage': True,
           'isInverse': False,
           'isQuanto': True,
           'lastTradePrice': '4.0430000000',
           'lotSize': '1',
           'lowPriceOf24h': '3.928999900817871',
           'maintainMargin': '0.025',
           'makerFeeRate': '0.00010',
           'makerFixFee': '0E-10',
           'markMethod': 'FairPrice',
           'markPrice': '4.044',
           'maxLeverage': '20',
           'maxOrderQty': '1000000',
           'maxPrice': '1000000.0000000000',
           'maxRiskLimit': '20000',
           'minRiskLimit': '1000000',
           'multiplier': '1.0',
           'nextFundingRateTime': '13270577',
           'openInterest': '3662',
           'order': '102',
           'predictedFundingFeeRate': '0.000000',
           'priceChgPctOf24h': '0.0037',
           'quoteCurrency': 'USDT',
           'riskStep': '500000',
           'rootSymbol': 'USDT',
           'settleCurrency': 'USDT',
           'settlementFeeRate': '0.0',
           'settlementFixFee': '0E-10',
           'settlementSymbol': '',
           'status': 'Open',
           'symbol': 'APTUSDTPERP',
           'takerFeeRate': '0.00040',
           'takerFixFee': '0E-10',
           'tickSize': '0.001',
           'turnoverOf24h': '340165.37604618',
           'type': 'FFWCSX',
           'updatedAt': '1671076377000',
           'volumeOf24h': '84040.00000000'},
  'inverse': False,
  'limits': {'amount': {'max': 1000000.0, 'min': 1.0},
             'cost': {'max': None, 'min': None},
             'leverage': {'max': 20.0, 'min': 1.0},
             'price': {'max': 1000000.0, 'min': 0.001}},
  'linear': True,
  'maker': 0.0001,
  'margin': False,
  'option': False,
  'optionType': None,
  'precision': {'amount': 1.0, 'price': 0.001},
  'quote': 'USDT',
  'quoteId': 'USDT',
  'settle': 'USDT',
  'settleId': 'USDT',
  'spot': False,
  'strike': None,
  'swap': True,
  'symbol': 'APT/USDT:USDT',
  'taker': 0.0004,
  'type': 'swap'},
  ]
```

**fetchOHLCV**
`python3 examples/py/cli.py poloniexfutures fetchOHLCV "BTC/USDT:USDT"`
```js
[
 [1671466680000, 16687.8, 16694.4, 16676.0, 16677.4, 94.0],
 [1671466740000, 16677.9, 16684.4, 16673.1, 16682.7, 33.0],
 [1671466800000, 16685.4, 16685.4, 16682.8, 16683.1, 14.0],
 [1671466860000, 16681.1, 16681.1, 16681.1, 16681.1, 1.0]
]
```

**fetchOrderBook**
`python3 examples/py/cli.py poloniexfutures fetchOrderBook "BTC/USDT:USDT"`
```js
{
 'bids': [
 ],
 'asks': [
 ],
 'datetime': '2022-12-19T19:50:49.861Z',
 'nonce': None,
 'symbol': 'BTC/USDT:USDT',
 'timestamp': 1671479449861
}
```

**fetchTicker(s)**
`python3 examples/py/cli.py poloniexfutures fetchTickers`
```js
{
'XRP/USDT:USDT': {
                   'ask': 0.3372,
                   'askVolume': 3941.0,
                   'average': None,
                   'baseVolume': None,
                   'bid': 0.3366,
                   'bidVolume': 1974.0,
                   'change': None,
                   'close': 0.3368,
                   'datetime': '2022-12-19T19:54:29.269Z',
                   'high': None,
                   'info': {'bestAskPrice': '0.3372',
                            'bestAskSize': '3941',
                            'bestBidPrice': '0.3366',
                            'bestBidSize': '1974',
                            'price': '0.3368',
                            'sequence': '2256609',
                            'side': 'buy',
                            'size': '11',
                            'symbol': 'XRPUSDTPERP',
                            'tradeId': '63a0c175a4c00b0001da907c',
                            'ts': '1671479669269864051'},
                   'last': 0.3368,
                   'low': None,
                   'open': None,
                   'percentage': None,
                   'previousClose': None,
                   'quoteVolume': None,
                   'symbol': 'XRP/USDT:USDT',
                   'timestamp': 1671479669269,
                   'vwap': None},
 'YFI/USDT:USDT': {
                   'ask': 5537.0,
                   'askVolume': 2346.0,
                   'average': None,
                   'baseVolume': None,
                   'bid': 5525.0,
                   'bidVolume': 550.0,
                   'change': None,
                   'close': 5531.0,
                   'datetime': '2022-12-19T19:54:37.750Z',
                   'high': None,
                   'info': {'bestAskPrice': '5537.0',
                            'bestAskSize': '2346',
                            'bestBidPrice': '5525.0',
                            'bestBidSize': '550',
                            'price': '5531.0',
                            'sequence': '2803988',
                            'side': 'buy',
                            'size': '93',
                            'symbol': 'YFIUSDTPERP',
                            'tradeId': '63a0c17d62742b00014d4145',
                            'ts': '1671479677750627749'},
                   'last': 5531.0,
                   'low': None,
                   'open': None,
                   'percentage': None,
                   'previousClose': None,
                   'quoteVolume': None,
                   'symbol': 'YFI/USDT:USDT',
                   'timestamp': 1671479677750,
                   'vwap': None}
}
```

**fetchTime**
`python3 examples/py/cli.py poloniexfutures fetchTime`
```js
1671479873570
```

**fetchTrades**
`python3 examples/py/cli.py poloniexfutures fetchTrades "BTC/USDT:USDT"`
```js
[
{'amount': 1.0,
  'cost': 16.5487,
  'datetime': '2022-12-19T19:58:26.341Z',
  'fee': None,
  'fees': [],
  'id': '63a0c2629fd7cf0001cb9687',
  'info': {'makerOrderId': '63a0c26256fa50000700a3b0',
           'price': '16548.7000000000',
           'sequence': '11885340',
           'side': 'buy',
           'size': '1',
           'takerOrderId': '63a0c26272403f0008f92fac',
           'tradeId': '63a0c2629fd7cf0001cb9687',
           'ts': '1671479906341220487'},
  'order': None,
  'price': 16548.7,
  'side': 'buy',
  'symbol': 'BTC/USDT:USDT',
  'takerOrMaker': None,
  'timestamp': 1671479906341,
  'type': None},
 {'amount': 2.0,
  'cost': 33.0976,
  'datetime': '2022-12-19T19:58:29.950Z',
  'fee': None,
  'fees': [],
  'id': '63a0c2659fd7cf0001cb96ce',
  'info': {'makerOrderId': '63a0c265bdd6cc0007dabe4e',
           'price': '16548.8000000000',
           'sequence': '11885341',
           'side': 'buy',
           'size': '2',
           'takerOrderId': '63a0c2651a5b790007be74be',
           'tradeId': '63a0c2659fd7cf0001cb96ce',
           'ts': '1671479909950386832'},
  'order': None,
  'price': 16548.8,
  'side': 'buy',
  'symbol': 'BTC/USDT:USDT',
  'takerOrMaker': None,
  'timestamp': 1671479909950,
  'type': None}
]
```

**fetchBalance**
`python3 examples/py/cli.py poloniexfutures fetchBalance`
```js
{'USDT': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'datetime': None,
 'free': {'USDT': 0.0},
 'info': {'code': '200000',
          'data': {'accountEquity': '0E-8',
                   'availableBalance': '0E-8',
                   'currency': 'USDT',
                   'frozenFunds': '0E-8',
                   'marginBalance': '0E-8',
                   'orderMargin': '0E-8',
                   'pnl': '0E-8',
                   'positionMargin': '0E-8',
                   'trialAccountOverview': {'availableBalance': '0E-8',
                                            'holdBalance': '0E-8',
                                            'totalBalance': '0E-8'},
                   'unrealisedPNL': '0E-8'}},
 'timestamp': None,
 'total': {'USDT': 0.0},
 'used': {'USDT': 0.0}}
```

**createOrder**
`python3 examples/py/cli.py poloniexfutures createOrder "ETH/USDT" "limit" "buy" "1" "1000" '{"leverage": 5}'`
```js
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'filled': None,
 'id': '63a9c5c2b9e7d70007eb0cd5',
 'info': {'code': '200000', 'data': {'orderId': '63a9c5c2b9e7d70007eb0cd5'}},
 'lastTradeTimestamp': None,
 'postOnly': None,
 'price': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopPrice': None,
 'symbol': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': None,
 'type': None}
```

**cancelOrder**
`python3 examples/py/cli.py poloniexfutures cancelOrder ""`
```js
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'filled': None,
 'id': '63a9c5c2b9e7d70007eb0cd5',
 'info': {
    code: "200000",
    data: {
        cancelledOrderIds: [
             "619714b8b6353000014c505a",
        ],
    },
 },
 'lastTradeTimestamp': None,
 'postOnly': None,
 'price': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopPrice': None,
 'symbol': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': None,
 'type': None}
```

**fetchPositions**
`python3 examples/py/cli.py poloniexfutures fetchPositions`
```js
[{'collateral': 2.4282344,
  'contractSize': 0.01,
  'contracts': 1.0,
  'datetime': None,
  'entryPrice': 1215.5,
  'id': None,
  'info': {'autoDeposit': False,
           'avgEntryPrice': '1215.50',
           'bankruptPrice': '972.40',
           'currentComm': '0.00486200',
           'currentCost': '12.15500000',
           'currentQty': '1',
           'currentTimestamp': '1672069519623',
           'delevPercentage': '0.23',
           'id': '63a9bf5c6cdfeb000a1b9ed8',
           'isOpen': True,
           'liquidationPrice': '979.10',
           'maintMargin': '2.42823440',
           'maintMarginReq': '0.0055',
           'marginType': '0',
           'markPrice': '1214.64',
           'markValue': '12.14640000',
           'maxWithdrawMarginAmount': '0',
           'openingTimestamp': '1672068956412',
           'posComm': '0.00583440',
           'posCost': '12.15500000',
           'posCross': '0E-10',
           'posInit': '2.43100000',
           'posLoss': '0E-8',
           'posMaint': '0.07268690',
           'posMargin': '2.43683440',
           'realLeverage': '5.02',
           'realisedCost': '0.00486200',
           'realisedGrossCost': '0E-8',
           'realisedGrossPnl': '0E-8',
           'realisedPnl': '-0.00486200',
           'riskLimit': '1000000',
           'settleCurrency': 'USDT',
           'symbol': 'ETHUSDTPERP',
           'unrealisedCost': '12.15500000',
           'unrealisedPnl': '-0.00860000',
           'unrealisedPnlPcnt': '-0.0007',
           'unrealisedRoePcnt': '-0.0035'},
  'initialMargin': 2.431,
  'initialMarginPercentage': 0.2,
  'leverage': 5.02,
  'liquidationPrice': 979.1,
  'maintenanceMargin': 0.0726869,
  'maintenanceMarginPercentage': 0.0055,
  'marginMode': 'isolated',
  'marginRatio': None,
  'markPrice': 1214.64,
  'notional': 12.155,
  'percentage': -0.003537638831756478,
  'side': 'long',
  'symbol': 'ETH/USDT:USDT',
  'timestamp': 1672069519623.0,
  'unrealizedPnl': -0.0086}]
```

**fetchFundingRate**
`python3 examples/py/cli.py poloniexfutures fetchFundingRate "ETH/USDT:USDT"`
```js
{'datetime': None,
 'estimatedSettlePrice': None,
 'fundingDatetime': None,
 'fundingRate': 0.0,
 'fundingTimestamp': None,
 'indexPrice': None,
 'info': {'granularity': '28800000',
          'predictedValue': '0.000000',
          'symbol': '.ETHUSDTPERPFPI8H',
          'timePoint': '1672228800000',
          'value': '0.000000'},
 'interestRate': None,
 'markPrice': None,
 'nextFundingDatetime': None,
 'nextFundingRate': None,
 'nextFundingTimestamp': None,
 'previousFundingDatetime': None,
 'previousFundingRate': 0.0,
 'previousFundingTimestamp': 1672228800000.0,
 'symbol': 'ETH/USDT:USDT',
 'timestamp': None}
```

**fetchFundingHistory**
`python3 examples/py/cli.py poloniexfutures fetchFundingHistory "ETH/USDT:USDT"`
```js
[
]
```

**cancelAllOrders**
`python3 examples/py/cli.py poloniexfutures cancelAllOrders`
```js
[{'amount': None,
  'average': None,
  'clientOrderId': None,
  'cost': None,
  'datetime': None,
  'fee': None,
  'filled': None,
  'id': '63ac64fba62d850008e8ccb4',
  'info': {'code': '200000',
           'data': {'cancelFailedOrders': [],
                    'cancelledOrderIds': ['63ac64fba62d850008e8ccb4',
                                          '63ac65072efd7d0007c177bc']}},
  'lastTradeTimestamp': None,
  'postOnly': None,
  'price': None,
  'remaining': None,
  'side': None,
  'status': None,
  'stopPrice': None,
  'symbol': None,
  'timeInForce': None,
  'timestamp': None,
  'trades': None,
  'type': None},
 {'amount': None,
  'average': None,
  'clientOrderId': None,
  'cost': None,
  'datetime': None,
  'fee': None,
  'filled': None,
  'id': '63ac65072efd7d0007c177bc',
  'info': {'code': '200000',
           'data': {'cancelFailedOrders': [],
                    'cancelledOrderIds': ['63ac64fba62d850008e8ccb4',
                                          '63ac65072efd7d0007c177bc']}},
  'lastTradeTimestamp': None,
  'postOnly': None,
  'price': None,
  'remaining': None,
  'side': None,
  'status': None,
  'stopPrice': None,
  'symbol': None,
  'timeInForce': None,
  'timestamp': None,
  'trades': None,
  'type': None}]
```

**fetchOpenOrders**
`python3 examples/py/cli.py poloniexfutures fetchOpenOrders`
```js
[{'amount': 1.0,
  'average': None,
  'clientOrderId': None,
  'cost': 0.0,
  'datetime': '2022-12-28T15:51:36.000Z',
  'fee': {'cost': None, 'currency': None},
  'fees': [{'cost': None, 'currency': None}],
  'filled': 0.0,
  'id': '63ac6607fd895f0007c83903',
  'info': {'cancelExist': False,
           'closeOrder': False,
           'createdAt': '1672242696000',
           'dealSize': '0',
           'dealValue': '0',
           'filledSize': '0',
           'filledValue': '0',
           'forceHold': False,
           'hidden': False,
           'iceberg': False,
           'id': '63ac6607fd895f0007c83903',
           'isActive': True,
           'leverage': '5',
           'marginType': '0',
           'orderTime': '1672242696016442068',
           'postOnly': True,
           'price': '1000',
           'reduceOnly': False,
           'settleCurrency': 'USDT',
           'side': 'buy',
           'size': '1',
           'status': 'open',
           'stop': '',
           'stopPriceType': '',
           'stopTriggered': False,
           'stp': '',
           'symbol': 'ETHUSDTPERP',
           'timeInForce': 'GTC',
           'type': 'limit',
           'updatedAt': '1672242696000',
           'value': '10'},
  'lastTradeTimestamp': None,
  'postOnly': True,
  'price': 1000.0,
  'remaining': 1.0,
  'side': 'buy',
  'status': 'open',
  'stopPrice': None,
  'symbol': 'ETH/USDT:USDT',
  'timeInForce': 'GTC',
  'timestamp': 1672242696000,
  'trades': [],
  'type': 'limit'},
 {'amount': 1.0,
  'average': None,
  'clientOrderId': None,
  'cost': 0.0,
  'datetime': '2022-12-28T15:51:47.000Z',
  'fee': {'cost': None, 'currency': None},
  'fees': [{'cost': None, 'currency': None}],
  'filled': 0.0,
  'id': '63ac6613fd895f0007c83e48',
  'info': {'cancelExist': False,
           'closeOrder': False,
           'createdAt': '1672242707000',
           'dealSize': '0',
           'dealValue': '0',
           'filledSize': '0',
           'filledValue': '0',
           'forceHold': False,
           'hidden': False,
           'iceberg': False,
           'id': '63ac6613fd895f0007c83e48',
           'isActive': True,
           'leverage': '5',
           'marginType': '0',
           'orderTime': '1672242707267535781',
           'postOnly': True,
           'price': '1100',
           'reduceOnly': False,
           'settleCurrency': 'USDT',
           'side': 'buy',
           'size': '1',
           'status': 'open',
           'stop': '',
           'stopPriceType': '',
           'stopTriggered': False,
           'stp': '',
           'symbol': 'ETHUSDTPERP',
           'timeInForce': 'GTC',
           'type': 'limit',
           'updatedAt': '1672242707000',
           'value': '11'},
  'lastTradeTimestamp': None,
  'postOnly': True,
  'price': 1100.0,
  'remaining': 1.0,
  'side': 'buy',
  'status': 'open',
  'stopPrice': None,
  'symbol': 'ETH/USDT:USDT',
  'timeInForce': 'GTC',
  'timestamp': 1672242707000,
  'trades': [],
  'type': 'limit'}]
```

**fetchClosedOrders**
`python3 examples/py/cli.py poloniexfutures fetchClosedOrders`
```js
[
{'amount': 1.0,
  'average': None,
  'clientOrderId': None,
  'cost': 0.0,
  'datetime': '2022-12-28T15:47:07.000Z',
  'fee': {'cost': None, 'currency': None},
  'fees': [{'cost': None, 'currency': None}],
  'filled': 0.0,
  'id': '63ac64fba62d850008e8ccb4',
  'info': {'cancelExist': True,
           'closeOrder': False,
           'createdAt': '1672242427000',
           'dealSize': '0',
           'dealValue': '0',
           'endAt': '1672242486000',
           'filledSize': '0',
           'filledValue': '0',
           'forceHold': False,
           'hidden': False,
           'iceberg': False,
           'id': '63ac64fba62d850008e8ccb4',
           'isActive': False,
           'leverage': '5',
           'marginType': '0',
           'orderTime': '1672242427571246999',
           'postOnly': True,
           'price': '1000',
           'reduceOnly': False,
           'remark': 'Order Cancel:The order is canceled by user',
           'settleCurrency': 'USDT',
           'side': 'buy',
           'size': '1',
           'status': 'done',
           'stop': '',
           'stopPriceType': '',
           'stopTriggered': False,
           'stp': '',
           'symbol': 'ETHUSDTPERP',
           'timeInForce': 'GTC',
           'type': 'limit',
           'updatedAt': '1672242486000',
           'value': '10'},
  'lastTradeTimestamp': None,
  'postOnly': True,
  'price': 1000.0,
  'remaining': 1.0,
  'side': 'buy',
  'status': 'canceled',
  'stopPrice': None,
  'symbol': 'ETH/USDT:USDT',
  'timeInForce': 'GTC',
  'timestamp': 1672242427000,
  'trades': [],
  'type': 'limit'},
 {'amount': 1.0,
  'average': None,
  'clientOrderId': None,
  'cost': 0.0,
  'datetime': '2022-12-28T15:47:19.000Z',
  'fee': {'cost': None, 'currency': None},
  'fees': [{'cost': None, 'currency': None}],
  'filled': 0.0,
  'id': '63ac65072efd7d0007c177bc',
  'info': {'cancelExist': True,
           'closeOrder': False,
           'createdAt': '1672242439000',
           'dealSize': '0',
           'dealValue': '0',
           'endAt': '1672242486000',
           'filledSize': '0',
           'filledValue': '0',
           'forceHold': False,
           'hidden': False,
           'iceberg': False,
           'id': '63ac65072efd7d0007c177bc',
           'isActive': False,
           'leverage': '5',
           'marginType': '0',
           'orderTime': '1672242439554375673',
           'postOnly': True,
           'price': '1100',
           'reduceOnly': False,
           'remark': 'Order Cancel:The order is canceled by user',
           'settleCurrency': 'USDT',
           'side': 'buy',
           'size': '1',
           'status': 'done',
           'stop': '',
           'stopPriceType': '',
           'stopTriggered': False,
           'stp': '',
           'symbol': 'ETHUSDTPERP',
           'timeInForce': 'GTC',
           'type': 'limit',
           'updatedAt': '1672242486000',
           'value': '11'},
  'lastTradeTimestamp': None,
  'postOnly': True,
  'price': 1100.0,
  'remaining': 1.0,
  'side': 'buy',
  'status': 'canceled',
  'stopPrice': None,
  'symbol': 'ETH/USDT:USDT',
  'timeInForce': 'GTC',
  'timestamp': 1672242439000,
  'trades': [],
  'type': 'limit'}]
```

**fetchOrder**
`python3 examples/py/cli.py poloniexfutures fetchOrder "63ac6613fd895f0007c83e48"`
```js
{'amount': 1.0,
 'average': None,
 'clientOrderId': None,
 'cost': 0.0,
 'datetime': '2022-12-28T15:51:47.000Z',
 'fee': {'cost': None, 'currency': None},
 'fees': [{'cost': None, 'currency': None}],
 'filled': 0.0,
 'id': '63ac6613fd895f0007c83e48',
 'info': {'cancelExist': False,
          'closeOrder': False,
          'createdAt': '1672242707000',
          'dealSize': '0',
          'dealValue': '0',
          'filledSize': '0',
          'filledValue': '0',
          'forceHold': False,
          'hidden': False,
          'iceberg': False,
          'id': '63ac6613fd895f0007c83e48',
          'isActive': True,
          'leverage': '5',
          'marginType': '0',
          'orderTime': '1672242707267535781',
          'postOnly': True,
          'price': '1100',
          'reduceOnly': False,
          'settleCurrency': 'USDT',
          'side': 'buy',
          'size': '1',
          'status': 'open',
          'stop': '',
          'stopPriceType': '',
          'stopTriggered': False,
          'stp': '',
          'symbol': 'ETHUSDTPERP',
          'timeInForce': 'GTC',
          'type': 'limit',
          'updatedAt': '1672242707000',
          'value': '11'},
 'lastTradeTimestamp': None,
 'postOnly': True,
 'price': 1100.0,
 'remaining': 1.0,
 'side': 'buy',
 'status': 'open',
 'stopPrice': None,
 'symbol': 'ETH/USDT:USDT',
 'timeInForce': 'GTC',
 'timestamp': 1672242707000,
 'trades': [],
 'type': 'limit'}
```

**fetchMyTrades**
`python3 examples/py/cli.py poloniexfutures fetchMyTrades`
```js
[
]
```

**setMarginMode**
`python3 examples/py/cli.py poloniexfutures setMarginMode 1 "BTC/USDT:USDT"`
```js
{'code': '200000'}
```

### CODE REVIEW

File: js/poloniexfutures.js [hunk 1]
```diff
@@ -0,0 +1,920 @@
...
+        url += tail;
+        const query = this.omit (params, path);
+        if (api === 'public') {
+            const queryLength = Object.keys (query).length;
+            if (queryLength) {
+                url += '?' + this.urlencode (query);
+            }
+        } else {
+            this.checkRequiredCredentials ();
+            if (method !== 'GET' && method !== 'HEAD') {
```
Comment (carlosmiei) [inline js/poloniexfutures.js:886]: so this is not right, 
you should only url-encode if Get or Head, so your if should be something like:

```Javascript
            const bodyEncoded = this.urlencode (query);
            if (method !== 'GET' && method !== 'HEAD') {
                body = query;
            } else {
                url += '?' + bodyEncoded;
            }
```

File: js/poloniexfutures.js [hunk 2]
```diff
@@ -0,0 +1,920 @@
...
+                body = this.urlencode (query);
+                url += '?' + body;
+            }
+            const now = this.milliseconds ().toString ();
+            let payload = now + method + tail;
```
Comment (carlosmiei) [inline js/poloniexfutures.js:891]: Your `payload` does not follow the spec, it should be something like:
image

but currently has this format: `1671555347881POST/api/v1/orders'`

You should construct it like this:
(pseudo-code)

```Javascript
payload = method + "\n" +
Access path + "\n" 
+ sorted URL-encoded query containing timestamp

Btw Poloniex has a python SDK you can check how they do the signing here: https://github.com/poloniex/polo-sdk-python/blob/0a58715c45767b794df0a29db5186de8987b81b7/polosdk/rest/request.py#L30

File: js/poloniexfutures.js [hunk 3]
```diff
@@ -0,0 +1,1628 @@
...
+                'versions': {
+                    'public': {
+                        'GET': {
+                            'ticker': 'v2',
+                            'tickers': 'v2',
+                            'level3/snapshot': 'v2',
+                        },
+                    },
+                },
+                'requiredCredentials': {
```
Comment (carlosmiei) [inline js/poloniexfutures.js:156]: `requiredCredentials` should be outside options

File: js/poloniexfutures.js [hunk 4]
```diff
@@ -0,0 +1,1628 @@
...
+            });
+        }
+        return result;
+    }
+
+    parseTicker (ticker, market = undefined) {
+        const marketId = this.safeString (ticker, 'symbol');
+        const symbol = this.safeSymbol (marketId, market);
+        let timestamp = this.safeNumber (ticker, 'ts');
+        timestamp = parseInt (timestamp / 1000000);
```
Comment (carlosmiei) [inline js/poloniexfutures.js:342]: You can replace this with `safeIntegerProduct(ticker, 'ts', 0.000001)`

File: js/poloniexfutures.js [hunk 5]
```diff
@@ -0,0 +1,1628 @@
...
+            'askVolume': this.safeString (ticker, 'bestAskSize'),
+            'vwap': undefined,
+            'open': undefined,
+            'close': last,
+            'last': last,
+            'previousClose': undefined,
+            'change': undefined,
+            'percentage': undefined,
+            'average': undefined,
+            'baseVolume': undefined,
```
Comment (carlosmiei) [inline js/poloniexfutures.js:362]: ins't size the baseVolume?
image

File: js/poloniexfutures.js [hunk 6]
```diff
@@ -0,0 +1,1628 @@
...
+            request['from'] = since;
+            if (limit === undefined) {
+                limit = this.safeInteger (this.options, 'fetchOHLCVLimit', 200);
+            }
+            endAt = this.sum (since, limit * duration);
+        } else if (limit !== undefined) {
+            since = endAt - limit * duration;
+            request['from'] = since;
+        }
+        request['to'] = endAt;
```
Comment (carlosmiei) [inline js/poloniexfutures.js:732]: this field is optional right? any reason for setting it?

File: js/poloniexfutures.js [hunk 7]
```diff
@@ -0,0 +1,1628 @@
...
+        params = this.omit (params, 'level');
+        if (level !== undefined && level !== 2 && level !== 3) {
+            throw new BadRequest (this.id + ' fetchOrderBook() can only return level 2 & 3');
+        }
+        const market = this.market (symbol);
+        const request = {
+            'symbol': market['id'],
+        };
+        let response = undefined;
+        if (level === 2) {
```
Comment (carlosmiei) [inline js/poloniexfutures.js:443]: I think we should make l2 default

File: js/poloniexfutures.js [hunk 8]
```diff
@@ -0,0 +1,1628 @@
...
+        //             "626659d83385c200072e690b",
+        //             "17.0",
+        //             "1000",
+        //             1650874840161291000
+        //         ],
+        //     ],
+        // }
+        //
+        const data = this.safeValue (response, 'data', {});
+        const timestamp = parseInt (this.safeInteger (data, 'ts') / 1000000);
```
Comment (carlosmiei) [inline js/poloniexfutures.js:495]: again it's preferable to use  `safeIntegerProduct` here if you don't mind

File: js/poloniexfutures.js [hunk 9]
```diff
@@ -0,0 +1,1628 @@
...
+        let orderbook = undefined;
+        if (level === 2) {
+            orderbook = this.parseOrderBook (data, market['symbol'], timestamp, 'bids', 'asks', 0, 1);
+        } else {
+            orderbook = this.parseOrderBook (data, market['symbol'], timestamp, 'bids', 'asks', 1, 2);
+        }
+        return orderbook;
```
Comment (carlosmiei) [inline js/poloniexfutures.js:502]: I think we're missing adding the nonce here:
```
orderbook['nonce'] = this.safeInteger(data, 'sequence')
```

File: js/poloniexfutures.js [hunk 10]
```diff
@@ -0,0 +1,1628 @@
...
+         * @param {int|undefined} limit max number of orders to return, default is undefined
+         * @param {object} params extra parameters specific to the blockchaincom api endpoint
+         * @returns {object} an [order book structure]{@link https://docs.ccxt.com/en/latest/manual.html#order-book-structure}
+         */
+        await this.loadMarkets ();
+        const market = this.market (symbol);
+        const request = {
+            'symbol': market['id'],
+        };
+        const response = await this.publicGetLevel3Snapshot (this.extend (request, params));
```
Comment (carlosmiei) [inline js/poloniexfutures.js:521]: Why don't you just call `fetchOrderBook` with level=3 in params?

File: js/poloniexfutures.js [hunk 11]
```diff
@@ -0,0 +1,1599 @@
...
+                        'status': 1,
+                        'kline/query': 1,
+                    },
+                    'post': {
+                        'bullet-public': 1,
+                    },
+                },
+                'private': {
+                    'get': {
+                        'account-overview': 10,
```
Comment (carlosmiei) [inline js/poloniexfutures.js:99]: Aren't we missing `marginMode` endpoints?
https://futures-docs.poloniex.com/#query-margin-mode
https://futures-docs.poloniex.com/#change-margin-mode

The latter can be used for `setMarginMode`

File: js/poloniexfutures.js [hunk 12]
```diff
@@ -0,0 +1,1599 @@
...
+                        'orders': 10,
+                        'stopOrders': 10,
+                        'recentDoneOrders': 10,
+                        'orders/{order-id}': 10,
+                        'fills': 10,
+                        'openOrderStatistics': 10,
+                        'position': 6.66,
+                        'positions': 6.66,
+                        'funding-history': 10,
+                    },
```
Comment (carlosmiei) [inline js/poloniexfutures.js:110]: Also batchOrders endpoint missing
https://futures-docs.poloniex.com/#place-multiple-orders

File: js/poloniexfutures.js [hunk 13]
```diff
@@ -0,0 +1,1628 @@
...
+            'leverage': 1,
+        };
+        const stopPrice = this.safeValue2 (params, 'triggerPrice', 'stopPrice');
+        if (stopPrice) {
+            request['stop'] = (side === 'buy') ? 'up' : 'down';
+            const stopPriceType = this.safeString (params, 'stopPriceType', 'TP');
+            request['stopPriceType'] = stopPriceType;
+            request['stopPrice'] = this.priceToPrecision (symbol, stopPrice);
+        }
+        const uppercaseType = type.toUpperCase ();
```
Comment (carlosmiei) [inline js/poloniexfutures.js:821]: why uppercasing here?

File: js/poloniexfutures.js [hunk 14]
```diff
@@ -0,0 +1,1628 @@
...
+        if (amount < 1) {
+            throw new InvalidOrder (this.id + ' createOrder() minimum contract order amount is 1');
+        }
+        const preciseAmount = parseInt (this.amountToPrecision (symbol, amount));
+        const request = {
+            'clientOid': clientOrderId,
+            'side': side,
+            'symbol': market['id'],
+            'type': type, // limit or market
+            'size': preciseAmount,
```
Comment (carlosmiei) [inline js/poloniexfutures.js:811]: is this quantity the cost? I
image

File: js/poloniexfutures.js (hunk 11 above)
Comment (AlgoQ) [reply js/poloniexfutures.js:99]: @carlosmiei Is there an example for `fetchMarginMode`? No results on a global search with as input: `'fetchMarginMode': true`

File: js/poloniexfutures.js [hunk 15]
```diff
@@ -0,0 +1,1628 @@
...
+            request['startAt'] = since;
+        }
+        if (until !== undefined) {
+            request['endAt'] = until;
+        }
+        const method = stop ? 'privateGetStopOrders' : 'privateGetOrders';
+        const response = await this[method] (this.extend (request, params));
+        const responseData = this.safeValue (response, 'data', {});
+        const orders = this.safeValue (responseData, 'items', []);
+        return this.parseOrders (orders, market, since, limit);
```
Comment (carlosmiei) [inline js/poloniexfutures.js:1279]: ccxt distinguishes closed orders from canceled orders, whereas poloniex don't, so we should probably filter them out here, no?
image

File: js/poloniexfutures.js [hunk 16]
```diff
@@ -0,0 +1,1628 @@
...
+        //    {
+        //        "symbol": ".BTCUSDTPERPFPI8H",
+        //        "granularity": 28800000,
+        //        "timePoint": 1558000800000,
+        //        "value": 0.00375,
+        //        "predictedValue": 0.00375
+        //    }
+        //
+        const data = this.safeValue (response, 'data');
+        const fundingTimestamp = this.safeNumber (data, 'timePoint');
```
Comment (carlosmiei) [inline js/poloniexfutures.js:1446]: let's avoid parsing timestamps as floats pls, use `safeInteger` instead

File: js/poloniexfutures.js [hunk 17]
```diff
@@ -0,0 +1,1599 @@
...
+        //                "bankruptPrice": 4021.75,                 // Bankruptcy price
+        //                "settleCurrency": "USDT",                 // Currency used to clear and settle the trades
+        //                "isInverse": false
+        //            }
+        //        ]
+        //    }
+        //
+        const symbol = this.safeString (position, 'symbol');
+        market = this.safeMarket (symbol, market);
+        const timestamp = this.safeNumber (position, 'currentTimestamp');
```
Comment (carlosmiei) [inline js/poloniexfutures.js:1053]: same here

File: js/poloniexfutures.js [hunk 18]
```diff
@@ -0,0 +1,1599 @@
...
+            'initialMarginPercentage': this.parseNumber (initialMarginPercentage),
+            'maintenanceMargin': this.safeNumber (position, 'posMaint'),
+            'maintenanceMarginPercentage': this.safeNumber (position, 'maintMarginReq'),
+            'entryPrice': this.safeNumber (position, 'avgEntryPrice'),
+            'notional': this.parseNumber (notional),
+            'leverage': this.safeNumber (position, 'realLeverage'),
+            'unrealizedPnl': this.parseNumber (unrealisedPnl),
+            'contracts': this.parseNumber (Precise.stringAbs (size)),
+            'contractSize': this.safeValue (market, 'contractSize'),
+            //     realisedPnl: position['realised_pnl'],
```
Comment (carlosmiei) [inline js/poloniexfutures.js:1085]: can we remove this comment?

File: js/poloniexfutures.js [hunk 19]
```diff
@@ -0,0 +1,1636 @@
...
+//  ---------------------------------------------------------------------------
+
+module.exports = class poloniexfutures extends Exchange {
+    describe () {
+        return this.deepExtend (super.describe (), {
+            'id': 'poloniexfutures',
+            'name': 'Poloniex Futures',
+            'countries': [ 'US' ],
+            // 3 requests per second for some unauthenticated market endpoints => 1000ms / 3 = 333ms between requests
+            'rateLimit': 333,
```
Comment (carlosmiei) [inline js/poloniexfutures.js:19]: @AlgoQ the RL value and weights are off, I think

The "lightest" endpoint allows 300 req / 10 sec --> 30 req per second, so RL would be 1000/30 = 33.333 (one req every 33ms = 1 cost)? 

So for order handling, we can fire 200 req/ 10 sec --> 20 req per second, 1 req every 50ms ---> 50/33.333 = 1.5 cost ?  

image

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p poloniexfutures fetchTicker "BTC/USDT:USDT"          
Python v3.10.8
CCXT v2.4.20
poloniexfutures.fetchTicker(BTC/USDT:USDT)
{'ask': 16522.7,
 'askVolume': 114.0,
 'average': None,
 'baseVolume': None,
 'bid': 16512.6,
 'bidVolume': 3.0,
 'change': None,
 'close': 16512.6,
 'datetime': '2022-12-30T12:53:19.847Z',
 'high': None,
 'info': {'bestAskPrice': '16522.7',
          'bestAskSize': '114',
          'bestBidPrice': '16512.6',
          'bestBidSize': '3',
          'price': '16512.6',
          'sequence': '11763597',
          'side': 'sell',
          'size': '2',
          'symbol': 'BTCUSDTPERP',
          'tradeId': '63aedf3f9fd7cf00012c5679',
          'ts': '1672404799847034663'},
 'last': 16512.6,
 'low': None,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': None,
 'symbol': 'BTC/USDT:USDT',
 'timestamp': 1672404799847,
 'vwap': None}
 ```

```
n poloniexfutures fetchOHLCV "BTC/USDT:USDT" 1h undefined 5          
Debugger attached.
2022-12-30T12:54:38.356Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.fetchOHLCV (BTC/USDT:USDT, 1h, , 5)
2022-12-30T12:54:41.276Z iteration 0 passed in 931 ms

1672387200000 | 16476.1 | 16505.4 | 16454.2 | 16500.1 | 2778
1672390800000 | 16500.1 |   16569 |   16500 | 16521.2 | 7991
1672394400000 | 16521.1 | 16538.4 | 16486.6 | 16486.6 | 3480
1672398000000 | 16486.6 |   16569 | 16486.6 | 16502.4 | 8024
1672401600000 | 16502.1 | 16516.2 | 16486.9 | 16515.9 | 3018
5 objects
2022-12-30T12:54:41.276Z iteration 1 passed in 931 ms
```


```
n poloniexfutures createOrder LTC/USDT:USDT limit buy 1 20 --verbose
Debugger attached.
2022-12-30T15:27:36.207Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.createOrder (LTC/USDT:USDT, limit, buy, 1, 20)
fetch Request:
 poloniexfutures POST https://futures-api.poloniex.com/api/v1/orders 
RequestHeaders:
 {
  'PF-API-SIGN': 'Eikiviw34gKYbchkeZwrs6hkWvl89DgVQtyL8rbVRbg=',
  'PF-API-TIMESTAMP': '1672414060073',
  'PF-API-KEY': '63a1e3cfd90c570007218387',
  'PF-API-PASSPHRASE': '20232023',
  'Content-Type': 'application/json'
} 
RequestBody:
 {"clientOid":"d1e692ad-397c-4c13-b789-2394b0581042","side":"buy","symbol":"LTCUSDTPERP","type":"limit","size":1,"leverage":1,"price":"20"} 

handleRestResponse:
 poloniexfutures POST https://futures-api.poloniex.com/api/v1/orders 200 OK 
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '781bcd044b06769e-LHR',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Fri, 30 Dec 2022 15:27:40 GMT',
  Expires: '0',
  Server: 'cloudflare',
  'Set-Cookie': 'AWSALB=35o0hMTK9PkchaD7Vi2R62QxPkGDSaWNknZ+3Em5jnlldHlsdWDQKJla/EU6aexClYSb+1VeokOsHrHzxy+ECS4EfkLrEbysyzRzX6356lLC/em+eoApIDDGnkqf; Expires=Fri, 06 Jan 2023 15:27:40 GMT; Path=/, AWSALBCORS=35o0hMTK9PkchaD7Vi2R62QxPkGDSaWNknZ+3Em5jnlldHlsdWDQKJla/EU6aexClYSb+1VeokOsHrHzxy+ECS4EfkLrEbysyzRzX6356lLC/em+eoApIDDGnkqf; Expires=Fri, 06 Jan 2023 15:27:40 GMT; Path=/; SameSite=None; Secure, X-TRACE=K1PrZFRhNos=; Path=/; HttpOnly',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Trace-Id': 'bdd40a1f1e361494',
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 {"code":"200000","data":{"orderId":"63af036cd0e1ad0007dbc13b"}} 

2022-12-30T15:27:40.484Z iteration 0 passed in 2689 ms

{
  id: '63af036cd0e1ad0007dbc13b',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: undefined,
  type: undefined,
  side: undefined,
  price: undefined,
  amount: undefined,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  stopPrice: undefined,
  info: { code: '200000', data: { orderId: '63af036cd0e1ad0007dbc13b' } }
}
2022-12-30T15:27:40.484Z iteration 1 passed in 2689 ms
```

```
 n poloniexfutures fetchOrder "63af036cd0e1ad0007dbc13b"             
Debugger attached.
2022-12-30T15:30:16.620Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.fetchOrder (63af036cd0e1ad0007dbc13b)
2022-12-30T15:30:19.170Z iteration 0 passed in 749 ms

{
  id: '63af036cd0e1ad0007dbc13b',
  clientOrderId: 'd1e692ad-397c-4c13-b789-2394b0581042',
  symbol: 'LTC/USDT:USDT',
  type: 'limit',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'buy',
  amount: 1,
  price: 20,
  stopPrice: undefined,
  cost: 0,
  filled: 0,
  remaining: 1,
  timestamp: 1672414060000,
  datetime: '2022-12-30T15:27:40.000Z',
  fee: { currency: undefined, cost: undefined },
  status: 'open',
  info: {
    symbol: 'LTCUSDTPERP',
    leverage: '1',
    hidden: false,
    forceHold: false,
    closeOrder: false,
    type: 'limit',
    isActive: true,
    createdAt: '1672414060000',
    orderTime: '1672414060378028678',
    price: '20',
    iceberg: false,
    stopTriggered: false,
    id: '63af036cd0e1ad0007dbc13b',
    value: '0.2',
    timeInForce: 'GTC',
    updatedAt: '1672414060000',
    side: 'buy',
    stopPriceType: '',
    dealValue: '0',
    dealSize: '0',
    settleCurrency: 'USDT',
    stp: '',
    filledValue: '0',
    postOnly: false,
    size: '1',
    stop: '',
    filledSize: '0',
    reduceOnly: false,
    marginType: '1',
    cancelExist: false,
    clientOid: 'd1e692ad-397c-4c13-b789-2394b0581042',
    status: 'open'
  },
  lastTradeTimestamp: undefined,
  average: undefined,
  trades: [],
  fees: [ { currency: undefined, cost: undefined } ]
}
2022-12-30T15:30:19.170Z iteration 1 passed in 749 ms

Waiting for the debugger to disconnect...
```

```
 n poloniexfutures cancelOrder "63af036cd0e1ad0007dbc13b"
Debugger attached.
2022-12-30T15:34:10.241Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.cancelOrder (63af036cd0e1ad0007dbc13b)
2022-12-30T15:34:12.752Z iteration 0 passed in 646 ms

{
  id: '63af036cd0e1ad0007dbc13b',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: undefined,
  type: undefined,
  side: undefined,
  price: undefined,
  amount: undefined,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  stopPrice: undefined,
  info: {
    code: '200000',
    data: {
      cancelFailedOrders: [],
      cancelledOrderIds: [ '63af036cd0e1ad0007dbc13b' ]
    }
  }
}
2022-12-30T15:34:12.752Z iteration 1 passed in 646 ms
```


```
 n poloniexfutures createOrder LTC/USDT:USDT market buy 1 
Debugger attached.
2022-12-30T15:35:04.888Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.createOrder (LTC/USDT:USDT, market, buy, 1)
2022-12-30T15:35:07.095Z iteration 0 passed in 726 ms

{
  id: '63af052a6a6d070007f24952',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: undefined,
  type: undefined,
  side: undefined,
  price: undefined,
  amount: undefined,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  stopPrice: undefined,
  info: { code: '200000', data: { orderId: '63af052a6a6d070007f24952' } }
}
2022-12-30T15:35:07.095Z iteration 1 passed in 726 ms

```

```
n poloniexfutures fetchOrder "63af052a6a6d070007f24952" 
Debugger attached.
2022-12-30T15:35:22.437Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.fetchOrder (63af052a6a6d070007f24952)
2022-12-30T15:35:25.178Z iteration 0 passed in 1823 ms

{
  id: '63af052a6a6d070007f24952',
  clientOrderId: 'f576e140-b7a3-4e29-99e9-86099a2c0d12',
  symbol: 'LTC/USDT:USDT',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'buy',
  amount: 1,
  price: 67.52,
  stopPrice: undefined,
  cost: 0.6752,
  filled: 1,
  remaining: 0,
  timestamp: 1672414507000,
  datetime: '2022-12-30T15:35:07.000Z',
  fee: { currency: undefined, cost: undefined },
  status: 'closed',
  info: {
    symbol: 'LTCUSDTPERP',
    leverage: '1',
    hidden: false,
    forceHold: false,
    closeOrder: false,
    type: 'market',
    isActive: false,
    createdAt: '1672414507000',
    orderTime: '1672414507022308260',
    iceberg: false,
    stopTriggered: false,
    id: '63af052a6a6d070007f24952',
    value: '0.675',
    timeInForce: 'GTC',
    updatedAt: '1672414507000',
    side: 'buy',
    stopPriceType: '',
    dealValue: '0.6752',
    dealSize: '1',
    settleCurrency: 'USDT',
    endAt: '1672414507000',
    stp: '',
    filledValue: '0.6752',
    postOnly: false,
    size: '1',
    stop: '',
    filledSize: '1',
    reduceOnly: false,
    marginType: '1',
    cancelExist: false,
    clientOid: 'f576e140-b7a3-4e29-99e9-86099a2c0d12',
    status: 'done'
  },
  lastTradeTimestamp: undefined,
  average: 67.52,
  trades: [],
  fees: [ { currency: undefined, cost: undefined } ]
}
2022-12-30T15:35:25.178Z iteration 1 passed in 1823 ms

```

```
p poloniexfutures fetchMyTrades  
Python v3.10.8
CCXT v2.4.20
poloniexfutures.fetchMyTrades()
[{'amount': 1.0,
  'cost': 0.6752,
  'datetime': '2022-12-30T15:35:07.071Z',
  'fee': {'cost': 0.00027008, 'currency': 'USDT', 'rate': 0.0004},
  'fees': [{'cost': 0.00027008, 'currency': 'USDT', 'rate': 0.0004}],
  'id': '63af052bb5e64b00019aed74',
  'info': {'createdAt': '1672414507071',
           'fee': '0.00027008',
           'feeCurrency': 'USDT',
           'feeRate': '0.0004',
           'fixFee': '0',
           'forceTaker': True,
           'liquidity': 'taker',
           'orderId': '63af052a6a6d070007f24952',
           'orderType': 'market',
           'price': '67.52',
           'settleCurrency': 'USDT',
           'side': 'buy',
           'size': '1',
           'stop': '',
           'symbol': 'LTCUSDTPERP',
           'tradeId': '63af052bb5e64b00019aed74',
           'tradeTime': '1672414507071584360',
           'tradeType': 'trade',
           'value': '0.6752'},
  'order': '63af052a6a6d070007f24952',
  'price': 67.52,
  'side': 'buy',
  'symbol': 'LTC/USDT:USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1672414507071,
  'type': 'market'}]
  ```

```
p poloniexfutures fetchPositions '["LTC/USDT:USDT"]'           
Python v3.10.8
CCXT v2.4.20
poloniexfutures.fetchPositions(['LTC/USDT:USDT'])
[{'collateral': 0.67574016,
  'contractSize': 0.01,
  'contracts': 1.0,
  'datetime': None,
  'entryPrice': 67.52,
  'id': None,
  'info': {'autoDeposit': False,
           'avgEntryPrice': '67.52',
           'bankruptPrice': '0.00',
           'currentComm': '0.00027008',
           'currentCost': '0.67520000',
           'currentQty': '1',
           'currentTimestamp': '1672415405505',
           'delevPercentage': '0.4',
           'id': '63af052bada2ec0007b0fc96',
           'isOpen': True,
           'liquidationPrice': '0.00',
           'maintMargin': '0.67574016',
           'maintMarginReq': '0.01',
           'marginType': '1',
           'markPrice': '67.88',
           'markValue': '0.67880000',
           'maxWithdrawMarginAmount': '0',
           'openingTimestamp': '1672414507168',
           'posComm': '0.00054016',
           'posCost': '0.67520000',
           'posCross': '0E-10',
           'posInit': '0.67520000',
           'posLoss': '0E-8',
           'posMaint': '0.00729216',
           'posMargin': '0.67574016',
           'realLeverage': '1.00',
           'realisedCost': '0.00027008',
           'realisedGrossCost': '0E-8',
           'realisedGrossPnl': '0E-8',
           'realisedPnl': '-0.00027008',
           'riskLimit': '1000000',
           'settleCurrency': 'USDT',
           'symbol': 'LTCUSDTPERP',
           'unrealisedCost': '0.67520000',
           'unrealisedPnl': '0.00360000',
           'unrealisedPnlPcnt': '0.0053',
           'unrealisedRoePcnt': '0.0053'},
  'initialMargin': 0.6752,
  'initialMarginPercentage': 1.0,
  'leverage': 1.0,
  'liquidationPrice': 0.0,
  'maintenanceMargin': 0.00729216,
  'maintenanceMarginPercentage': 0.01,
  'marginMode': 'isolated',
  'marginRatio': None,
  'markPrice': 67.88,
  'notional': 0.6752,
  'percentage': 0.005331753554502369,
  'side': 'long',
  'symbol': 'LTC/USDT:USDT',
  'timestamp': 1672415405505.0,
  'unrealizedPnl': 0.0036}]
  ```
  ```
   n poloniexfutures cancelAllOrders                                   
Debugger attached.
2022-12-30T15:51:56.937Z
Node.js: v17.9.0
CCXT v2.4.20
poloniexfutures.cancelAllOrders ()
2022-12-30T15:51:59.074Z iteration 0 passed in 685 ms

                      id | clientOrderId | timestamp | datetime | lastTradeTimestamp | symbol | type | side | price | amount | cost | average | filled | remaining | status | fee | trades | timeInForce | postOnly | stopPrice
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
63af0914f55f5f0007a8fca3 |               |           |          |                    |        |      |      |       |        |      |         |        |           |        |     |        |             |          |          
1 objects
```

**Review by carlosmiei — APPROVED** [review]
